namespace ProMaxx2.QA.Domain.Execution;

public sealed class AutomationQueueJob
{
    private AutomationQueueJob() { }
    public AutomationQueueJob(Guid projectId,Guid releaseId,Guid buildId,Guid?testCycleId,string targetApp,Guid?requestedBy,string?notes,string pack="Smoke",int maxAttempts=3,Guid?sourceScheduleId=null)
    {
        if(targetApp is not ("pos" or "app"))throw new ArgumentException("Target app must be pos or app.");
        if(pack is not ("Smoke" or "Regression"))throw new ArgumentException("Pack must be Smoke or Regression.");if(maxAttempts is<1 or>5)throw new ArgumentException("Max attempts must be 1 to 5.");AutomationQueueJobId=Guid.NewGuid();ProjectId=projectId;ReleaseId=releaseId;BuildId=buildId;TestCycleId=testCycleId;TargetApp=targetApp;RequestedBy=requestedBy;Notes=notes?.Trim();Pack=pack;MaxAttempts=maxAttempts;SourceScheduleId=sourceScheduleId;Status="Queued";RequestedAt=DateTime.UtcNow;
    }
    public Guid AutomationQueueJobId{get;private set;}public Guid ProjectId{get;private set;}public Guid ReleaseId{get;private set;}public Guid BuildId{get;private set;}public Guid?TestCycleId{get;private set;}public string TargetApp{get;private set;}="pos";public string Pack{get;private set;}="Smoke";public int MaxAttempts{get;private set;}=3;public Guid?SourceScheduleId{get;private set;}public string Status{get;private set;}="Queued";public Guid?RequestedBy{get;private set;}public DateTime RequestedAt{get;private set;}public string?RunnerName{get;private set;}public string?LeaseToken{get;private set;}public DateTime?LeaseExpiresAt{get;private set;}public int AttemptCount{get;private set;}public DateTime?ClaimedAt{get;private set;}public DateTime?StartedAt{get;private set;}public DateTime?CompletedAt{get;private set;}public Guid?AutomationRunId{get;private set;}public string?ErrorMessage{get;private set;}public string?ErrorType{get;private set;}public string?Notes{get;private set;}
    public string Claim(string runnerName,DateTime?now=null){if(Status!="Queued")throw new InvalidOperationException("Only queued jobs can be claimed.");if(string.IsNullOrWhiteSpace(runnerName))throw new ArgumentException("Runner name is required.");var at=now??DateTime.UtcNow;RunnerName=runnerName.Trim();LeaseToken=Guid.NewGuid().ToString("N");ClaimedAt=at;LeaseExpiresAt=at.AddMinutes(2);AttemptCount++;Status="Claimed";return LeaseToken;}
    public void RenewLease(string runnerName,string leaseToken,DateTime?now=null){if(Status is not ("Claimed" or "Running")||RunnerName!=runnerName.Trim()||LeaseToken!=leaseToken)throw new InvalidOperationException("Invalid queue lease.");LeaseExpiresAt=(now??DateTime.UtcNow).AddMinutes(2);}
    public bool RecoverExpiredLease(DateTime now){if(Status is not ("Claimed" or "Running")||!LeaseExpiresAt.HasValue||LeaseExpiresAt>now)return false;if(AttemptCount>=MaxAttempts){Status="Failed";CompletedAt=now;ErrorType="Infrastructure";ErrorMessage="Runner heartbeat expired after maximum retry attempts.";}else{Status="Queued";ErrorType="Infrastructure";ErrorMessage="Previous runner heartbeat expired; job returned to queue.";}RunnerName=null;LeaseToken=null;LeaseExpiresAt=null;ClaimedAt=null;StartedAt=null;return true;}
    public void Update(string leaseToken,string status,string?errorMessage,Guid?automationRunId,string?errorType=null){if(LeaseToken!=leaseToken)throw new InvalidOperationException("Invalid queue lease token.");if(status=="Running"&&Status=="Claimed"){Status="Running";StartedAt=DateTime.UtcNow;return;}if(status=="Failed"&&(Status is "Claimed" or "Running")&&IsRetryable(errorType)&&AttemptCount<MaxAttempts){Status="Queued";ErrorMessage=errorMessage?.Trim();ErrorType=errorType;RunnerName=null;LeaseToken=null;LeaseExpiresAt=null;ClaimedAt=null;StartedAt=null;return;}if((status is "Completed" or "Failed")&&(Status is "Claimed" or "Running")){Status=status;CompletedAt=DateTime.UtcNow;ErrorMessage=errorMessage?.Trim();ErrorType=errorType;AutomationRunId=automationRunId;return;}throw new InvalidOperationException($"Invalid queue transition {Status} -> {status}.");}
    private static bool IsRetryable(string?errorType)=>errorType is "Infrastructure" or "Timeout" or "ApplicationStart";
    public void Cancel(){if(Status is not ("Queued" or "Claimed"))throw new InvalidOperationException("Only queued or claimed jobs can be cancelled.");Status="Cancelled";CompletedAt=DateTime.UtcNow;}
}
