namespace ProMaxx2.QA.Domain.Execution;
public sealed class AutomationSchedule
{
 private AutomationSchedule(){}
 public AutomationSchedule(Guid projectId,Guid releaseId,Guid buildId,string name,string targetApp,string pack,string frequency,TimeOnly runAtUtc,int maxAttempts,Guid?createdBy,DateTime now){if(string.IsNullOrWhiteSpace(name))throw new ArgumentException("Schedule name is required.");if(targetApp is not("pos" or "app"))throw new ArgumentException("Target app must be pos or app.");if(pack is not("Smoke" or "Regression"))throw new ArgumentException("Pack must be Smoke or Regression.");if(frequency is not("Daily" or "Weekdays"))throw new ArgumentException("Frequency must be Daily or Weekdays.");if(maxAttempts is<1 or>5)throw new ArgumentException("Max attempts must be 1 to 5.");AutomationScheduleId=Guid.NewGuid();ProjectId=projectId;ReleaseId=releaseId;BuildId=buildId;Name=name.Trim();TargetApp=targetApp;Pack=pack;Frequency=frequency;RunAtUtc=runAtUtc;MaxAttempts=maxAttempts;CreatedBy=createdBy;CreatedAt=now;IsActive=true;NextRunAt=Next(now);}
 public Guid AutomationScheduleId{get;private set;}public Guid ProjectId{get;private set;}public Guid ReleaseId{get;private set;}public Guid BuildId{get;private set;}public string Name{get;private set;}="";public string TargetApp{get;private set;}="pos";public string Pack{get;private set;}="Smoke";public string Frequency{get;private set;}="Daily";public TimeOnly RunAtUtc{get;private set;}public int MaxAttempts{get;private set;}public bool IsActive{get;private set;}public DateTime NextRunAt{get;private set;}public DateTime?LastQueuedAt{get;private set;}public Guid?CreatedBy{get;private set;}public DateTime CreatedAt{get;private set;}
 public void MarkQueued(DateTime now){LastQueuedAt=now;NextRunAt=Next(now.AddSeconds(1));}public void Disable(){IsActive=false;}
 private DateTime Next(DateTime from){var candidate=from.Date.Add(RunAtUtc.ToTimeSpan());if(candidate<=from)candidate=candidate.AddDays(1);if(Frequency=="Weekdays")while(candidate.DayOfWeek is DayOfWeek.Saturday or DayOfWeek.Sunday)candidate=candidate.AddDays(1);return DateTime.SpecifyKind(candidate,DateTimeKind.Utc);}
}
