namespace ProMaxx2.QA.Domain.Execution;
public sealed class TestEnvironment
{
 private TestEnvironment(){}public TestEnvironment(Guid projectId,string name,string?url){if(projectId==Guid.Empty||string.IsNullOrWhiteSpace(name))throw new ArgumentException("Project and environment name are required.");TestEnvironmentId=Guid.NewGuid();ProjectId=projectId;EnvironmentName=name.Trim();BaseUrl=url?.Trim();IsActive=true;}public Guid TestEnvironmentId{get;private set;}public Guid ProjectId{get;private set;}public string EnvironmentName{get;private set;}=string.Empty;public string?BaseUrl{get;private set;}public bool IsActive{get;private set;}public void Update(string name,string?url,bool active){if(string.IsNullOrWhiteSpace(name))throw new ArgumentException("Environment name is required.");EnvironmentName=name.Trim();BaseUrl=url?.Trim();IsActive=active;}
}
public sealed class TestCycle
{
 private TestCycle(){}public TestCycle(Guid projectId,Guid releaseId,Guid buildId,Guid environmentId,Guid? suiteId,string code,string name,string?type,DateTime?start,DateTime?end,Guid?owner,string?notes,Guid?createdBy){if(new[]{projectId,releaseId,buildId,environmentId}.Any(x=>x==Guid.Empty))throw new ArgumentException("Project, release, build and environment are required.");Validate(code,name,start,end);TestCycleId=Guid.NewGuid();ProjectId=projectId;ReleaseId=releaseId;BuildId=buildId;EnvironmentId=environmentId;TestSuiteId=suiteId;CycleCode=code.Trim().ToUpperInvariant();CycleName=name.Trim();CycleType=type?.Trim();StartDate=start;EndDate=end;OwnerUserId=owner;Notes=notes?.Trim();Status="Draft";CreatedAt=DateTime.UtcNow;CreatedBy=createdBy;}public Guid TestCycleId{get;private set;}public Guid ProjectId{get;private set;}public Guid ReleaseId{get;private set;}public Guid BuildId{get;private set;}public Guid EnvironmentId{get;private set;}public Guid?TestSuiteId{get;private set;}public string CycleCode{get;private set;}=string.Empty;public string CycleName{get;private set;}=string.Empty;public string?CycleType{get;private set;}public DateTime?StartDate{get;private set;}public DateTime?EndDate{get;private set;}public Guid?OwnerUserId{get;private set;}public string Status{get;private set;}="Draft";public string?Notes{get;private set;}public DateTime CreatedAt{get;private set;}public Guid?CreatedBy{get;private set;}public ICollection<TestCycleCase>Cases{get;private set;}=[];public void Update(string name,string?type,DateTime?start,DateTime?end,Guid?owner,string?notes){Validate(CycleCode,name,start,end);CycleName=name.Trim();CycleType=type?.Trim();StartDate=start;EndDate=end;OwnerUserId=owner;Notes=notes?.Trim();}public void ChangeStatus(string status){string[]allowed=["Draft","InProgress","Completed","Closed","Cancelled"];Status=allowed.SingleOrDefault(x=>x.Equals(status,StringComparison.OrdinalIgnoreCase))??throw new ArgumentException("Invalid cycle status.");}private static void Validate(string code,string name,DateTime?start,DateTime?end){if(string.IsNullOrWhiteSpace(code)||string.IsNullOrWhiteSpace(name))throw new ArgumentException("Cycle code and name are required.");if(start.HasValue&&end.HasValue&&end<start)throw new ArgumentException("End date must be after start date.");}
}
public sealed class TestCycleCase{private TestCycleCase(){}public TestCycleCase(Guid cycleId,Guid caseId,int revision,string priority,int order){TestCycleCaseId=Guid.NewGuid();TestCycleId=cycleId;TestCaseId=caseId;TestCaseRevisionNo=revision;Priority=priority;ExecutionOrder=order;CurrentStatus="NotRun";}public Guid TestCycleCaseId{get;private set;}public Guid TestCycleId{get;private set;}public Guid TestCaseId{get;private set;}public int TestCaseRevisionNo{get;private set;}public Guid?AssignedTesterUserId{get;private set;}public string?Priority{get;private set;}public int ExecutionOrder{get;private set;}public string CurrentStatus{get;private set;}="NotRun";public TestCycle Cycle{get;private set;}=null!;public ProMaxx2.QA.Domain.TestManagement.TestCase TestCase{get;private set;}=null!;public ICollection<TestExecution>Executions{get;private set;}=[];public void SetStatus(string status){CurrentStatus=status;}}
public sealed class TestExecution
{
 private TestExecution(){}public TestExecution(Guid cycleCaseId,int executionNo,Guid buildId,Guid environmentId,Guid testerId,string status,string?actual,string?comment,IEnumerable<StepResultInput>steps){Validate(status);TestExecutionId=Guid.NewGuid();TestCycleCaseId=cycleCaseId;ExecutionNo=executionNo;BuildId=buildId;EnvironmentId=environmentId;TesterUserId=testerId;StartedAt=DateTime.UtcNow;CompletedAt=DateTime.UtcNow;Status=Normalize(status);ActualResult=actual?.Trim();Comment=comment?.Trim();StepResults=steps.Select(x=>new TestStepResult(TestExecutionId,x.StepNo,x.Status,x.ActualResult,x.Comment)).ToList();}public Guid TestExecutionId{get;private set;}public Guid TestCycleCaseId{get;private set;}public int ExecutionNo{get;private set;}public Guid BuildId{get;private set;}public Guid EnvironmentId{get;private set;}public Guid TesterUserId{get;private set;}public DateTime?StartedAt{get;private set;}public DateTime?CompletedAt{get;private set;}public string Status{get;private set;}=string.Empty;public string?ActualResult{get;private set;}public string?Comment{get;private set;}public TestCycleCase CycleCase{get;private set;}=null!;public ICollection<TestStepResult>StepResults{get;private set;}=[];private static void Validate(string status){if(!new[]{"Pass","Fail","Blocked","Skipped"}.Contains(status,StringComparer.OrdinalIgnoreCase))throw new ArgumentException("Execution status must be Pass, Fail, Blocked or Skipped.");}private static string Normalize(string status)=>new[]{"Pass","Fail","Blocked","Skipped"}.Single(x=>x.Equals(status,StringComparison.OrdinalIgnoreCase));
}
public sealed record StepResultInput(int StepNo,string Status,string?ActualResult,string?Comment);
public sealed class TestStepResult{private TestStepResult(){}public TestStepResult(Guid executionId,int stepNo,string status,string?actual,string?comment){if(!new[]{"Pass","Fail","Blocked","Skipped","NotRun"}.Contains(status,StringComparer.OrdinalIgnoreCase))throw new ArgumentException("Invalid step status.");TestStepResultId=Guid.NewGuid();TestExecutionId=executionId;StepNo=stepNo;Status=status;ActualResult=actual?.Trim();Comment=comment?.Trim();}public Guid TestStepResultId{get;private set;}public Guid TestExecutionId{get;private set;}public Guid?TestStepId{get;private set;}public int StepNo{get;private set;}public string Status{get;private set;}=string.Empty;public string?ActualResult{get;private set;}public string?Comment{get;private set;}public TestExecution Execution{get;private set;}=null!;}
