using ProMaxx2.QA.Domain.Execution;using ProMaxx2.QA.Application.Projects;
namespace ProMaxx2.QA.Application.Execution;
public sealed record PublishAutomationCaseResult(Guid?TestCaseId,string TestCaseCode,string Status,long DurationMs,string?ErrorMessage,string?EvidencePath);
public sealed record PublishAutomationRunRequest(Guid ProjectId,Guid?ReleaseId,Guid?BuildId,Guid?TestCycleId,string TargetApp,string?RunnerName,DateTime StartedAt,IReadOnlyList<PublishAutomationCaseResult>Results);
public sealed record AutomationRunCaseDto(Guid AutomationRunCaseId,Guid?TestCaseId,Guid?TestExecutionId,string TestCaseCode,string Status,long DurationMs,string?ErrorMessage,string?EvidencePath);
public sealed record AutomationRunDto(Guid AutomationRunId,Guid ProjectId,Guid?ReleaseId,Guid?BuildId,Guid?TestCycleId,string TargetApp,string Status,string?RunnerName,DateTime StartedAt,DateTime CompletedAt,int TotalCount,int PassedCount,int FailedCount,int SkippedCount,IReadOnlyList<AutomationRunCaseDto>Results);
public sealed record PublishAutomationQualityGateRequest(Guid ProjectId,Guid ReleaseId,Guid BuildId,string TargetApp,string BaselineBuild,string CurrentBuild,bool Passed,int NewMissingCount,int NewDuplicateCount,int RemovedCount,int ChangedCount,IReadOnlyList<string>?Messages,string?RunnerName,DateTime CompletedAt);
public sealed record AutomationQualityGateDto(Guid AutomationQualityGateRunId,Guid ProjectId,Guid ReleaseId,Guid BuildId,string TargetApp,string BaselineBuild,string CurrentBuild,string Status,int NewMissingCount,int NewDuplicateCount,int RemovedCount,int ChangedCount,string?Messages,string?RunnerName,DateTime CompletedAt);
public sealed record AutomationBuildGateStatusDto(Guid BuildId,string Status,bool IsReleaseBlocked,AutomationQualityGateDto?Pos,AutomationQualityGateDto?App);
public sealed record CreateAutomationQueueJobRequest(Guid ProjectId,Guid ReleaseId,Guid BuildId,Guid?TestCycleId,string TargetApp,string?Notes);
public sealed record ClaimAutomationQueueJobRequest(string RunnerName,IReadOnlyList<string>?TargetApps);
public sealed record UpdateAutomationQueueJobRequest(string LeaseToken,string Status,string?ErrorMessage,Guid?AutomationRunId,string?ErrorType);
public sealed record AutomationQueueJobDto(Guid AutomationQueueJobId,Guid ProjectId,Guid ReleaseId,Guid BuildId,Guid?TestCycleId,string TargetApp,string Pack,int MaxAttempts,Guid?SourceScheduleId,string Status,Guid?RequestedBy,DateTime RequestedAt,string?RunnerName,string?LeaseToken,DateTime?LeaseExpiresAt,int AttemptCount,DateTime?ClaimedAt,DateTime?StartedAt,DateTime?CompletedAt,Guid?AutomationRunId,string?ErrorMessage,string?ErrorType,string?Notes);
public sealed record AutomationRunnerHeartbeatRequest(string RunnerName,string MachineName,string Version,IReadOnlyList<string>Capabilities,string State,Guid?CurrentJobId,string?LeaseToken);
public sealed record AutomationRunnerAgentDto(Guid AutomationRunnerAgentId,Guid ProjectId,string RunnerName,string MachineName,string Version,IReadOnlyList<string>Capabilities,string State,Guid?CurrentJobId,DateTime RegisteredAt,DateTime LastHeartbeatAt,string Connectivity);
public sealed record CreateAutomationScheduleRequest(Guid ProjectId,Guid ReleaseId,Guid BuildId,string Name,string TargetApp,string Pack,string Frequency,TimeOnly RunAtUtc,int MaxAttempts);
public sealed record AutomationScheduleDto(Guid AutomationScheduleId,Guid ProjectId,Guid ReleaseId,Guid BuildId,string Name,string TargetApp,string Pack,string Frequency,TimeOnly RunAtUtc,int MaxAttempts,bool IsActive,DateTime NextRunAt,DateTime?LastQueuedAt,DateTime CreatedAt);
public sealed record AutomationNotificationDto(Guid AutomationQueueJobId,string Severity,string Title,string Message,string Status,string?ErrorType,int AttemptCount,int MaxAttempts,DateTime CreatedAt);
public interface IAutomationRunRepository{Task PublishAsync(AutomationRun run,Guid?testerId,CancellationToken ct);Task<IReadOnlyList<AutomationRunDto>>ListAsync(Guid projectId,int take,CancellationToken ct);Task<AutomationRunCase?>FindCaseAsync(Guid runId,Guid caseId,Guid projectId,CancellationToken ct);Task SaveAsync(CancellationToken ct);Task<AutomationQualityGateDto>PublishGateAsync(AutomationQualityGateRun gate,CancellationToken ct);Task<IReadOnlyList<AutomationQualityGateDto>>ListGatesAsync(Guid projectId,Guid?buildId,int take,CancellationToken ct);Task<AutomationQueueJobDto>CreateQueueJobAsync(AutomationQueueJob job,CancellationToken ct);Task<IReadOnlyList<AutomationQueueJobDto>>ListQueueJobsAsync(Guid projectId,Guid?buildId,int take,CancellationToken ct);Task<AutomationQueueJobDto?>ClaimQueueJobAsync(Guid projectId,string runnerName,IReadOnlyList<string>targetApps,CancellationToken ct);Task<AutomationQueueJob?>FindQueueJobAsync(Guid jobId,Guid projectId,CancellationToken ct);Task<AutomationRunnerAgentDto>HeartbeatAgentAsync(Guid projectId,AutomationRunnerHeartbeatRequest request,CancellationToken ct);Task<IReadOnlyList<AutomationRunnerAgentDto>>ListAgentsAsync(Guid projectId,CancellationToken ct);Task<AutomationScheduleDto>CreateScheduleAsync(AutomationSchedule schedule,CancellationToken ct);Task<IReadOnlyList<AutomationScheduleDto>>ListSchedulesAsync(Guid projectId,CancellationToken ct);Task<AutomationSchedule?>FindScheduleAsync(Guid id,Guid projectId,CancellationToken ct);Task<IReadOnlyList<AutomationNotificationDto>>ListNotificationsAsync(Guid projectId,CancellationToken ct);}
public sealed class AutomationRunService(IAutomationRunRepository repository)
{
 public async Task<AutomationRunDto>PublishAsync(PublishAutomationRunRequest r,Guid?testerId,CancellationToken ct){if(r.Results.Count==0)throw new ArgumentException("At least one result is required.");var run=new AutomationRun(r.ProjectId,r.ReleaseId,r.BuildId,r.TestCycleId,r.TargetApp,r.RunnerName,r.StartedAt,r.Results.Select(x=>new AutomationCaseResultInput(x.TestCaseId,x.TestCaseCode,x.Status,x.DurationMs,x.ErrorMessage,x.EvidencePath)));await repository.PublishAsync(run,testerId,ct);return (await repository.ListAsync(r.ProjectId,100,ct)).Single(x=>x.AutomationRunId==run.AutomationRunId);}
 public Task<IReadOnlyList<AutomationRunDto>>ListAsync(Guid projectId,int take,CancellationToken ct)=>repository.ListAsync(projectId,Math.Clamp(take,1,100),ct);
 public async Task AttachEvidenceAsync(Guid runId,Guid caseId,Guid projectId,string path,CancellationToken ct){var item=await repository.FindCaseAsync(runId,caseId,projectId,ct)??throw new EntityNotFoundException("Automation result not found.");item.AttachEvidence(path);await repository.SaveAsync(ct);}
 public async Task<string?>GetEvidencePathAsync(Guid runId,Guid caseId,Guid projectId,CancellationToken ct)=>(await repository.FindCaseAsync(runId,caseId,projectId,ct)??throw new EntityNotFoundException("Automation result not found.")).EvidencePath;
 public Task<IReadOnlyList<AutomationQualityGateDto>>ListGatesAsync(Guid projectId,Guid?buildId,int take,CancellationToken ct)=>repository.ListGatesAsync(projectId,buildId,Math.Clamp(take,1,100),ct);
 public async Task<AutomationQualityGateDto>PublishGateAsync(PublishAutomationQualityGateRequest r,CancellationToken ct){var gate=new AutomationQualityGateRun(r.ProjectId,r.ReleaseId,r.BuildId,r.TargetApp,r.BaselineBuild,r.CurrentBuild,r.Passed,r.NewMissingCount,r.NewDuplicateCount,r.RemovedCount,r.ChangedCount,r.Messages is null?null:string.Join(Environment.NewLine,r.Messages),r.RunnerName,r.CompletedAt);return await repository.PublishGateAsync(gate,ct);}
 public async Task<AutomationBuildGateStatusDto>GetBuildGateStatusAsync(Guid projectId,Guid buildId,CancellationToken ct){var gates=await repository.ListGatesAsync(projectId,buildId,100,ct);var pos=gates.FirstOrDefault(x=>x.TargetApp=="pos");var app=gates.FirstOrDefault(x=>x.TargetApp=="app");var status=pos is null||app is null?"Pending":pos.Status=="Passed"&&app.Status=="Passed"?"Passed":"Failed";return new(buildId,status,status!="Passed",pos,app);}
 public Task<IReadOnlyList<AutomationQueueJobDto>>ListQueueJobsAsync(Guid projectId,Guid?buildId,int take,CancellationToken ct)=>repository.ListQueueJobsAsync(projectId,buildId,Math.Clamp(take,1,100),ct);
 public async Task<AutomationQueueJobDto>CreateQueueJobAsync(CreateAutomationQueueJobRequest r,Guid?requestedBy,CancellationToken ct)=>await repository.CreateQueueJobAsync(new(r.ProjectId,r.ReleaseId,r.BuildId,r.TestCycleId,r.TargetApp,requestedBy,r.Notes),ct);
 public Task<AutomationQueueJobDto?>ClaimQueueJobAsync(Guid projectId,ClaimAutomationQueueJobRequest r,CancellationToken ct){var targets=(r.TargetApps??["pos","app"]).Distinct(StringComparer.OrdinalIgnoreCase).ToList();if(targets.Count==0||targets.Any(x=>x is not ("pos" or "app")))throw new ArgumentException("Target apps must contain pos or app.");return repository.ClaimQueueJobAsync(projectId,r.RunnerName,targets,ct);}
 public async Task<AutomationQueueJobDto>UpdateQueueJobAsync(Guid jobId,Guid projectId,UpdateAutomationQueueJobRequest r,CancellationToken ct){var job=await repository.FindQueueJobAsync(jobId,projectId,ct)??throw new EntityNotFoundException("Automation queue job not found.");job.Update(r.LeaseToken,r.Status,r.ErrorMessage,r.AutomationRunId,r.ErrorType);await repository.SaveAsync(ct);return (await repository.ListQueueJobsAsync(projectId,null,100,ct)).Single(x=>x.AutomationQueueJobId==jobId);}
 public async Task CancelQueueJobAsync(Guid jobId,Guid projectId,CancellationToken ct){var job=await repository.FindQueueJobAsync(jobId,projectId,ct)??throw new EntityNotFoundException("Automation queue job not found.");job.Cancel();await repository.SaveAsync(ct);}
 public Task<AutomationRunnerAgentDto>HeartbeatAgentAsync(Guid projectId,AutomationRunnerHeartbeatRequest r,CancellationToken ct){var caps=r.Capabilities.Select(x=>x.Trim().ToLowerInvariant()).Distinct().ToList();if(caps.Count==0||caps.Any(x=>x is not ("pos" or "app")))throw new ArgumentException("Capabilities must contain pos or app.");return repository.HeartbeatAgentAsync(projectId,r with{Capabilities=caps},ct);}
 public Task<IReadOnlyList<AutomationRunnerAgentDto>>ListAgentsAsync(Guid projectId,CancellationToken ct)=>repository.ListAgentsAsync(projectId,ct);
 public Task<AutomationScheduleDto>CreateScheduleAsync(CreateAutomationScheduleRequest r,Guid?createdBy,CancellationToken ct)=>repository.CreateScheduleAsync(new(r.ProjectId,r.ReleaseId,r.BuildId,r.Name,r.TargetApp,r.Pack,r.Frequency,r.RunAtUtc,r.MaxAttempts,createdBy,DateTime.UtcNow),ct);
 public Task<IReadOnlyList<AutomationScheduleDto>>ListSchedulesAsync(Guid projectId,CancellationToken ct)=>repository.ListSchedulesAsync(projectId,ct);
 public async Task DisableScheduleAsync(Guid id,Guid projectId,CancellationToken ct){var schedule=await repository.FindScheduleAsync(id,projectId,ct)??throw new EntityNotFoundException("Automation schedule not found.");schedule.Disable();await repository.SaveAsync(ct);}
 public Task<IReadOnlyList<AutomationNotificationDto>>ListNotificationsAsync(Guid projectId,CancellationToken ct)=>repository.ListNotificationsAsync(projectId,ct);
}
