using ProMaxx2.QA.Application.Projects;using ProMaxx2.QA.Domain.Execution;
namespace ProMaxx2.QA.Application.Execution;
public sealed record ExecutionStepDto(int StepNo,string Action,string?TestData,string ExpectedResult,string?LastStatus=null,string?LastActualResult=null);public sealed record ExecutionHistoryDto(Guid TestExecutionId,int ExecutionNo,string Status,string?ActualResult,string?Comment,string TesterName,DateTime?CompletedAt,string?CreatedDefectCode=null);public sealed record CycleCaseQueueItemDto(Guid TestCycleCaseId,Guid TestCaseId,string TestCaseCode,string Title,string Priority,string CurrentStatus,int ExecutionOrder,Guid ModuleId,string?ModuleCode,string?ModuleName);public sealed record CycleCaseDetailDto(Guid TestCycleCaseId,Guid TestCaseId,string TestCaseCode,string Title,string?Preconditions,string Priority,string CurrentStatus,int ExecutionOrder,Guid ModuleId,string?ModuleCode,string?ModuleName,IReadOnlyList<ExecutionStepDto>Steps,IReadOnlyList<ExecutionHistoryDto>History);public sealed record ExecutionWorkspaceDto(Guid TestCycleId,string CycleCode,string CycleName,string Status,string BuildNumber,string EnvironmentName,IReadOnlyList<CycleCaseQueueItemDto>Cases);public sealed record SaveStepResultRequest(int StepNo,string Status,string?ActualResult,string?Comment);public sealed record CreateExecutionRequest(string Status,string?ActualResult,string?Comment,IReadOnlyList<SaveStepResultRequest>StepResults);
public interface IExecutionRepository{Task<ExecutionWorkspaceDto?>WorkspaceAsync(Guid cycleId,CancellationToken ct);Task<CycleCaseDetailDto?>CaseDetailAsync(Guid cycleId,Guid cycleCaseId,CancellationToken ct);Task<TestCycleCase?>FindCycleCaseAsync(Guid id,CancellationToken ct);Task<TestExecution?>FindExecutionAsync(Guid id,CancellationToken ct);Task<string?>LatestActiveStatusAsync(Guid cycleCaseId,Guid excludingExecutionId,CancellationToken ct);Task<int>NextExecutionNoAsync(Guid id,CancellationToken ct);Task AddAsync(TestExecution entity,CancellationToken ct);Task SaveAsync(CancellationToken ct);}
public sealed class ExecutionService(IExecutionRepository repository){public async Task<ExecutionWorkspaceDto>WorkspaceAsync(Guid id,CancellationToken ct)=>await repository.WorkspaceAsync(id,ct)??throw new EntityNotFoundException("Test cycle not found.");public async Task<CycleCaseDetailDto?>CaseDetailAsync(Guid cycleId,Guid cycleCaseId,CancellationToken ct)=>await repository.CaseDetailAsync(cycleId,cycleCaseId,ct);public async Task<ExecutionHistoryDto>CreateAsync(Guid cycleCaseId,CreateExecutionRequest r,Guid?testerId,CancellationToken ct){if(!testerId.HasValue)throw new ArgumentException("Tester identity is required.");var cycleCase=await repository.FindCycleCaseAsync(cycleCaseId,ct)??throw new EntityNotFoundException("Test cycle case not found.");if(cycleCase.Cycle.Status=="Completed")throw new ArgumentException("ไม่สามารถบันทึกผลได้ เนื่องจาก Test Cycle เสร็จสิ้นแล้ว");
            // Server เป็นผู้คำนวณ Overall Result เองเสมอจากผล Step (test-case-execution-ui-spec.md §25) —
            // ไม่เชื่อค่า r.Status ที่ client ส่งมาโดยตรง ยกเว้นกรณี Skipped ซึ่งเป็นการกระทำระดับ
            // Test Case โดยเฉพาะ (เลิกใช้ Test Case แล้ว ไม่เกี่ยวกับผลของ Step เลย)
            var overall=r.Status=="Skipped"?"Skipped":OverallResultCalculator.Calculate(r.StepResults.Select(x=>x.Status));
            var execution=new TestExecution(cycleCaseId,await repository.NextExecutionNoAsync(cycleCaseId,ct),cycleCase.Cycle.BuildId,cycleCase.Cycle.EnvironmentId,testerId.Value,overall,r.ActualResult,r.Comment,r.StepResults.Select(x=>new StepResultInput(x.StepNo,x.Status,x.ActualResult,x.Comment)));cycleCase.SetStatus(execution.Status);await repository.AddAsync(execution,ct);await repository.SaveAsync(ct);return new(execution.TestExecutionId,execution.ExecutionNo,execution.Status,execution.ActualResult,execution.Comment,"Current User",execution.CompletedAt);}public async Task DeleteAsync(Guid executionId,Guid?userId,CancellationToken ct){var execution=await repository.FindExecutionAsync(executionId,ct)??throw new EntityNotFoundException("Execution not found.");execution.SoftDelete(userId);var latest=await repository.LatestActiveStatusAsync(execution.TestCycleCaseId,executionId,ct);execution.CycleCase.SetStatus(latest??"NotRun");await repository.SaveAsync(ct);}}
