using Microsoft.EntityFrameworkCore;using ProMaxx2.QA.Application.Execution;using ProMaxx2.QA.Domain.Execution;
namespace ProMaxx2.QA.Infrastructure.Persistence;
public sealed class AutomationRunRepository(QaDbContext db):IAutomationRunRepository
{
 public async Task PublishAsync(AutomationRun run,Guid?testerId,CancellationToken ct)
 {
  await using Microsoft.EntityFrameworkCore.Storage.IDbContextTransaction? transaction=db.Database.IsRelational()?await db.Database.BeginTransactionAsync(ct):null;
  if(run.TestCycleId.HasValue)
  {
   if(!testerId.HasValue)throw new ArgumentException("Tester identity is required when linking an automation run to a test cycle.");
   var cycle=await db.TestCycles.Include(x=>x.Cases).SingleOrDefaultAsync(x=>x.TestCycleId==run.TestCycleId&&!x.IsDeleted,ct)??throw new ArgumentException("Test cycle not found.");
   if(cycle.ProjectId!=run.ProjectId)throw new ArgumentException("Test cycle does not belong to the automation run project.");
   if(cycle.Status is "Completed" or "Closed" or "Cancelled")throw new ArgumentException("Cannot publish automation results to a closed test cycle.");
   if(run.ReleaseId.HasValue&&run.ReleaseId!=cycle.ReleaseId)throw new ArgumentException("Release does not match the test cycle.");
   if(run.BuildId.HasValue&&run.BuildId!=cycle.BuildId)throw new ArgumentException("Build does not match the test cycle.");
   foreach(var result in run.Results)
   {
    if(!result.TestCaseId.HasValue)throw new ArgumentException($"{result.TestCaseCode} is missing testCaseId required for cycle linking.");
    var cycleCase=cycle.Cases.SingleOrDefault(x=>x.TestCaseId==result.TestCaseId)??throw new ArgumentException($"{result.TestCaseCode} is not included in the selected test cycle.");
    var nextNo=(await db.TestExecutions.Where(x=>x.TestCycleCaseId==cycleCase.TestCycleCaseId).Select(x=>(int?)x.ExecutionNo).MaxAsync(ct)??0)+1;
    var status=result.Status switch{"Passed"=>"Pass","Failed"=>"Fail","Blocked"=>"Blocked",_=>"Skipped"};
    var execution=new TestExecution(cycleCase.TestCycleCaseId,nextNo,cycle.BuildId,cycle.EnvironmentId,testerId.Value,status,result.ErrorMessage,$"Automation: {run.RunnerName??run.TargetApp}",[]);
    cycleCase.SetStatus(status);result.LinkExecution(execution.TestExecutionId);await db.TestExecutions.AddAsync(execution,ct);
   }
  }
  await db.AutomationRuns.AddAsync(run,ct);await db.SaveChangesAsync(ct);if(transaction is not null)await transaction.CommitAsync(ct);
 }
 public async Task<IReadOnlyList<AutomationRunDto>>ListAsync(Guid projectId,int take,CancellationToken ct)=>await db.AutomationRuns.AsNoTracking().Where(x=>x.ProjectId==projectId).OrderByDescending(x=>x.CompletedAt).Take(take).Select(x=>new AutomationRunDto(x.AutomationRunId,x.ProjectId,x.ReleaseId,x.BuildId,x.TestCycleId,x.TargetApp,x.Status,x.RunnerName,x.StartedAt,x.CompletedAt,x.TotalCount,x.PassedCount,x.FailedCount,x.SkippedCount,x.Results.OrderBy(r=>r.TestCaseCode).Select(r=>new AutomationRunCaseDto(r.AutomationRunCaseId,r.TestCaseId,r.TestExecutionId,r.TestCaseCode,r.Status,r.DurationMs,r.ErrorMessage,r.EvidencePath)).ToList())).ToListAsync(ct);
 public Task<AutomationRunCase?>FindCaseAsync(Guid runId,Guid caseId,Guid projectId,CancellationToken ct)=>db.AutomationRunCases.Include(x=>x.Run).SingleOrDefaultAsync(x=>x.AutomationRunId==runId&&x.AutomationRunCaseId==caseId&&x.Run.ProjectId==projectId,ct);
 public Task SaveAsync(CancellationToken ct)=>db.SaveChangesAsync(ct);
 public async Task<AutomationQualityGateDto>PublishGateAsync(AutomationQualityGateRun gate,CancellationToken ct)
 {
  var build=await db.Builds.AsNoTracking().Include(x=>x.Release).SingleOrDefaultAsync(x=>x.BuildId==gate.BuildId,ct)??throw new ArgumentException("Build not found.");
  if(build.ReleaseId!=gate.ReleaseId||build.Release.ProjectId!=gate.ProjectId)throw new ArgumentException("Project, release and build do not match.");
  await db.AutomationQualityGateRuns.AddAsync(gate,ct);await db.SaveChangesAsync(ct);return MapGate(gate);
 }
 public async Task<IReadOnlyList<AutomationQualityGateDto>>ListGatesAsync(Guid projectId,Guid?buildId,int take,CancellationToken ct)=>await db.AutomationQualityGateRuns.AsNoTracking().Where(x=>x.ProjectId==projectId&&(!buildId.HasValue||x.BuildId==buildId)).OrderByDescending(x=>x.CompletedAt).Take(take).Select(x=>new AutomationQualityGateDto(x.AutomationQualityGateRunId,x.ProjectId,x.ReleaseId,x.BuildId,x.TargetApp,x.BaselineBuild,x.CurrentBuild,x.Status,x.NewMissingCount,x.NewDuplicateCount,x.RemovedCount,x.ChangedCount,x.Messages,x.RunnerName,x.CompletedAt)).ToListAsync(ct);
 private static AutomationQualityGateDto MapGate(AutomationQualityGateRun x)=>new(x.AutomationQualityGateRunId,x.ProjectId,x.ReleaseId,x.BuildId,x.TargetApp,x.BaselineBuild,x.CurrentBuild,x.Status,x.NewMissingCount,x.NewDuplicateCount,x.RemovedCount,x.ChangedCount,x.Messages,x.RunnerName,x.CompletedAt);
 public async Task<AutomationQueueJobDto>CreateQueueJobAsync(AutomationQueueJob job,CancellationToken ct)
 {
  var build=await db.Builds.AsNoTracking().Include(x=>x.Release).SingleOrDefaultAsync(x=>x.BuildId==job.BuildId&&x.IsActive,ct)??throw new ArgumentException("Active build not found.");if(build.ReleaseId!=job.ReleaseId||build.Release.ProjectId!=job.ProjectId)throw new ArgumentException("Project, release and build do not match.");
  if(job.TestCycleId.HasValue){var cycle=await db.TestCycles.AsNoTracking().SingleOrDefaultAsync(x=>x.TestCycleId==job.TestCycleId&&!x.IsDeleted,ct)??throw new ArgumentException("Test cycle not found.");if(cycle.ProjectId!=job.ProjectId||cycle.ReleaseId!=job.ReleaseId||cycle.BuildId!=job.BuildId)throw new ArgumentException("Test cycle does not match the selected build.");if(cycle.Status is "Completed" or "Closed" or "Cancelled")throw new ArgumentException("Cannot queue automation for a closed test cycle.");}
  await db.AutomationQueueJobs.AddAsync(job,ct);await db.SaveChangesAsync(ct);return MapJob(job);
 }
 public async Task<IReadOnlyList<AutomationQueueJobDto>>ListQueueJobsAsync(Guid projectId,Guid?buildId,int take,CancellationToken ct){await ProcessSchedulesAndRecoverAsync(projectId,ct);return (await db.AutomationQueueJobs.AsNoTracking().Where(x=>x.ProjectId==projectId&&(!buildId.HasValue||x.BuildId==buildId)).OrderByDescending(x=>x.RequestedAt).Take(take).ToListAsync(ct)).Select(x=>MapJob(x)).ToList();}
 public async Task<AutomationQueueJobDto?>ClaimQueueJobAsync(Guid projectId,string runnerName,IReadOnlyList<string>targetApps,CancellationToken ct)
 {
  await using Microsoft.EntityFrameworkCore.Storage.IDbContextTransaction? transaction=db.Database.IsRelational()?await db.Database.BeginTransactionAsync(System.Data.IsolationLevel.Serializable,ct):null;await ProcessSchedulesAndRecoverAsync(projectId,ct);var job=await db.AutomationQueueJobs.Where(x=>x.ProjectId==projectId&&x.Status=="Queued"&&targetApps.Contains(x.TargetApp)).OrderBy(x=>x.RequestedAt).FirstOrDefaultAsync(ct);if(job is null){if(transaction is not null)await transaction.CommitAsync(ct);return null;}job.Claim(runnerName);await db.SaveChangesAsync(ct);if(transaction is not null)await transaction.CommitAsync(ct);return MapJob(job,true);
 }
 public Task<AutomationQueueJob?>FindQueueJobAsync(Guid jobId,Guid projectId,CancellationToken ct)=>db.AutomationQueueJobs.SingleOrDefaultAsync(x=>x.AutomationQueueJobId==jobId&&x.ProjectId==projectId,ct);
 public async Task<AutomationRunnerAgentDto>HeartbeatAgentAsync(Guid projectId,AutomationRunnerHeartbeatRequest r,CancellationToken ct)
 {
  var now=DateTime.UtcNow;await ProcessSchedulesAndRecoverAsync(projectId,ct);var agent=await db.AutomationRunnerAgents.SingleOrDefaultAsync(x=>x.ProjectId==projectId&&x.RunnerName==r.RunnerName.Trim(),ct);var caps=string.Join(',',r.Capabilities);
  if(agent is null){agent=new(projectId,r.RunnerName,r.MachineName,r.Version,caps,now);await db.AutomationRunnerAgents.AddAsync(agent,ct);}agent.Heartbeat(r.MachineName,r.Version,caps,r.State,r.CurrentJobId,now);
  if(r.CurrentJobId.HasValue&&!string.IsNullOrWhiteSpace(r.LeaseToken)){var job=await db.AutomationQueueJobs.SingleOrDefaultAsync(x=>x.ProjectId==projectId&&x.AutomationQueueJobId==r.CurrentJobId,ct)??throw new InvalidOperationException("Current queue job not found.");job.RenewLease(r.RunnerName,r.LeaseToken,now);}
  await db.SaveChangesAsync(ct);return MapAgent(agent,now);
 }
 public async Task<IReadOnlyList<AutomationRunnerAgentDto>>ListAgentsAsync(Guid projectId,CancellationToken ct){var now=DateTime.UtcNow;return (await db.AutomationRunnerAgents.AsNoTracking().Where(x=>x.ProjectId==projectId).OrderByDescending(x=>x.LastHeartbeatAt).ToListAsync(ct)).Select(x=>MapAgent(x,now)).ToList();}
 public async Task<AutomationScheduleDto>CreateScheduleAsync(AutomationSchedule schedule,CancellationToken ct){var build=await db.Builds.AsNoTracking().Include(x=>x.Release).SingleOrDefaultAsync(x=>x.BuildId==schedule.BuildId&&x.IsActive,ct)??throw new ArgumentException("Active build not found.");if(build.ReleaseId!=schedule.ReleaseId||build.Release.ProjectId!=schedule.ProjectId)throw new ArgumentException("Project, release and build do not match.");await db.AutomationSchedules.AddAsync(schedule,ct);await db.SaveChangesAsync(ct);return MapSchedule(schedule);}
 public async Task<IReadOnlyList<AutomationScheduleDto>>ListSchedulesAsync(Guid projectId,CancellationToken ct)=>await db.AutomationSchedules.AsNoTracking().Where(x=>x.ProjectId==projectId&&x.IsActive).OrderBy(x=>x.NextRunAt).Select(x=>new AutomationScheduleDto(x.AutomationScheduleId,x.ProjectId,x.ReleaseId,x.BuildId,x.Name,x.TargetApp,x.Pack,x.Frequency,x.RunAtUtc,x.MaxAttempts,x.IsActive,x.NextRunAt,x.LastQueuedAt,x.CreatedAt)).ToListAsync(ct);
 public Task<AutomationSchedule?>FindScheduleAsync(Guid id,Guid projectId,CancellationToken ct)=>db.AutomationSchedules.SingleOrDefaultAsync(x=>x.AutomationScheduleId==id&&x.ProjectId==projectId,ct);
 public async Task<IReadOnlyList<AutomationNotificationDto>>ListNotificationsAsync(Guid projectId,CancellationToken ct)=>await db.AutomationQueueJobs.AsNoTracking().Where(x=>x.ProjectId==projectId&&((x.Status=="Failed")||(x.Status=="Queued"&&x.AttemptCount>0))).OrderByDescending(x=>x.CompletedAt??x.RequestedAt).Take(50).Select(x=>new AutomationNotificationDto(x.AutomationQueueJobId,x.Status=="Failed"?"Error":"Warning",x.Status=="Failed"?"Automation failed":"Automation retry queued",x.ErrorMessage??"Automation runner did not complete the job.",x.Status,x.ErrorType,x.AttemptCount,x.MaxAttempts,x.CompletedAt??x.RequestedAt)).ToListAsync(ct);
 private async Task ProcessSchedulesAndRecoverAsync(Guid projectId,CancellationToken ct){var now=DateTime.UtcNow;var due=await db.AutomationSchedules.Where(x=>x.ProjectId==projectId&&x.IsActive&&x.NextRunAt<=now).ToListAsync(ct);foreach(var schedule in due){await db.AutomationQueueJobs.AddAsync(new(schedule.ProjectId,schedule.ReleaseId,schedule.BuildId,null,schedule.TargetApp,schedule.CreatedBy,$"Scheduled: {schedule.Name}",schedule.Pack,schedule.MaxAttempts,schedule.AutomationScheduleId),ct);schedule.MarkQueued(now);}var leased=await db.AutomationQueueJobs.Where(x=>x.ProjectId==projectId&&(x.Status=="Claimed"||x.Status=="Running")&&x.LeaseExpiresAt<=now).ToListAsync(ct);var changed=leased.Any(x=>x.RecoverExpiredLease(now));if(due.Count>0||changed)await db.SaveChangesAsync(ct);}
 public async Task<int>RunScheduledWorkAsync(CancellationToken ct){var now=DateTime.UtcNow;var due=await db.AutomationSchedules.Where(x=>x.IsActive&&x.NextRunAt<=now).ToListAsync(ct);foreach(var schedule in due){await db.AutomationQueueJobs.AddAsync(new(schedule.ProjectId,schedule.ReleaseId,schedule.BuildId,null,schedule.TargetApp,schedule.CreatedBy,$"Scheduled: {schedule.Name}",schedule.Pack,schedule.MaxAttempts,schedule.AutomationScheduleId),ct);schedule.MarkQueued(now);}var leased=await db.AutomationQueueJobs.Where(x=>(x.Status=="Claimed"||x.Status=="Running")&&x.LeaseExpiresAt<=now).ToListAsync(ct);var recovered=leased.Count(x=>x.RecoverExpiredLease(now));var changes=due.Count+recovered;if(changes>0)await db.SaveChangesAsync(ct);return changes;}
 private static AutomationQueueJobDto MapJob(AutomationQueueJob x,bool includeLease=false)=>new(x.AutomationQueueJobId,x.ProjectId,x.ReleaseId,x.BuildId,x.TestCycleId,x.TargetApp,x.Pack,x.MaxAttempts,x.SourceScheduleId,x.Status,x.RequestedBy,x.RequestedAt,x.RunnerName,includeLease?x.LeaseToken:null,x.LeaseExpiresAt,x.AttemptCount,x.ClaimedAt,x.StartedAt,x.CompletedAt,x.AutomationRunId,x.ErrorMessage,x.ErrorType,x.Notes);
 private static AutomationScheduleDto MapSchedule(AutomationSchedule x)=>new(x.AutomationScheduleId,x.ProjectId,x.ReleaseId,x.BuildId,x.Name,x.TargetApp,x.Pack,x.Frequency,x.RunAtUtc,x.MaxAttempts,x.IsActive,x.NextRunAt,x.LastQueuedAt,x.CreatedAt);
 private static AutomationRunnerAgentDto MapAgent(AutomationRunnerAgent x,DateTime now)=>new(x.AutomationRunnerAgentId,x.ProjectId,x.RunnerName,x.MachineName,x.Version,x.Capabilities.Split(',',StringSplitOptions.RemoveEmptyEntries),x.State,x.CurrentJobId,x.RegisteredAt,x.LastHeartbeatAt,now-x.LastHeartbeatAt<=TimeSpan.FromSeconds(60)?"Online":"Offline");
}
public sealed class AutomationRunConfiguration:Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<AutomationRun>{public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<AutomationRun>b){b.ToTable("AutomationRuns");b.HasKey(x=>x.AutomationRunId);b.Property(x=>x.TargetApp).HasMaxLength(10);b.Property(x=>x.Status).HasMaxLength(20);b.Property(x=>x.RunnerName).HasMaxLength(100);b.HasMany(x=>x.Results).WithOne(x=>x.Run).HasForeignKey(x=>x.AutomationRunId).OnDelete(DeleteBehavior.Cascade);b.HasOne(x=>x.Cycle).WithMany().HasForeignKey(x=>x.TestCycleId).OnDelete(DeleteBehavior.Restrict);b.HasIndex(x=>new{x.ProjectId,x.CompletedAt});}}
public sealed class AutomationRunCaseConfiguration:Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<AutomationRunCase>{public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<AutomationRunCase>b){b.ToTable("AutomationRunCases");b.HasKey(x=>x.AutomationRunCaseId);b.Property(x=>x.TestCaseCode).HasMaxLength(100);b.Property(x=>x.Status).HasMaxLength(20);b.Property(x=>x.ErrorMessage).HasMaxLength(2000);b.Property(x=>x.EvidencePath).HasMaxLength(1000);b.HasOne(x=>x.Execution).WithOne().HasForeignKey<AutomationRunCase>(x=>x.TestExecutionId).OnDelete(DeleteBehavior.Restrict);}}
public sealed class AutomationQualityGateRunConfiguration:Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<AutomationQualityGateRun>{public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<AutomationQualityGateRun>b){b.ToTable("AutomationQualityGateRuns");b.HasKey(x=>x.AutomationQualityGateRunId);b.Property(x=>x.TargetApp).HasMaxLength(10);b.Property(x=>x.BaselineBuild).HasMaxLength(100);b.Property(x=>x.CurrentBuild).HasMaxLength(100);b.Property(x=>x.Status).HasMaxLength(20);b.Property(x=>x.Messages).HasMaxLength(4000);b.Property(x=>x.RunnerName).HasMaxLength(100);b.HasIndex(x=>new{x.ProjectId,x.BuildId,x.TargetApp,x.CompletedAt});}}
public sealed class AutomationQueueJobConfiguration:Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<AutomationQueueJob>{public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<AutomationQueueJob>b){b.ToTable("AutomationQueueJobs");b.HasKey(x=>x.AutomationQueueJobId);b.Property(x=>x.TargetApp).HasMaxLength(10);b.Property(x=>x.Pack).HasMaxLength(20).HasDefaultValue("Smoke");b.Property(x=>x.MaxAttempts).HasDefaultValue(3);b.Property(x=>x.Status).HasMaxLength(20);b.Property(x=>x.RunnerName).HasMaxLength(100);b.Property(x=>x.LeaseToken).HasMaxLength(64);b.Property(x=>x.ErrorType).HasMaxLength(30);b.Property(x=>x.ErrorMessage).HasMaxLength(2000);b.Property(x=>x.Notes).HasMaxLength(1000);b.HasIndex(x=>new{x.Status,x.TargetApp,x.RequestedAt});b.HasIndex(x=>new{x.ProjectId,x.BuildId,x.RequestedAt});}}
public sealed class AutomationRunnerAgentConfiguration:Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<AutomationRunnerAgent>{public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<AutomationRunnerAgent>b){b.ToTable("AutomationRunnerAgents");b.HasKey(x=>x.AutomationRunnerAgentId);b.Property(x=>x.RunnerName).HasMaxLength(100);b.Property(x=>x.MachineName).HasMaxLength(100);b.Property(x=>x.Version).HasMaxLength(50);b.Property(x=>x.Capabilities).HasMaxLength(100);b.Property(x=>x.State).HasMaxLength(20);b.HasIndex(x=>new{x.ProjectId,x.RunnerName}).IsUnique();b.HasIndex(x=>new{x.ProjectId,x.LastHeartbeatAt});}}
public sealed class AutomationScheduleConfiguration:Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<AutomationSchedule>{public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<AutomationSchedule>b){b.ToTable("AutomationSchedules");b.HasKey(x=>x.AutomationScheduleId);b.Property(x=>x.Name).HasMaxLength(160);b.Property(x=>x.TargetApp).HasMaxLength(10);b.Property(x=>x.Pack).HasMaxLength(20);b.Property(x=>x.Frequency).HasMaxLength(20);b.HasIndex(x=>new{x.ProjectId,x.IsActive,x.NextRunAt});}}
