using Microsoft.EntityFrameworkCore;using ProMaxx2.QA.Application.Execution;using ProMaxx2.QA.Domain.Execution;using ProMaxx2.QA.Application.Common;
namespace ProMaxx2.QA.Infrastructure.Persistence;
public sealed class ExecutionRepository(QaDbContext db,ProjectAccessContext projectCtx):IExecutionRepository
{
 public async Task<ExecutionWorkspaceDto?>WorkspaceAsync(Guid cycleId,CancellationToken ct){var q=db.TestCycles.AsNoTracking().Where(x=>x.TestCycleId==cycleId&&!x.IsDeleted);var allowed=projectCtx.AllowedProjectIds;if(allowed.Length>0)q=q.Where(x=>allowed.Contains(x.ProjectId));return await q.Select(x=>new ExecutionWorkspaceDto(x.TestCycleId,x.CycleCode,x.CycleName,x.Status,db.Builds.Where(b=>b.BuildId==x.BuildId).Select(b=>b.BuildNumber).First(),db.TestEnvironments.Where(e=>e.TestEnvironmentId==x.EnvironmentId).Select(e=>e.EnvironmentName).First(),x.Cases.OrderBy(c=>c.ExecutionOrder).Select(c=>new CycleCaseQueueItemDto(c.TestCycleCaseId,c.TestCaseId,c.TestCase.TestCaseCode,c.TestCase.Title,c.Priority??c.TestCase.Priority,c.CurrentStatus,c.ExecutionOrder,c.TestCase.ModuleId,db.Modules.Where(m=>m.ModuleId==c.TestCase.ModuleId).Select(m=>m.ModuleCode).First(),db.Modules.Where(m=>m.ModuleId==c.TestCase.ModuleId).Select(m=>m.ModuleName).First())).ToList())).SingleOrDefaultAsync(ct);}
 public async Task<CycleCaseDetailDto?>CaseDetailAsync(Guid cycleId,Guid cycleCaseId,CancellationToken ct){
    var q=db.TestCycleCases.AsNoTracking().Where(x=>x.TestCycleId==cycleId&&x.TestCycleCaseId==cycleCaseId&&!x.Cycle.IsDeleted);var allowed=projectCtx.AllowedProjectIds;if(allowed.Length>0)q=q.Where(x=>allowed.Contains(x.Cycle.ProjectId));
    var detail=await q.Select(x=>new CycleCaseDetailDto(x.TestCycleCaseId,x.TestCaseId,x.TestCase.TestCaseCode,x.TestCase.Title,x.TestCase.Preconditions,x.Priority??x.TestCase.Priority,x.CurrentStatus,x.ExecutionOrder,x.TestCase.ModuleId,db.Modules.Where(m=>m.ModuleId==x.TestCase.ModuleId).Select(m=>m.ModuleCode).First(),db.Modules.Where(m=>m.ModuleId==x.TestCase.ModuleId).Select(m=>m.ModuleName).First(),x.TestCase.Steps.Where(s=>s.RevisionNo==x.TestCaseRevisionNo).OrderBy(s=>s.StepNo).Select(s=>new ExecutionStepDto(s.StepNo,s.Action,s.TestDataText,s.ExpectedResult,null,null)).ToList(),x.Executions.Where(e=>!e.IsDeleted).OrderByDescending(e=>e.ExecutionNo).Select(e=>new ExecutionHistoryDto(e.TestExecutionId,e.ExecutionNo,e.Status,e.ActualResult,e.Comment,db.Users.Where(u=>u.UserId==e.TesterUserId).Select(u=>u.DisplayName).First(),e.CompletedAt)).ToList())).SingleOrDefaultAsync(ct);
    if(detail is null)return null;
    // Pre-fill each step with its most recently saved result so the workspace remembers prior per-step input
    // instead of always resetting to "NotRun"/blank whenever the case is reopened or the detail is refetched.
    var latestByStep=(await db.TestStepResults.AsNoTracking().Where(r=>r.Execution.TestCycleCaseId==cycleCaseId&&!r.Execution.IsDeleted).OrderByDescending(r=>r.Execution.ExecutionNo).Select(r=>new{r.StepNo,r.Status,r.ActualResult}).ToListAsync(ct)).GroupBy(r=>r.StepNo).ToDictionary(g=>g.Key,g=>g.First());
    var steps=detail.Steps.Select(s=>latestByStep.TryGetValue(s.StepNo,out var last)?s with{LastStatus=last.Status,LastActualResult=last.ActualResult}:s).ToList();
    return detail with{Steps=steps};
 }
 public async Task<TestCycleCase?>FindCycleCaseAsync(Guid id,CancellationToken ct){var allowed=projectCtx.AllowedProjectIds;var e=await db.TestCycleCases.Include(x=>x.Cycle).SingleOrDefaultAsync(x=>x.TestCycleCaseId==id&&!x.Cycle.IsDeleted,ct);if(e is not null&&allowed.Length>0&&!allowed.Contains(e.Cycle.ProjectId))return null;return e;}public async Task<TestExecution?>FindExecutionAsync(Guid id,CancellationToken ct){var allowed=projectCtx.AllowedProjectIds;var e=await db.TestExecutions.Include(x=>x.CycleCase).ThenInclude(cc=>cc.Cycle).SingleOrDefaultAsync(x=>x.TestExecutionId==id&&!x.IsDeleted,ct);if(e is not null&&allowed.Length>0&&!(e.CycleCase?.Cycle is null)&&!allowed.Contains(e.CycleCase.Cycle.ProjectId))return null;return e;}public Task<string?>LatestActiveStatusAsync(Guid cycleCaseId,Guid excludingExecutionId,CancellationToken ct)=>db.TestExecutions.Where(x=>x.TestCycleCaseId==cycleCaseId&&!x.IsDeleted&&x.TestExecutionId!=excludingExecutionId).OrderByDescending(x=>x.ExecutionNo).Select(x=>x.Status).FirstOrDefaultAsync(ct);public async Task<int>NextExecutionNoAsync(Guid id,CancellationToken ct)=>(await db.TestExecutions.Where(x=>x.TestCycleCaseId==id).Select(x=>(int?)x.ExecutionNo).MaxAsync(ct)??0)+1;public Task AddAsync(TestExecution e,CancellationToken ct)=>db.TestExecutions.AddAsync(e,ct).AsTask();public Task SaveAsync(CancellationToken ct)=>db.SaveChangesAsync(ct);
}
