using Microsoft.EntityFrameworkCore;
using ProMaxx2.QA.Application.Projects;
using ProMaxx2.QA.Domain.Projects;

namespace ProMaxx2.QA.Infrastructure.Persistence;

public sealed class ProjectRepository(QaDbContext db,ProMaxx2.QA.Application.Common.ProjectAccessContext projectCtx):IProjectRepository
{
    public async Task<IReadOnlyList<ProjectDto>> ListAsync(CancellationToken ct)=>await db.Projects.AsNoTracking().OrderBy(x=>x.ProjectCode).Select(x=>new ProjectDto(x.ProjectId,x.ProjectCode,x.ProjectName,x.Description,x.Status,x.OwnerUserId,x.IsActive,x.CreatedAt)).ToListAsync(ct);
    public async Task<IReadOnlyList<ProjectDto>> ListForUserAsync(Guid userId,CancellationToken ct)=>await db.Projects.AsNoTracking().Where(x=>db.ProjectUsers.Any(pu=>pu.ProjectId==x.ProjectId&&pu.UserId==userId)).OrderBy(x=>x.ProjectCode).Select(x=>new ProjectDto(x.ProjectId,x.ProjectCode,x.ProjectName,x.Description,x.Status,x.OwnerUserId,x.IsActive,x.CreatedAt)).ToListAsync(ct);
    public Task<ProjectDto?> GetAsync(Guid id,CancellationToken ct)=>db.Projects.AsNoTracking().Where(x=>x.ProjectId==id).Select(x=>new ProjectDto(x.ProjectId,x.ProjectCode,x.ProjectName,x.Description,x.Status,x.OwnerUserId,x.IsActive,x.CreatedAt)).SingleOrDefaultAsync(ct);
    public Task<bool> ProjectCodeExistsAsync(string code,CancellationToken ct)=>db.Projects.AnyAsync(x=>x.ProjectCode==code,ct); public Task AddAsync(Project project,CancellationToken ct)=>db.Projects.AddAsync(project,ct).AsTask(); public Task<Project?> FindAsync(Guid id,CancellationToken ct)=>db.Projects.SingleOrDefaultAsync(x=>x.ProjectId==id,ct);
    public async Task<IReadOnlyList<ModuleDto>> ListModulesAsync(Guid projectId,CancellationToken ct)=>await db.Modules.AsNoTracking().Where(x=>x.ProjectId==projectId).OrderBy(x=>x.SortOrder).ThenBy(x=>x.ModuleCode).Select(x=>new ModuleDto(x.ModuleId,x.ProjectId,x.ParentModuleId,x.ModuleCode,x.ModuleName,x.Description,x.OwnerUserId,x.IsActive,x.SortOrder)).ToListAsync(ct);
    public async Task<IReadOnlyList<ProductModule>> ListModuleEntitiesAsync(Guid projectId,CancellationToken ct)=>await db.Modules.Where(x=>x.ProjectId==projectId).ToListAsync(ct);
    public Task<bool> ModuleCodeExistsAsync(Guid projectId,string code,CancellationToken ct)=>db.Modules.AnyAsync(x=>x.ProjectId==projectId&&x.ModuleCode==code,ct);public async Task<ProductModule?> FindModuleAsync(Guid id,CancellationToken ct){var allowed=projectCtx.AllowedProjectIds;return allowed.Length==0?await db.Modules.SingleOrDefaultAsync(x=>x.ModuleId==id,ct):await db.Modules.SingleOrDefaultAsync(x=>x.ModuleId==id&&allowed.Contains(x.ProjectId),ct);}public Task AddModuleAsync(ProductModule module,CancellationToken ct)=>db.Modules.AddAsync(module,ct).AsTask();public async Task<bool> ModuleHasReferencesAsync(Guid moduleId,CancellationToken ct)=>await db.Requirements.AnyAsync(x=>x.ModuleId==moduleId,ct)||await db.TestCases.AnyAsync(x=>x.ModuleId==moduleId,ct)||await db.Defects.AnyAsync(x=>x.ModuleId==moduleId,ct);public Task SaveChangesAsync(CancellationToken ct)=>db.SaveChangesAsync(ct);
    public async Task AddProjectUserAsync(Guid userId,Guid projectId,CancellationToken ct){if(!await db.ProjectUsers.AnyAsync(x=>x.UserId==userId&&x.ProjectId==projectId,ct)){db.ProjectUsers.Add(new ProMaxx2.QA.Domain.Identity.ProjectUser(projectId,userId,null));await db.SaveChangesAsync(ct);}}
    public async Task<IReadOnlyList<string>>ListProjectCodesAsync(string prefix,CancellationToken ct)=>await db.Projects.AsNoTracking().Where(x=>x.ProjectCode.StartsWith(prefix)).Select(x=>x.ProjectCode).ToListAsync(ct);
    public async Task<IReadOnlyList<string>>ListModuleCodesAsync(Guid projectId,string prefix,CancellationToken ct)=>await db.Modules.AsNoTracking().Where(x=>x.ProjectId==projectId&&x.ModuleCode.StartsWith(prefix)).Select(x=>x.ModuleCode).ToListAsync(ct);
}
