using Microsoft.EntityFrameworkCore;
using ProMaxx2.QA.Domain.Identity;
using ProMaxx2.QA.Domain.Projects;
using ProMaxx2.QA.Domain.Releases;
using ProMaxx2.QA.Domain.Requirements;
using ProMaxx2.QA.Domain.TestManagement;
using ProMaxx2.QA.Domain.Execution;
using ProMaxx2.QA.Domain.Defects;
using ProMaxx2.QA.Domain.Settings;
using ProMaxx2.QA.Domain.Dashboard;
using ProMaxx2.QA.Domain.Governance;
using ProMaxx2.QA.Domain.Automation;

namespace ProMaxx2.QA.Infrastructure.Persistence;

public sealed class QaDbContext(DbContextOptions<QaDbContext> options) : DbContext(options)
{
    public DbSet<User> Users => Set<User>();
    public DbSet<Role> Roles => Set<Role>();
    public DbSet<Permission> Permissions => Set<Permission>();
    public DbSet<UserRole> UserRoles => Set<UserRole>();
    public DbSet<RolePermission> RolePermissions => Set<RolePermission>();
    public DbSet<Project> Projects => Set<Project>();
    public DbSet<ProductModule> Modules => Set<ProductModule>();
    public DbSet<Release> Releases => Set<Release>();
    public DbSet<Build> Builds => Set<Build>();
    public DbSet<Requirement> Requirements => Set<Requirement>();
    public DbSet<RequirementRevision> RequirementRevisions => Set<RequirementRevision>();
    public DbSet<TestCase> TestCases => Set<TestCase>();
    public DbSet<TestStep> TestSteps => Set<TestStep>();
    public DbSet<TestCaseRevision> TestCaseRevisions => Set<TestCaseRevision>();
    public DbSet<RequirementTestCase> RequirementTestCases => Set<RequirementTestCase>();
    public DbSet<TestSuite> TestSuites => Set<TestSuite>();
    public DbSet<TestSuiteCase> TestSuiteCases => Set<TestSuiteCase>();
    public DbSet<TestEnvironment> TestEnvironments => Set<TestEnvironment>();
    public DbSet<TestCycle> TestCycles => Set<TestCycle>();
    public DbSet<TestCycleCase> TestCycleCases => Set<TestCycleCase>();
    public DbSet<TestExecution> TestExecutions => Set<TestExecution>();
    public DbSet<RegressionAnalysis> RegressionAnalyses => Set<RegressionAnalysis>();
    public DbSet<RegressionActivity> RegressionActivities => Set<RegressionActivity>();
    public DbSet<RegressionProfile> RegressionProfiles => Set<RegressionProfile>();
    public DbSet<RegressionSchedule> RegressionSchedules => Set<RegressionSchedule>();
    public DbSet<TestStepResult> TestStepResults => Set<TestStepResult>();
    public DbSet<Defect> Defects => Set<Defect>();
    public DbSet<DefectActivity> DefectActivities => Set<DefectActivity>();
    public DbSet<DefectTestCaseLink> DefectTestCaseLinks => Set<DefectTestCaseLink>();
    public DbSet<MasterOption> MasterOptions => Set<MasterOption>();
    public DbSet<AiConfiguration> AiConfigurations => Set<AiConfiguration>();
    public DbSet<DashboardShare> DashboardShares => Set<DashboardShare>();
    public DbSet<ProjectUser> ProjectUsers => Set<ProjectUser>();
    public DbSet<RiskAcceptance> RiskAcceptances => Set<RiskAcceptance>();
    public DbSet<ReleaseSignoff> ReleaseSignoffs => Set<ReleaseSignoff>();
    public DbSet<AutomationCase> AutomationCases => Set<AutomationCase>();
    public DbSet<AutomationVersion> AutomationVersions => Set<AutomationVersion>();
    public DbSet<AutomationAction> AutomationActions => Set<AutomationAction>();
    public DbSet<AutomationObject> AutomationObjects => Set<AutomationObject>();
    public DbSet<AutomationAgent> AutomationAgents => Set<AutomationAgent>();
    public DbSet<AutomationAgentCapability> AutomationAgentCapabilities => Set<AutomationAgentCapability>();
    public DbSet<AutomationExecution> AutomationExecutions => Set<AutomationExecution>();
    public DbSet<AutomationStepResult> AutomationStepResults => Set<AutomationStepResult>();
    public DbSet<AutomationJob> AutomationJobs => Set<AutomationJob>();
    public DbSet<AutomationEvidence> AutomationEvidences => Set<AutomationEvidence>();
    public DbSet<AutomationObjectVerification> AutomationObjectVerifications => Set<AutomationObjectVerification>();
    public DbSet<AutomationRetryPolicySettings> AutomationRetryPolicySettings => Set<AutomationRetryPolicySettings>();
    public DbSet<AutomationSuite> AutomationSuites => Set<AutomationSuite>();
    public DbSet<AutomationSuiteCase> AutomationSuiteCases => Set<AutomationSuiteCase>();
    public DbSet<AutomationSuiteRevision> AutomationSuiteRevisions => Set<AutomationSuiteRevision>();

    protected override void OnModelCreating(ModelBuilder modelBuilder) => modelBuilder.ApplyConfigurationsFromAssembly(typeof(QaDbContext).Assembly);
}
