using Microsoft.EntityFrameworkCore;using ProMaxx2.QA.Application.Projects;using ProMaxx2.QA.Application.TestManagement;using ProMaxx2.QA.Domain.TestManagement;using ProMaxx2.QA.Application.Common;
namespace ProMaxx2.QA.Infrastructure.Persistence;
public sealed class TestSuiteRepository(QaDbContext db,ProjectAccessContext projectCtx):ITestSuiteRepository
{
 private IQueryable<TestSuiteDto>Project(IQueryable<TestSuite>q)=>q.Select(x=>new TestSuiteDto(x.TestSuiteId,x.ProjectId,x.SuiteCode,x.SuiteName,x.SuiteType,x.Description,x.RiskTier,x.IsActive,db.TestCycles.Count(c=>c.TestSuiteId==x.TestSuiteId&&!c.IsDeleted),x.Cases.OrderBy(c=>c.SortOrder).Select(c=>new SuiteCaseDto(c.TestCaseId,c.TestCase.TestCaseCode,c.TestCase.Title,c.TestCase.Priority,c.SortOrder,c.IsRequired)).ToList()));
 public async Task<IReadOnlyList<TestSuiteDto>>ListAsync(Guid?projectId,string?search,CancellationToken ct){var q=db.TestSuites.AsNoTracking();if(projectId.HasValue)q=q.Where(x=>x.ProjectId==projectId);else if(projectCtx.AllowedProjectIds.Length>0)q=q.Where(x=>projectCtx.AllowedProjectIds.Contains(x.ProjectId));else q=q.Where(_=>false);if(!string.IsNullOrWhiteSpace(search))q=q.Where(x=>x.SuiteCode.Contains(search)||x.SuiteName.Contains(search));return await Project(q.OrderBy(x=>x.SuiteCode)).ToListAsync(ct);}public Task<TestSuiteDto?>GetAsync(Guid id,CancellationToken ct)=>Project(db.TestSuites.AsNoTracking().Where(x=>x.TestSuiteId==id)).SingleOrDefaultAsync(ct);public Task<TestSuite?>FindAsync(Guid id,CancellationToken ct)=>db.TestSuites.SingleOrDefaultAsync(x=>x.TestSuiteId==id,ct);public Task<bool>CodeExistsAsync(Guid projectId,string code,Guid?excludeId,CancellationToken ct)=>db.TestSuites.AnyAsync(x=>x.ProjectId==projectId&&x.SuiteCode==code&&(!excludeId.HasValue||x.TestSuiteId!=excludeId),ct);public Task AddAsync(TestSuite suite,CancellationToken ct)=>db.TestSuites.AddAsync(suite,ct).AsTask();
 public async Task AddCasesAsync(Guid id,IReadOnlyList<Guid>caseIds,bool required,CancellationToken ct){var existing=await db.TestSuiteCases.Where(x=>x.TestSuiteId==id).Select(x=>x.TestCaseId).ToListAsync(ct);var valid=await db.TestCases.Where(x=>caseIds.Contains(x.TestCaseId)&&!x.IsDeleted).Select(x=>x.TestCaseId).ToListAsync(ct);var next=await db.TestSuiteCases.Where(x=>x.TestSuiteId==id).Select(x=>(int?)x.SortOrder).MaxAsync(ct)??0;db.TestSuiteCases.AddRange(valid.Except(existing).Select((caseId,index)=>new TestSuiteCase(id,caseId,next+index+1,required)));}
 public async Task UpdateCaseAsync(Guid id,Guid caseId,int sortOrder,bool required,CancellationToken ct){var link=await db.TestSuiteCases.SingleOrDefaultAsync(x=>x.TestSuiteId==id&&x.TestCaseId==caseId,ct)??throw new EntityNotFoundException("Suite case not found.");var previousOrder=link.SortOrder;var occupied=await db.TestSuiteCases.SingleOrDefaultAsync(x=>x.TestSuiteId==id&&x.TestCaseId!=caseId&&x.SortOrder==sortOrder,ct);occupied?.Update(previousOrder,occupied.IsRequired);link.Update(sortOrder,required);}
 public async Task RemoveCaseAsync(Guid id,Guid caseId,CancellationToken ct){var link=await db.TestSuiteCases.FindAsync([id,caseId],ct);if(link is not null)db.TestSuiteCases.Remove(link);}public Task SaveAsync(CancellationToken ct)=>db.SaveChangesAsync(ct);
}
