using Microsoft.EntityFrameworkCore;using ProMaxx2.QA.Application.Execution;using ProMaxx2.QA.Application.Projects;using ProMaxx2.QA.Application.TestManagement;using ProMaxx2.QA.Domain.Execution;using ProMaxx2.QA.Application.Common;
namespace ProMaxx2.QA.Infrastructure.Persistence;
public sealed class TestCycleRepository(QaDbContext db,ProjectAccessContext projectCtx):ITestCycleRepository
{
 public async Task<IReadOnlyList<EnvironmentDto>>EnvironmentsAsync(Guid?projectId,CancellationToken ct){var q=db.TestEnvironments.AsNoTracking().AsQueryable();if(projectId.HasValue)q=q.Where(x=>x.ProjectId==projectId);else if(projectCtx.AllowedProjectIds.Length>0)q=q.Where(x=>projectCtx.AllowedProjectIds.Contains(x.ProjectId));else q=q.Where(_=>false);return await q.OrderBy(x=>x.EnvironmentName).Select(x=>new EnvironmentDto(x.TestEnvironmentId,x.ProjectId,x.EnvironmentName,x.BaseUrl,x.IsActive)).ToListAsync(ct);}public Task AddEnvironmentAsync(TestEnvironment e,CancellationToken ct)=>db.TestEnvironments.AddAsync(e,ct).AsTask();
 private IQueryable<TestCycleDto>Project(IQueryable<TestCycle>q)=>q.Select(x=>new TestCycleDto(x.TestCycleId,x.ProjectId,x.ReleaseId,db.Releases.Where(r=>r.ReleaseId==x.ReleaseId).Select(r=>r.ReleaseCode).First(),x.BuildId,db.Builds.Where(b=>b.BuildId==x.BuildId).Select(b=>b.BuildNumber).First(),x.EnvironmentId,db.TestEnvironments.Where(e=>e.TestEnvironmentId==x.EnvironmentId).Select(e=>e.EnvironmentName).First(),x.TestSuiteId,db.TestSuites.Where(s=>s.TestSuiteId==x.TestSuiteId).Select(s=>s.SuiteName).FirstOrDefault(),x.CycleCode,x.CycleName,x.CycleType,x.StartDate,x.EndDate,x.OwnerUserId,x.Status,x.Notes,x.Cases.Count,x.Cases.Count(c=>c.CurrentStatus!="NotRun"),x.Cases.Count==0?0:Math.Round(x.Cases.Count(c=>c.CurrentStatus!="NotRun")*100m/x.Cases.Count,2),new List<SuiteModuleDto>(),x.CreatedBy,db.Users.Where(u=>u.UserId==x.CreatedBy).Select(u=>u.DisplayName).FirstOrDefault(),x.CreatedAt));
 public async Task<TestCycleListResultDto>ListAsync(Guid?projectId,Guid?releaseId,Guid?buildId,Guid?moduleId,string?search,string?status,string?cycleType,Guid?createdBy,int page,int size,CancellationToken ct){
    var q=db.TestCycles.AsNoTracking().Where(x=>!x.IsDeleted);if(projectId.HasValue)q=q.Where(x=>x.ProjectId==projectId);else if(projectCtx.AllowedProjectIds.Length>0)q=q.Where(x=>projectCtx.AllowedProjectIds.Contains(x.ProjectId));else q=q.Where(_=>false);
    if(releaseId.HasValue)q=q.Where(x=>x.ReleaseId==releaseId);if(buildId.HasValue)q=q.Where(x=>x.BuildId==buildId);if(moduleId.HasValue)q=q.Where(x=>x.Cases.Any(c=>c.TestCase.ModuleId==moduleId));
    if(!string.IsNullOrWhiteSpace(search))q=q.Where(x=>x.CycleName.Contains(search)||x.CycleCode.Contains(search));if(!string.IsNullOrWhiteSpace(status))q=q.Where(x=>x.Status==status);if(!string.IsNullOrWhiteSpace(cycleType))q=q.Where(x=>x.CycleType==cycleType);if(createdBy.HasValue)q=q.Where(x=>x.CreatedBy==createdBy);
    var total=await q.CountAsync(ct);var inProgress=await q.CountAsync(x=>x.Status=="InProgress",ct);var completed=await q.CountAsync(x=>x.Status=="Completed",ct);var cancelled=await q.CountAsync(x=>x.Status=="Cancelled",ct);var executedCases=await q.SelectMany(x=>x.Cases).CountAsync(x=>x.CurrentStatus!="NotRun",ct);var totalCases=await q.SelectMany(x=>x.Cases).CountAsync(ct);
    var p=Math.Max(1,page);var s=Math.Clamp(size,10,100);
    var items=await Project(q.OrderByDescending(x=>x.CreatedAt).Skip((p-1)*s).Take(s)).ToListAsync(ct);
    // Cycles aren't scoped to a single module — look up every distinct module touched by each cycle's
    // cases (for this page only) so the list can show/filter by them, same approach as Test Suites.
    var cycleIds=items.Select(x=>x.TestCycleId).ToList();
    var moduleLinks=await db.TestCycleCases.AsNoTracking().Where(x=>cycleIds.Contains(x.TestCycleId)).Select(x=>new{x.TestCycleId,x.TestCase.ModuleId}).Distinct().ToListAsync(ct);
    var moduleIds=moduleLinks.Select(x=>x.ModuleId).Distinct().ToList();
    var moduleInfo=await db.Modules.AsNoTracking().Where(m=>moduleIds.Contains(m.ModuleId)).ToDictionaryAsync(m=>m.ModuleId,m=>new SuiteModuleDto(m.ModuleId,m.ModuleCode,m.ModuleName),ct);
    var byCycle=moduleLinks.GroupBy(x=>x.TestCycleId).ToDictionary(g=>g.Key,g=>(IReadOnlyList<SuiteModuleDto>)g.Select(x=>moduleInfo.GetValueOrDefault(x.ModuleId)).Where(x=>x is not null).Select(x=>x!).OrderBy(x=>x.ModuleCode).ToList());
    var result=items.Select(x=>x with{Modules=byCycle.GetValueOrDefault(x.TestCycleId,Array.Empty<SuiteModuleDto>())}).ToList();
    return new(new(total,result),new(total,inProgress,completed,cancelled,executedCases,totalCases));
 }
 public async Task<IReadOnlyList<TestCycleOptionDto>>ListOptionsAsync(Guid?projectId,CancellationToken ct){var q=db.TestCycles.AsNoTracking().Where(x=>!x.IsDeleted);if(projectId.HasValue)q=q.Where(x=>x.ProjectId==projectId);else if(projectCtx.AllowedProjectIds.Length>0)q=q.Where(x=>projectCtx.AllowedProjectIds.Contains(x.ProjectId));else q=q.Where(_=>false);return await q.OrderByDescending(x=>x.CreatedAt).Select(x=>new TestCycleOptionDto(x.TestCycleId,x.ProjectId,x.ReleaseId,x.BuildId,x.CycleCode,x.CycleName,x.Status)).ToListAsync(ct);}
 public async Task<TestCycleDto?>GetAsync(Guid id,CancellationToken ct){var allowed=projectCtx.AllowedProjectIds;var q=db.TestCycles.AsNoTracking().Where(x=>x.TestCycleId==id&&!x.IsDeleted);if(allowed.Length>0)q=q.Where(x=>allowed.Contains(x.ProjectId));return await Project(q).SingleOrDefaultAsync(ct);}public async Task<TestCycle?>FindAsync(Guid id,CancellationToken ct){var allowed=projectCtx.AllowedProjectIds;var x=await db.TestCycles.SingleOrDefaultAsync(x=>x.TestCycleId==id&&!x.IsDeleted,ct);if(x is not null&&allowed.Length>0&&!allowed.Contains(x.ProjectId))return null;return x;}public Task<bool>CodeExistsAsync(Guid projectId,string code,Guid?excludeId,CancellationToken ct)=>db.TestCycles.AnyAsync(x=>x.ProjectId==projectId&&x.CycleCode==code&&(!excludeId.HasValue||x.TestCycleId!=excludeId),ct);
 public async Task<IReadOnlyList<string>>ListCodesAsync(Guid projectId,string prefix,CancellationToken ct)=>await db.TestCycles.AsNoTracking().Where(x=>x.ProjectId==projectId&&x.CycleCode.StartsWith(prefix)).Select(x=>x.CycleCode).ToListAsync(ct);
 public async Task ValidateReferencesAsync(SaveTestCycleRequest r,CancellationToken ct){if(!await db.Projects.AnyAsync(x=>x.ProjectId==r.ProjectId&&x.IsActive,ct))throw new ArgumentException("Project is not active.");var release=await db.Releases.AsNoTracking().SingleOrDefaultAsync(x=>x.ReleaseId==r.ReleaseId&&x.ProjectId==r.ProjectId,ct)??throw new EntityNotFoundException("Release not found in project.");if(release.Status is "Released" or "Cancelled")throw new ArgumentException("Cannot create a cycle for a closed release.");if(!await db.Builds.AnyAsync(x=>x.BuildId==r.BuildId&&x.ReleaseId==r.ReleaseId&&x.IsActive,ct))throw new ArgumentException("Build is not active or does not belong to selected release.");if(!await db.TestEnvironments.AnyAsync(x=>x.TestEnvironmentId==r.EnvironmentId&&x.ProjectId==r.ProjectId&&x.IsActive,ct))throw new ArgumentException("Environment is not active in selected project.");if(r.TestSuiteId.HasValue&&!await db.TestSuites.AnyAsync(x=>x.TestSuiteId==r.TestSuiteId&&x.ProjectId==r.ProjectId&&x.IsActive,ct))throw new ArgumentException("Test suite is not active in selected project.");}
 public Task AddAsync(TestCycle e,CancellationToken ct)=>db.TestCycles.AddAsync(e,ct).AsTask();public async Task PopulateAsync(Guid cycleId,Guid suiteId,bool requiredOnly,CancellationToken ct){var source=await db.TestSuiteCases.Where(x=>x.TestSuiteId==suiteId&&(!requiredOnly||x.IsRequired)).OrderBy(x=>x.SortOrder).Select(x=>new{x.TestCaseId,x.TestCase.RevisionNo,x.TestCase.Priority}).ToListAsync(ct);db.TestCycleCases.AddRange(source.Select((x,index)=>new TestCycleCase(cycleId,x.TestCaseId,x.RevisionNo,x.Priority,index+1)));}public Task DeleteAsync(TestCycle entity,CancellationToken ct){db.TestCycles.Update(entity);return Task.CompletedTask;}public Task SaveAsync(CancellationToken ct)=>db.SaveChangesAsync(ct);
}
