using Microsoft.EntityFrameworkCore;using ProMaxx2.QA.Application.Execution;using ProMaxx2.QA.Application.Projects;using ProMaxx2.QA.Domain.Execution;
namespace ProMaxx2.QA.Infrastructure.Persistence;
public sealed class TestCycleRepository(QaDbContext db):ITestCycleRepository
{
 public async Task<IReadOnlyList<EnvironmentDto>>EnvironmentsAsync(Guid?projectId,CancellationToken ct)=>await db.TestEnvironments.AsNoTracking().Where(x=>!projectId.HasValue||x.ProjectId==projectId).OrderBy(x=>x.EnvironmentName).Select(x=>new EnvironmentDto(x.TestEnvironmentId,x.ProjectId,x.EnvironmentName,x.BaseUrl,x.IsActive)).ToListAsync(ct);public Task AddEnvironmentAsync(TestEnvironment e,CancellationToken ct)=>db.TestEnvironments.AddAsync(e,ct).AsTask();
 private IQueryable<TestCycleDto>Project(IQueryable<TestCycle>q)=>q.Select(x=>new TestCycleDto(x.TestCycleId,x.ProjectId,x.ReleaseId,db.Releases.Where(r=>r.ReleaseId==x.ReleaseId).Select(r=>r.ReleaseCode).First(),x.BuildId,db.Builds.Where(b=>b.BuildId==x.BuildId).Select(b=>b.BuildNumber).First(),x.EnvironmentId,db.TestEnvironments.Where(e=>e.TestEnvironmentId==x.EnvironmentId).Select(e=>e.EnvironmentName).First(),x.TestSuiteId,db.TestSuites.Where(s=>s.TestSuiteId==x.TestSuiteId).Select(s=>s.SuiteName).FirstOrDefault(),x.CycleCode,x.CycleName,x.CycleType,x.StartDate,x.EndDate,x.OwnerUserId,x.Status,x.Notes,x.Cases.Count,x.Cases.Count(c=>c.CurrentStatus!="NotRun"),x.Cases.Count==0?0:Math.Round(x.Cases.Count(c=>c.CurrentStatus!="NotRun")*100m/x.Cases.Count,2)));
 public async Task<IReadOnlyList<TestCycleDto>>ListAsync(Guid?projectId,CancellationToken ct){var q=db.TestCycles.AsNoTracking();if(projectId.HasValue)q=q.Where(x=>x.ProjectId==projectId);return await Project(q.OrderByDescending(x=>x.CreatedAt)).ToListAsync(ct);}public Task<TestCycleDto?>GetAsync(Guid id,CancellationToken ct)=>Project(db.TestCycles.AsNoTracking().Where(x=>x.TestCycleId==id)).SingleOrDefaultAsync(ct);public Task<TestCycle?>FindAsync(Guid id,CancellationToken ct)=>db.TestCycles.SingleOrDefaultAsync(x=>x.TestCycleId==id,ct);public Task<bool>CodeExistsAsync(Guid projectId,string code,CancellationToken ct)=>db.TestCycles.AnyAsync(x=>x.ProjectId==projectId&&x.CycleCode==code,ct);
 public async Task ValidateReferencesAsync(SaveTestCycleRequest r,CancellationToken ct){if(!await db.Projects.AnyAsync(x=>x.ProjectId==r.ProjectId&&x.IsActive,ct))throw new ArgumentException("Project is not active.");var release=await db.Releases.AsNoTracking().SingleOrDefaultAsync(x=>x.ReleaseId==r.ReleaseId&&x.ProjectId==r.ProjectId,ct)??throw new EntityNotFoundException("Release not found in project.");if(release.Status is "Released" or "Cancelled")throw new ArgumentException("Cannot create a cycle for a closed release.");if(!await db.Builds.AnyAsync(x=>x.BuildId==r.BuildId&&x.ReleaseId==r.ReleaseId&&x.IsActive,ct))throw new ArgumentException("Build is not active or does not belong to selected release.");if(!await db.TestEnvironments.AnyAsync(x=>x.TestEnvironmentId==r.EnvironmentId&&x.ProjectId==r.ProjectId&&x.IsActive,ct))throw new ArgumentException("Environment is not active in selected project.");if(r.TestSuiteId.HasValue&&!await db.TestSuites.AnyAsync(x=>x.TestSuiteId==r.TestSuiteId&&x.ProjectId==r.ProjectId&&x.IsActive,ct))throw new ArgumentException("Test suite is not active in selected project.");}
 public Task AddAsync(TestCycle e,CancellationToken ct)=>db.TestCycles.AddAsync(e,ct).AsTask();public async Task PopulateAsync(Guid cycleId,Guid suiteId,bool requiredOnly,CancellationToken ct){var source=await db.TestSuiteCases.Where(x=>x.TestSuiteId==suiteId&&(!requiredOnly||x.IsRequired)).OrderBy(x=>x.SortOrder).Select(x=>new{x.TestCaseId,x.TestCase.RevisionNo,x.TestCase.Priority}).ToListAsync(ct);db.TestCycleCases.AddRange(source.Select((x,index)=>new TestCycleCase(cycleId,x.TestCaseId,x.RevisionNo,x.Priority,index+1)));}public Task SaveAsync(CancellationToken ct)=>db.SaveChangesAsync(ct);
}
