using Microsoft.EntityFrameworkCore;using ProMaxx2.QA.Application.TestManagement;using ProMaxx2.QA.Domain.TestManagement;using ProMaxx2.QA.Application.Common;
namespace ProMaxx2.QA.Infrastructure.Persistence;
public sealed class TestCaseRepository(QaDbContext db,ProjectAccessContext projectCtx):ITestCaseRepository
{
 public async Task<IReadOnlyList<TestCaseDto>>ListAsync(Guid?projectId,string?search,CancellationToken ct){var q=db.TestCases.AsNoTracking().Where(x=>!x.IsDeleted);if(projectId.HasValue)q=q.Where(x=>x.ProjectId==projectId);else if(projectCtx.AllowedProjectIds.Length>0)q=q.Where(x=>projectCtx.AllowedProjectIds.Contains(x.ProjectId));else q=q.Where(_=>false);if(!string.IsNullOrWhiteSpace(search))q=q.Where(x=>x.TestCaseCode.Contains(search)||x.Title.Contains(search));return await q.OrderBy(x=>x.TestCaseCode).Select(x=>new TestCaseDto(x.TestCaseId,x.ProjectId,x.ModuleId,x.TestCaseCode,x.Title,x.Objective,x.Preconditions,x.Priority,x.TestType,x.AutomationCandidate,x.Status,x.RevisionNo,x.OwnerUserId,x.Steps.Where(s=>s.RevisionNo==x.RevisionNo).OrderBy(s=>s.StepNo).Select(s=>new StepDto(s.StepNo,s.Action,s.TestDataText,s.ExpectedResult)).ToList())).ToListAsync(ct);}
 public async Task<TestCaseDto?>GetAsync(Guid id,CancellationToken ct)=>await db.TestCases.AsNoTracking().Where(x=>x.TestCaseId==id&&!x.IsDeleted).Select(x=>new TestCaseDto(x.TestCaseId,x.ProjectId,x.ModuleId,x.TestCaseCode,x.Title,x.Objective,x.Preconditions,x.Priority,x.TestType,x.AutomationCandidate,x.Status,x.RevisionNo,x.OwnerUserId,x.Steps.Where(s=>s.RevisionNo==x.RevisionNo).OrderBy(s=>s.StepNo).Select(s=>new StepDto(s.StepNo,s.Action,s.TestDataText,s.ExpectedResult)).ToList())).SingleOrDefaultAsync(ct);public Task<TestCase?>FindAsync(Guid id,CancellationToken ct)=>db.TestCases.Include(x=>x.Steps).SingleOrDefaultAsync(x=>x.TestCaseId==id&&!x.IsDeleted,ct);public Task<bool>CodeExistsAsync(Guid projectId,string code,CancellationToken ct)=>db.TestCases.AnyAsync(x=>x.ProjectId==projectId&&x.TestCaseCode==code,ct);public Task AddAsync(TestCase e,CancellationToken ct)=>db.TestCases.AddAsync(e,ct).AsTask();public void AddSteps(IEnumerable<TestStep>steps)=>db.TestSteps.AddRange(steps);
 public async Task LinkAsync(Guid reqId,Guid caseId,string?type,CancellationToken ct){if(!await db.Requirements.AnyAsync(x=>x.RequirementId==reqId&&!x.IsDeleted,ct)||!await db.TestCases.AnyAsync(x=>x.TestCaseId==caseId&&!x.IsDeleted,ct))throw new ProMaxx2.QA.Application.Projects.EntityNotFoundException("Requirement or test case not found.");if(!await db.RequirementTestCases.AnyAsync(x=>x.RequirementId==reqId&&x.TestCaseId==caseId,ct))await db.RequirementTestCases.AddAsync(new(reqId,caseId,type),ct);}public async Task UnlinkAsync(Guid reqId,Guid caseId,CancellationToken ct){var link=await db.RequirementTestCases.FindAsync([reqId,caseId],ct);if(link is not null)db.RequirementTestCases.Remove(link);}
 public async Task<IReadOnlyList<RtmRow>>RtmAsync(Guid releaseId,CancellationToken ct){var requirements=await db.Requirements.AsNoTracking().Where(x=>x.ReleaseId==releaseId&&x.IsInScope&&!x.IsDeleted).OrderBy(x=>x.RequirementCode).Select(x=>new{x.RequirementId,x.ModuleId,ModuleName=x.ModuleId.ToString(),x.RequirementCode,x.Title,x.Priority,x.Status}).ToListAsync(ct);var moduleIds=requirements.Select(x=>x.ModuleId).Distinct().ToArray();var moduleNames=await db.Modules.AsNoTracking().Where(x=>moduleIds.Contains(x.ModuleId)).ToDictionaryAsync(x=>x.ModuleId,x=>x.ModuleName,ct);var requirementIds=requirements.Select(x=>x.RequirementId).ToArray();var links=await db.RequirementTestCases.AsNoTracking().Where(x=>requirementIds.Contains(x.RequirementId)).Join(db.TestCases.AsNoTracking().Where(x=>!x.IsDeleted),l=>l.TestCaseId,t=>t.TestCaseId,(l,t)=>new{l.RequirementId,l.CoverageType,t.TestCaseId,t.TestCaseCode,t.Title,t.Priority,t.TestType,t.Status,t.RevisionNo}).ToListAsync(ct);return requirements.Select(r=>{var cases=links.Where(x=>x.RequirementId==r.RequirementId).Select(x=>new RtmLinkedTestCase(x.TestCaseId,x.TestCaseCode,x.Title,x.Priority,x.TestType,x.Status,x.RevisionNo,x.CoverageType)).ToList();var coverage=cases.Count==0?"Not Covered":cases.Any(x=>x.Status=="Ready")?"Covered":"Partial";return new RtmRow(r.RequirementId,r.ModuleId,moduleNames.GetValueOrDefault(r.ModuleId,"-"),r.RequirementCode,r.Title,r.Priority,cases.Count,coverage,r.Status,cases);}).ToList();}
 public async Task<IReadOnlyList<TestCaseRevisionDto>>RevisionsAsync(Guid id,CancellationToken ct){var revisions=await db.TestCaseRevisions.AsNoTracking().Where(x=>x.TestCaseId==id).OrderByDescending(x=>x.RevisionNo).Select(x=>new{x.RevisionNo,x.ChangeReason,x.ChangedBy,x.ChangedAt,ChangedByName=x.ChangedBy==null?null:db.Users.Where(u=>u.UserId==x.ChangedBy).Select(u=>u.DisplayName).FirstOrDefault()}).ToListAsync(ct);var steps=await db.TestSteps.AsNoTracking().Where(x=>x.TestCaseId==id).OrderBy(x=>x.StepNo).Select(x=>new{x.RevisionNo,Step=new StepDto(x.StepNo,x.Action,x.TestDataText,x.ExpectedResult)}).ToListAsync(ct);return revisions.Select(x=>new TestCaseRevisionDto(x.RevisionNo,x.ChangeReason,x.ChangedBy,x.ChangedByName,x.ChangedAt,steps.Where(s=>s.RevisionNo==x.RevisionNo).Select(s=>s.Step).ToList())).ToList();}
 public async Task<IReadOnlyList<TestCaseRequirementDto>>RequirementsAsync(Guid id,CancellationToken ct)=>await db.RequirementTestCases.AsNoTracking().Where(x=>x.TestCaseId==id).Join(db.Requirements.AsNoTracking().Where(x=>!x.IsDeleted),l=>l.RequirementId,r=>r.RequirementId,(l,r)=>new TestCaseRequirementDto(r.RequirementId,r.RequirementCode,r.Title,r.Status,l.CoverageType)).OrderBy(x=>x.RequirementCode).ToListAsync(ct);
 public Task SaveAsync(CancellationToken ct)=>db.SaveChangesAsync(ct);
}
