using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Text.Json;
using FlaUIElement = FlaUI.Core.AutomationElements.AutomationElement;
using FlaUI.UIA3;
using WinFormsTimer = System.Windows.Forms.Timer;

namespace ProMaxx2.Automation.AgentGui;

public sealed partial class CaptureForm : Form
{
    private readonly TextBox _url = new() { Text = "http://localhost:5038/api/v1" }, _user = new(), _password = new();
    private readonly ComboBox _project = new(), _module = new(), _testCase = new(), _app = new();
    private readonly ListBox _events = new() { Dock = DockStyle.Fill };
    private readonly Label _hover = new() { Dock = DockStyle.Fill, AutoSize = false, TextAlign = ContentAlignment.TopLeft, Text = "พร้อมจับการใช้งาน\r\n\r\n1. Login และเลือก Project / Module / Test Case\r\n2. เปิดหน้าต่าง ProMaxx2\r\n3. เลื่อนเมาส์ไปยังปุ่มหรือช่องกรอกข้อมูล\r\n4. คลิกเพื่อเพิ่ม Step Capture" };
    private readonly Button _login = new() { Text = "Login / Load" }, _preview = new() { Text = "Preview" }, _commit = new() { Text = "Commit Draft" }, _clear = new() { Text = "Clear" }, _edit = new() { Text = "Edit Selected" };
    private readonly WinFormsTimer _timer = new() { Interval = 120 }; private readonly UIA3Automation _automation = new();
    private readonly List<CapturedItem> _items = []; private FlaUIElement? _last; private string? _lastValue; private bool _wasDown; private string? _token;
    [DllImport("user32.dll")] static extern bool GetCursorPos(out POINT p); [DllImport("user32.dll")] static extern short GetAsyncKeyState(int key); [StructLayout(LayoutKind.Sequential)] struct POINT { public int X; public int Y; }
    record CapturedItem(int StepNo,string EventType,string Action,string? TestData,string ExpectedResult,string ScreenCode,string ObjectCode,string ObjectName,string ControlType,string? AutomationId,string SelectorJson,bool Sensitive=false);
    public CaptureForm(string? hubUrl = null, string? username = null, string? password = null)
    {
        Text = "ProMaxx2 Capture Companion"; Width = 1100; Height = 720; MinimumSize = new Size(900, 600); StartPosition = FormStartPosition.CenterScreen; BackColor = Color.FromArgb(246, 248, 251); Font = new Font("Segoe UI", 10F); _url.Text = string.IsNullOrWhiteSpace(hubUrl) ? _url.Text : hubUrl; _user.Text = username ?? string.Empty; _password.Text = password ?? string.Empty; _password.UseSystemPasswordChar = true; _app.Items.AddRange(["pos", "app"]); _app.SelectedIndex = 0;
        foreach (var c in new[] { _project, _module, _testCase, _app }) c.DropDownStyle = ComboBoxStyle.DropDownList;
        foreach (var c in new Control[] { _url, _user, _password }) c.Margin = new Padding(4, 5, 8, 5);
        foreach (var c in new ComboBox[] { _project, _module, _testCase, _app }) { c.Margin = new Padding(4, 5, 8, 5); c.IntegralHeight = false; c.DropDownHeight = 260; }
        _hover.BackColor = Color.White; _hover.BorderStyle = BorderStyle.FixedSingle; _hover.Padding = new Padding(18); _hover.Font = new Font("Segoe UI", 11F);
        _events.BackColor = Color.White; _events.BorderStyle = BorderStyle.FixedSingle; _events.HorizontalScrollbar = true;
        StyleButton(_login, Color.FromArgb(37, 99, 235), Color.White); StyleButton(_preview, Color.FromArgb(226, 232, 240), Color.FromArgb(30, 41, 59)); StyleButton(_commit, Color.FromArgb(22, 163, 74), Color.White); StyleButton(_edit, Color.FromArgb(226, 232, 240), Color.FromArgb(30, 41, 59)); StyleButton(_clear, Color.FromArgb(254, 226, 226), Color.FromArgb(153, 27, 27));
        _project.FormattingEnabled = _module.FormattingEnabled = _testCase.FormattingEnabled = true;
        _project.Format += (_, e) => e.Value = FormatItem(e.ListItem, "projectCode", "projectName");
        _module.Format += (_, e) => e.Value = FormatItem(e.ListItem, "moduleCode", "moduleName");
        _testCase.Format += (_, e) => e.Value = FormatItem(e.ListItem, "testCaseCode", "title");
        var top = new TableLayoutPanel { Dock = DockStyle.Top, Height = 166, ColumnCount = 6, RowCount = 3, Padding = new Padding(18, 12, 18, 10), BackColor = Color.White }; for (var i=0;i<6;i++) top.ColumnStyles.Add(i%2==0?new ColumnStyle(SizeType.Absolute,90):new ColumnStyle(SizeType.Percent,25));
        Add(top,"Hub URL",_url,0,0,5); Add(top,"User",_user,0,1,1); Add(top,"Password",_password,2,1,1); Add(top,"Application",_app,0,2,1); Add(top,"Project",_project,2,2,1); top.Controls.Add(_login,4,1);
        var scope = new FlowLayoutPanel { Dock = DockStyle.Top, Height = 58, Padding = new Padding(18, 8, 18, 8), BackColor = Color.FromArgb(241, 245, 249), WrapContents = false }; scope.Controls.Add(new Label{Text="Module",AutoSize=true,Padding=new Padding(0,8,5,0)}); scope.Controls.Add(_module); scope.Controls.Add(new Label{Text="Test Case",AutoSize=true,Padding=new Padding(14,8,5,0)}); scope.Controls.Add(_testCase); _preview.Enabled=false; _commit.Enabled=false; scope.Controls.Add(_edit); scope.Controls.Add(_clear); scope.Controls.Add(_preview); scope.Controls.Add(_commit);
        var split = new SplitContainer { Dock = DockStyle.Fill, Padding = new Padding(18, 14, 18, 18), BackColor = Color.FromArgb(246, 248, 251) }; split.Panel1.Padding = new Padding(0, 28, 8, 0); split.Panel2.Padding = new Padding(8, 28, 0, 0); split.Panel1.Controls.Add(_hover); split.Panel2.Controls.Add(_events); var leftTitle = new Label { Text = "UIA Control Detail", Dock = DockStyle.Top, Height = 28, Font = new Font("Segoe UI", 10F, FontStyle.Bold), ForeColor = Color.FromArgb(30, 41, 59) }; var rightTitle = new Label { Text = "Captured Steps", Dock = DockStyle.Top, Height = 28, Font = new Font("Segoe UI", 10F, FontStyle.Bold), ForeColor = Color.FromArgb(30, 41, 59) }; split.Panel1.Controls.Add(leftTitle); split.Panel2.Controls.Add(rightTitle); Controls.Add(split); Controls.Add(scope); Controls.Add(top); Shown += (_, _) => { split.Panel1MinSize = 180; split.Panel2MinSize = 180; split.SplitterDistance = Math.Max(180, Math.Min(split.ClientSize.Width / 2, split.ClientSize.Width - 180)); };
        _login.Click += async (_,_) => await LoadScopeAsync(); _project.SelectedIndexChanged += async (_,_) => await LoadProjectDataAsync(); _preview.Click += async (_,_) => await SendAsync(false); _commit.Click += async (_,_) => await SendAsync(true); _clear.Click += (_,_) => { _items.Clear(); _events.Items.Clear(); }; _edit.Click += (_,_) => EditSelected(); _timer.Tick += (_,_) => PollTarget(); _timer.Tick += (_,_) => PollText(); _timer.Start(); FormClosed += (_,_) => { _timer.Stop(); _automation.Dispose(); };
    }
    static void StyleButton(Button button, Color backColor, Color foreColor){button.AutoSize = true; button.FlatStyle = FlatStyle.Flat; button.FlatAppearance.BorderSize = 0; button.BackColor = backColor; button.ForeColor = foreColor; button.Font = new Font("Segoe UI", 9.5F, FontStyle.Bold); button.Padding = new Padding(10, 4, 10, 4); button.Margin = new Padding(5, 5, 5, 5);}
    static void Add(TableLayoutPanel t,string label,Control c,int x,int y,int span){t.Controls.Add(new Label{Text=label,AutoSize=true,Padding=new Padding(0,7,4,0)},x,y);t.Controls.Add(c,x+1,y);t.SetColumnSpan(c,span);c.Dock=DockStyle.Fill;}
    async Task LoadScopeAsync(){try{using var h=Client();var r=await h.PostAsJsonAsync($"{_url.Text.TrimEnd('/')}/auth/login",new{username=_user.Text,password=_password.Text});r.EnsureSuccessStatusCode();var j=await r.Content.ReadFromJsonAsync<JsonElement>();_token=j.GetProperty("accessToken").GetString();await LoadAsync($"{_url.Text.TrimEnd('/')}/projects",_project);_preview.Enabled=_commit.Enabled=true;MessageBox.Show("Login สำเร็จ");}catch(Exception ex){MessageBox.Show($"Login/Load ไม่สำเร็จ: {ex.Message}");}}
    async Task LoadProjectDataAsync(){if(_project.SelectedItem is not JsonElement p)return;var id=p.GetProperty("projectId").GetGuid();await LoadAsync($"{_url.Text.TrimEnd('/')}/projects/{id}/modules",_module);await LoadAsync($"{_url.Text.TrimEnd('/')}/automation/capture/test-cases?projectId={id}",_testCase);}
    static string FormatItem(object? item, string codeProperty, string nameProperty){if(item is not JsonElement j)return item?.ToString()??string.Empty;var code=j.TryGetProperty(codeProperty,out var c)?c.GetString():null;var name=j.TryGetProperty(nameProperty,out var n)?n.GetString():null;return string.IsNullOrWhiteSpace(code)?name??string.Empty:$"{code} - {name}";}
    async Task LoadAsync(string url,ComboBox box){using var h=Client();var a=await h.GetFromJsonAsync<JsonElement[]>(url)??[];box.Items.Clear();foreach(var x in a)box.Items.Add(x);if(box.Items.Count>0)box.SelectedIndex=0;}
    HttpClient Client(){var h=new HttpClient(new HubRecoveryHandler()){Timeout=TimeSpan.FromSeconds(20)};if(!string.IsNullOrWhiteSpace(_token)){if(TokenExpired(_token)){_token=null;throw new InvalidOperationException("QA Hub session expired. Please login again.");}h.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",_token);}return h;}
    void PollTarget(){try{if(IsPromaxxForeground())Poll();}catch{} }
    static bool IsPromaxxForeground(){try{var handle=GetForegroundWindow();if(handle==IntPtr.Zero)return false;GetWindowThreadProcessId(handle,out var pid);var path=Process.GetProcessById((int)pid).MainModule?.FileName??"";return path.EndsWith("Promaxxs.App.exe",StringComparison.OrdinalIgnoreCase)||path.EndsWith("PromaxxsPos.exe",StringComparison.OrdinalIgnoreCase);}catch{return false;}}
    [DllImport("user32.dll")] static extern IntPtr GetForegroundWindow(); [DllImport("user32.dll")] static extern uint GetWindowThreadProcessId(IntPtr hWnd,out uint processId);
    static bool TokenExpired(string token){try{var part=token.Split('.')[1].Replace('-','+').Replace('_','/');part+=new string('=',(4-part.Length%4)%4);using var doc=JsonDocument.Parse(Convert.FromBase64String(part));return doc.RootElement.GetProperty("exp").GetInt64()<=DateTimeOffset.UtcNow.ToUnixTimeSeconds()+30;}catch{return false;}}
    void PollText(){if(_last is null||!_last.ControlType.ToString().Equals("Edit",StringComparison.OrdinalIgnoreCase))return;try{var value=_last.Patterns.Value.Pattern.Value;if(value==_lastValue)return;_lastValue=value;var sensitive=(_last.Name+" "+_last.AutomationId).Contains("password",StringComparison.OrdinalIgnoreCase)||_last.Properties.IsPassword.ValueOrDefault;var n=_items.Count+1;_items.Add(new(n,"TextInput",$"Enter text in {_last.Name}",sensitive?null:value,"ผู้ใช้ตรวจสอบผลลัพธ์หลังดำเนินการ","",$"OBJ_{n:000}",_last.Name,"Edit",_last.AutomationId,string.IsNullOrWhiteSpace(_last.AutomationId)?"{}":JsonSerializer.Serialize(new{automationId=_last.AutomationId}),sensitive));_events.Items.Add($"{n}. TEXT INPUT | {(sensitive?"[MASKED]":value)} | {_last.AutomationId ?? "Missing AutomationId"}");}catch{}}
    void Poll(){if(!GetCursorPos(out var p))return;FlaUIElement? e=null;try{e=_automation.FromPoint(new System.Drawing.Point(p.X,p.Y));}catch{}if(e is not null&&!ReferenceEquals(e,_last)){_last=e;_hover.Text=$"Name: {e.Name}\r\nAutomationId: {e.AutomationId}\r\nControlType: {e.ControlType}\r\nClass: {SafeClassName(e)}";}var d=(GetAsyncKeyState(1)&0x8000)!=0;if(d&&!_wasDown&&e is not null){var n=_items.Count+1;_items.Add(new(n,"Click",$"Click {e.Name}",null,"ผู้ใช้ตรวจสอบผลลัพธ์หลังดำเนินการ","",$"OBJ_{n:000}",e.Name,e.ControlType.ToString(),e.AutomationId,string.IsNullOrWhiteSpace(e.AutomationId)?"{}":JsonSerializer.Serialize(new{automationId=e.AutomationId})));_events.Items.Add($"{n}. CLICK | {e.AutomationId ?? "Missing AutomationId"} | {e.Name}");}_wasDown=d;}
    static string SafeClassName(FlaUIElement element){try{return element.ClassName;}catch{return "(ไม่รองรับโดย Control นี้)";}}
    async Task SendAsync(bool commit){try{if(_project.SelectedItem is not JsonElement p||_module.SelectedItem is not JsonElement m||_testCase.SelectedItem is not JsonElement t)throw new InvalidOperationException("เลือก Project, Module และ Test Case ก่อน");var req=new{projectId=p.GetProperty("projectId").GetGuid(),moduleId=m.GetProperty("moduleId").GetGuid(),testCaseId=t.GetProperty("testCaseId").GetGuid(),applicationCode=_app.Text,sourceMachine=Environment.MachineName,applicationVersion=Application.ProductVersion,items=_items};using var h=Client();var r=await h.PostAsJsonAsync($"{_url.Text.TrimEnd('/')}/automation/capture/sessions",req);r.EnsureSuccessStatusCode();var s=await r.Content.ReadFromJsonAsync<JsonElement>();if(commit){var id=s.GetProperty("sessionId").GetGuid();var c=await h.PostAsync($"{_url.Text.TrimEnd('/')}/automation/capture/sessions/{id}/commit",null);c.EnsureSuccessStatusCode();MessageBox.Show("Commit Draft สำเร็จ");}else MessageBox.Show("Preview สำเร็จ");}catch(Exception ex){MessageBox.Show($"ส่ง Capture ไม่สำเร็จ: {ex.Message}");}}
}
