<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Promaxx2.Automation.Core\Promaxx2.Automation.Core.csproj" />
    <ProjectReference Include="..\Promaxx2.Automation.Hub\Promaxx2.Automation.Hub.csproj" />
    <ProjectReference Include="..\Promaxx2.Automation.Data\Promaxx2.Automation.Data.csproj" />
    <ProjectReference Include="..\Promaxx2.Automation.Pages.App\Promaxx2.Automation.Pages.App.csproj" />
    <ProjectReference Include="..\Promaxx2.Automation.Pages.Pos\Promaxx2.Automation.Pages.Pos.csproj" />
    <ProjectReference Include="..\..\tests\Promaxx2.Automation.Tests\Promaxx2.Automation.Tests.csproj" />
  </ItemGroup>
</Project>
