namespace ProMaxx2.QA.Domain.Requirements;
public sealed class Requirement
{
 private Requirement(){}
 public Requirement(Guid projectId,Guid? releaseId,Guid moduleId,string code,string title,string? description,string? acceptanceCriteria,string priority,string? riskLevel,string? source,Guid? ownerId,bool inScope,Guid? createdBy){Validate(title,priority);RequirementId=Guid.NewGuid();ProjectId=projectId;ReleaseId=releaseId;ModuleId=moduleId;RequirementCode=code.Trim().ToUpperInvariant();Title=title.Trim();Description=description?.Trim();AcceptanceCriteria=acceptanceCriteria?.Trim();Priority=priority.ToUpperInvariant();RiskLevel=riskLevel?.Trim();Source=source?.Trim();OwnerUserId=ownerId;IsInScope=inScope;CreatedBy=createdBy;Status="Draft";RevisionNo=1;CreatedAt=DateTime.UtcNow;Revisions.Add(new RequirementRevision(RequirementId,1,Title,Description,AcceptanceCriteria,createdBy,"Initial revision"));}
 public Guid RequirementId{get;private set;}public Guid ProjectId{get;private set;}public Guid? ReleaseId{get;private set;}public Guid ModuleId{get;private set;}public string RequirementCode{get;private set;}=string.Empty;public string Title{get;private set;}=string.Empty;public string? Description{get;private set;}public string? AcceptanceCriteria{get;private set;}public string Priority{get;private set;}="P2";public string? RiskLevel{get;private set;}public string? Source{get;private set;}public Guid? OwnerUserId{get;private set;}public string Status{get;private set;}="Draft";public int RevisionNo{get;private set;}public bool IsInScope{get;private set;}public bool IsDeleted{get;private set;}public DateTime CreatedAt{get;private set;}public Guid? CreatedBy{get;private set;}public DateTime? UpdatedAt{get;private set;}public Guid? UpdatedBy{get;private set;}public ICollection<RequirementRevision>Revisions{get;private set;}=[];
 public void Update(Guid? releaseId,Guid moduleId,string title,string? description,string? acceptanceCriteria,string priority,string? risk,string? source,Guid? owner,bool inScope,Guid? userId){Validate(title,priority);ReleaseId=releaseId;ModuleId=moduleId;Title=title.Trim();Description=description?.Trim();AcceptanceCriteria=acceptanceCriteria?.Trim();Priority=priority.ToUpperInvariant();RiskLevel=risk?.Trim();Source=source?.Trim();OwnerUserId=owner;IsInScope=inScope;UpdatedAt=DateTime.UtcNow;UpdatedBy=userId;}
 public void CreateRevision(string title,string? description,string? acceptanceCriteria,string? reason,Guid? userId){if(string.IsNullOrWhiteSpace(reason))throw new ArgumentException("Change reason is required.");if(string.IsNullOrWhiteSpace(title))throw new ArgumentException("Title is required.");RevisionNo++;Title=title.Trim();Description=description?.Trim();AcceptanceCriteria=acceptanceCriteria?.Trim();Revisions.Add(new RequirementRevision(RequirementId,RevisionNo,Title,Description,AcceptanceCriteria,userId,reason.Trim()));UpdatedAt=DateTime.UtcNow;UpdatedBy=userId;}
 public void ChangeStatus(string status,Guid? userId){string[]allowed=["Draft","Review","Approved","Implemented","Cancelled"];Status=allowed.SingleOrDefault(x=>x.Equals(status,StringComparison.OrdinalIgnoreCase))??throw new ArgumentException("Invalid requirement status.");UpdatedAt=DateTime.UtcNow;UpdatedBy=userId;}public void SoftDelete(Guid? userId){IsDeleted=true;UpdatedAt=DateTime.UtcNow;UpdatedBy=userId;}
 private static void Validate(string title,string priority){if(string.IsNullOrWhiteSpace(title))throw new ArgumentException("Title is required.");if(!new[]{"P0","P1","P2","P3"}.Contains(priority.ToUpperInvariant()))throw new ArgumentException("Priority must be P0-P3.");}
}
public sealed class RequirementRevision{private RequirementRevision(){}public RequirementRevision(Guid requirementId,int number,string title,string? description,string? criteria,Guid? changedBy,string? reason){RequirementId=requirementId;RevisionNo=number;Title=title;Description=description;AcceptanceCriteria=criteria;ChangedBy=changedBy;ChangeReason=reason;ChangedAt=DateTime.UtcNow;}public Guid RequirementRevisionId{get;private set;}public Guid RequirementId{get;private set;}public int RevisionNo{get;private set;}public string Title{get;private set;}=string.Empty;public string?Description{get;private set;}public string?AcceptanceCriteria{get;private set;}public Guid?ChangedBy{get;private set;}public DateTime ChangedAt{get;private set;}public string?ChangeReason{get;private set;}public Requirement Requirement{get;private set;}=null!;}
