namespace ProMaxx2.QA.Domain.Releases;

public static class ReleaseStatuses { public static readonly string[] All=["Draft","Testing","Ready","Released","Cancelled"]; }
public static class BuildStatuses { public static readonly string[] All=["Ready","Testing","Passed","Failed","Blocked"]; }
public sealed class Release
{
    private Release(){}
    public Release(Guid projectId,string code,string version,string? type,string? scope,DateOnly? plannedDate,Guid? ownerId,Guid? createdBy){if(string.IsNullOrWhiteSpace(code)||string.IsNullOrWhiteSpace(version))throw new ArgumentException("Release code and version are required.");ReleaseId=Guid.NewGuid();ProjectId=projectId;ReleaseCode=code.Trim().ToUpperInvariant();Version=version.Trim();ReleaseType=type?.Trim();Scope=scope?.Trim();PlannedReleaseDate=plannedDate;ReleaseOwnerUserId=ownerId;CreatedBy=createdBy;Status="Draft";CreatedAt=DateTime.UtcNow;}
    public Guid ReleaseId{get;private set;}public Guid ProjectId{get;private set;}public string ReleaseCode{get;private set;}=string.Empty;public string Version{get;private set;}=string.Empty;public string? ReleaseType{get;private set;}public string? Scope{get;private set;}public DateOnly? PlannedReleaseDate{get;private set;}public DateOnly? ActualReleaseDate{get;private set;}public string Status{get;private set;}="Draft";public Guid? ReleaseOwnerUserId{get;private set;}public DateTime CreatedAt{get;private set;}public Guid? CreatedBy{get;private set;}public DateTime? UpdatedAt{get;private set;}public Guid? UpdatedBy{get;private set;}public ICollection<Build> Builds{get;private set;}=[];
    public void Update(string version,string? type,string? scope,DateOnly? plannedDate,Guid? ownerId,Guid? userId){if(string.IsNullOrWhiteSpace(version))throw new ArgumentException("Version is required.");Version=version.Trim();ReleaseType=type?.Trim();Scope=scope?.Trim();PlannedReleaseDate=plannedDate;ReleaseOwnerUserId=ownerId;UpdatedBy=userId;UpdatedAt=DateTime.UtcNow;}
    public void ChangeStatus(string status,Guid? userId){if(!ReleaseStatuses.All.Contains(status,StringComparer.OrdinalIgnoreCase))throw new ArgumentException("Invalid release status.");Status=ReleaseStatuses.All.Single(x=>x.Equals(status,StringComparison.OrdinalIgnoreCase));ActualReleaseDate=Status=="Released"?DateOnly.FromDateTime(DateTime.UtcNow):ActualReleaseDate;UpdatedBy=userId;UpdatedAt=DateTime.UtcNow;}
}
public sealed class Build
{
    private Build(){}
    public Build(Guid releaseId,string number,string? appVersion,string? packageVersion,string? commitReference,DateTime? buildDate,string? changeNotes,string? knownIssues,Guid? createdBy){if(string.IsNullOrWhiteSpace(number))throw new ArgumentException("Build number is required.");BuildId=Guid.NewGuid();ReleaseId=releaseId;BuildNumber=number.Trim();ApplicationVersion=appVersion?.Trim();PackageVersion=packageVersion?.Trim();CommitReference=commitReference?.Trim();BuildDate=buildDate;ChangeNotes=changeNotes?.Trim();KnownIssues=knownIssues?.Trim();CreatedBy=createdBy;Status="Ready";IsActive=true;CreatedAt=DateTime.UtcNow;}
    public Guid BuildId{get;private set;}public Guid ReleaseId{get;private set;}public string BuildNumber{get;private set;}=string.Empty;public string? ApplicationVersion{get;private set;}public string? PackageVersion{get;private set;}public string? CommitReference{get;private set;}public DateTime? BuildDate{get;private set;}public string? ChangeNotes{get;private set;}public string? KnownIssues{get;private set;}public bool IsReleaseCandidate{get;private set;}public bool IsActive{get;private set;}public string Status{get;private set;}="Ready";public DateTime CreatedAt{get;private set;}public Guid? CreatedBy{get;private set;}public Release Release{get;private set;}=null!;
    public void Update(string? appVersion,string? packageVersion,string? commitReference,DateTime? buildDate,string? changeNotes,string? knownIssues){ApplicationVersion=appVersion?.Trim();PackageVersion=packageVersion?.Trim();CommitReference=commitReference?.Trim();BuildDate=buildDate;ChangeNotes=changeNotes?.Trim();KnownIssues=knownIssues?.Trim();}
    public void MarkReleaseCandidate()=>IsReleaseCandidate=true;
    public void ChangeStatus(string status){Status=BuildStatuses.All.SingleOrDefault(x=>x.Equals(status,StringComparison.OrdinalIgnoreCase))??throw new ArgumentException("Invalid build status.");}
    public void Deactivate(){IsActive=false;Status="Inactive";}
}
