-- ProMaxx2 Capture Companion: read-only duplicate audit
-- Run with a Firebird account that has SELECT access only.
-- This script intentionally contains no INSERT/UPDATE/DELETE/DDL.

-- Summary: duplicate non-empty AutomationId within the matching scope.
SELECT
    PROJECTID,
    APPLICATIONCODE,
    AUTOMATIONID,
    COUNT(*) AS DUPLICATECOUNT
FROM AUTOMATIONOBJECTS
WHERE AUTOMATIONID IS NOT NULL
  AND TRIM(AUTOMATIONID) <> ''
  AND ISACTIVE = 1
GROUP BY PROJECTID, APPLICATIONCODE, AUTOMATIONID
HAVING COUNT(*) > 1
ORDER BY PROJECTID, APPLICATIONCODE, AUTOMATIONID;

-- Detail: rows belonging to duplicate groups.
SELECT
    O.AUTOMATIONOBJECTID,
    O.PROJECTID,
    O.MODULEID,
    O.APPLICATIONCODE,
    O.SCREENCODE,
    O.OBJECTCODE,
    O.OBJECTNAME,
    O.CONTROLTYPE,
    O.AUTOMATIONID,
    O.ISACTIVE
FROM AUTOMATIONOBJECTS O
JOIN (
    SELECT PROJECTID, APPLICATIONCODE, AUTOMATIONID
    FROM AUTOMATIONOBJECTS
    WHERE AUTOMATIONID IS NOT NULL
      AND TRIM(AUTOMATIONID) <> ''
      AND ISACTIVE = 1
    GROUP BY PROJECTID, APPLICATIONCODE, AUTOMATIONID
    HAVING COUNT(*) > 1
) D ON D.PROJECTID = O.PROJECTID
   AND D.APPLICATIONCODE = O.APPLICATIONCODE
   AND D.AUTOMATIONID = O.AUTOMATIONID
WHERE O.ISACTIVE = 1
ORDER BY O.PROJECTID, O.APPLICATIONCODE, O.AUTOMATIONID, O.AUTOMATIONOBJECTID;
