using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using ProMaxx2.QA.Application.Identity;using ProMaxx2.QA.Application.Projects;
namespace ProMaxx2.QA.Api.Controllers;
[ApiController,Route("api/v1/admin")]
public sealed class AdministrationController(AdministrationService service):ControllerBase
{
 [HttpGet("users"),Authorize(Policy="AdminUser")]public Task<IReadOnlyList<UserDto>>Users(CancellationToken ct)=>service.UsersAsync(ct);[HttpPost("users"),Authorize(Policy="AdminUser")]public async Task<ActionResult<UserDto>>CreateUser(CreateUserRequest r,CancellationToken ct){try{return Ok(await service.CreateUserAsync(r,ct));}catch(DuplicateCodeException ex){return Conflict(P("Username ซ้ำ",ex.Message,409));}catch(ArgumentException ex){return BadRequest(P("ข้อมูลไม่ถูกต้อง",ex.Message,400));}}[HttpPut("users/{id:guid}"),Authorize(Policy="AdminUser")]public async Task<ActionResult<UserDto>>UpdateUser(Guid id,UpdateUserRequest r,CancellationToken ct){try{return Ok(await service.UpdateUserAsync(id,r,ct));}catch(EntityNotFoundException){return NotFound();}} [HttpPost("users/{id:guid}/roles"),Authorize(Policy="AdminUser")]public async Task<IActionResult>Roles(Guid id,AssignRolesRequest r,CancellationToken ct){try{await service.AssignRolesAsync(id,r,ct);return NoContent();}catch(EntityNotFoundException){return NotFound();}}[HttpPost("users/{id:guid}/projects"),Authorize(Policy="AdminUser")]public async Task<IActionResult>Projects(Guid id,AssignProjectsRequest r,CancellationToken ct){try{await service.AssignProjectsAsync(id,r,ct);return NoContent();}catch(EntityNotFoundException){return NotFound();}}[HttpPost("users/{id:guid}/reset-password"),Authorize(Policy="AdminUser")]public async Task<IActionResult>Reset(Guid id,ResetPasswordRequest r,CancellationToken ct){try{await service.ResetPasswordAsync(id,r.NewPassword,ct);return NoContent();}catch(EntityNotFoundException){return NotFound();}catch(ArgumentException ex){return BadRequest(P("รหัสผ่านไม่ถูกต้อง",ex.Message,400));}}
 [HttpGet("roles"),Authorize(Policy="AdminUser")]public Task<IReadOnlyList<RoleDto>>ListRoles(CancellationToken ct)=>service.RolesAsync(ct);[HttpPost("roles"),Authorize(Policy="AdminUser")]public async Task<ActionResult<RoleDto>>CreateRole(CreateRoleRequest r,CancellationToken ct){try{return Ok(await service.CreateRoleAsync(r,ct));}catch(DuplicateCodeException ex){return Conflict(P("Role code ซ้ำ",ex.Message,409));}}[HttpPut("roles/{id:guid}"),Authorize(Policy="AdminUser")]public async Task<ActionResult<RoleDto>>UpdateRole(Guid id,UpdateRoleRequest r,CancellationToken ct){try{return Ok(await service.UpdateRoleAsync(id,r,ct));}catch(EntityNotFoundException){return NotFound();}}
 [HttpGet("permissions"),Authorize(Policy="AdminUser")]public Task<IReadOnlyList<PermissionDto>>Permissions(CancellationToken ct)=>service.PermissionsAsync(ct);[HttpPost("roles/{id:guid}/permissions"),Authorize(Policy="AdminUser")]public async Task<IActionResult>Permissions(Guid id,AssignPermissionsRequest r,CancellationToken ct){try{await service.AssignPermissionsAsync(id,r,ct);return NoContent();}catch(EntityNotFoundException){return NotFound();}}
 private static ProblemDetails P(string title,string detail,int status)=>new(){Title=title,Detail=detail,Status=status};
}
