using System.Security.Claims;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.AspNetCore.StaticFiles;using ProMaxx2.QA.Api.Services;using ProMaxx2.QA.Application.Execution;using ProMaxx2.QA.Application.Projects;
namespace ProMaxx2.QA.Api.Controllers;
[ApiController,Route("api/v1/automation"),Authorize(Policy="ExecutionRun"),RequireProjectAccess]
public sealed class AutomationController(AutomationRunService service,IWebHostEnvironment environment):ControllerBase
{
 [HttpGet("runs")]public Task<IReadOnlyList<AutomationRunDto>>List([FromQuery]Guid projectId,[FromQuery]int take=20,CancellationToken ct=default)=>service.ListAsync(projectId,take,ct);
 [HttpPost("runs")]public async Task<ActionResult<AutomationRunDto>>Publish([FromQuery]Guid projectId,PublishAutomationRunRequest request,CancellationToken ct){if(projectId!=request.ProjectId)return BadRequest(Problem("Project ไม่ตรงกัน","projectId ใน query และ payload ต้องเป็นค่าเดียวกัน",400));try{return Ok(await service.PublishAsync(request,UserId(),ct));}catch(ArgumentException ex){return BadRequest(Problem("ผล Automation ไม่ถูกต้อง",ex.Message,400));}}
 [HttpGet("quality-gates")]public Task<IReadOnlyList<AutomationQualityGateDto>>ListGates([FromQuery]Guid projectId,[FromQuery]Guid?buildId,[FromQuery]int take=20,CancellationToken ct=default)=>service.ListGatesAsync(projectId,buildId,take,ct);
 [HttpGet("quality-gates/builds/{buildId:guid}")]public Task<AutomationBuildGateStatusDto>BuildGateStatus(Guid buildId,[FromQuery]Guid projectId,CancellationToken ct)=>service.GetBuildGateStatusAsync(projectId,buildId,ct);
 [HttpPost("quality-gates")]public async Task<ActionResult<AutomationQualityGateDto>>PublishGate([FromQuery]Guid projectId,PublishAutomationQualityGateRequest request,CancellationToken ct){if(projectId!=request.ProjectId)return BadRequest(Problem("Project ไม่ตรงกัน","projectId ใน query และ payload ต้องเป็นค่าเดียวกัน",400));try{return Ok(await service.PublishGateAsync(request,ct));}catch(ArgumentException ex){return BadRequest(Problem("ผล Quality Gate ไม่ถูกต้อง",ex.Message,400));}}
 [HttpGet("queue")]public Task<IReadOnlyList<AutomationQueueJobDto>>ListQueue([FromQuery]Guid projectId,[FromQuery]Guid?buildId,[FromQuery]int take=50,CancellationToken ct=default)=>service.ListQueueJobsAsync(projectId,buildId,take,ct);
 [HttpPost("queue")]public async Task<ActionResult<AutomationQueueJobDto>>CreateQueue([FromQuery]Guid projectId,CreateAutomationQueueJobRequest request,CancellationToken ct){if(projectId!=request.ProjectId)return BadRequest(Problem("Project ไม่ตรงกัน","projectId ใน query และ payload ต้องเป็นค่าเดียวกัน",400));try{return Ok(await service.CreateQueueJobAsync(request,UserId(),ct));}catch(ArgumentException ex){return BadRequest(Problem("สร้าง Automation Queue ไม่สำเร็จ",ex.Message,400));}}
 [HttpPost("queue/claim")]public async Task<ActionResult<AutomationQueueJobDto?>>ClaimQueue([FromQuery]Guid projectId,ClaimAutomationQueueJobRequest request,CancellationToken ct){try{var job=await service.ClaimQueueJobAsync(projectId,request,ct);return job is null?NoContent():Ok(job);}catch(ArgumentException ex){return BadRequest(Problem("รับงาน Automation ไม่สำเร็จ",ex.Message,400));}}
 [HttpPost("queue/{jobId:guid}/status")]public async Task<ActionResult<AutomationQueueJobDto>>UpdateQueue(Guid jobId,[FromQuery]Guid projectId,UpdateAutomationQueueJobRequest request,CancellationToken ct){try{return Ok(await service.UpdateQueueJobAsync(jobId,projectId,request,ct));}catch(EntityNotFoundException){return NotFound();}catch(InvalidOperationException ex){return Conflict(Problem("สถานะ Automation Queue ไม่ถูกต้อง",ex.Message,409));}}
 [HttpDelete("queue/{jobId:guid}")]public async Task<IActionResult>CancelQueue(Guid jobId,[FromQuery]Guid projectId,CancellationToken ct){try{await service.CancelQueueJobAsync(jobId,projectId,ct);return NoContent();}catch(EntityNotFoundException){return NotFound();}catch(InvalidOperationException ex){return Conflict(Problem("ยกเลิก Automation Queue ไม่สำเร็จ",ex.Message,409));}}
 [HttpPost("runs/{runId:guid}/cases/{caseId:guid}/evidence"),RequestSizeLimit(10_500_000)]public async Task<IActionResult>UploadEvidence(Guid runId,Guid caseId,[FromQuery]Guid projectId,IFormFile file,CancellationToken ct){if(file.Length==0||file.Length>10_000_000)return BadRequest(Problem("Evidence ไม่ถูกต้อง","ไฟล์ต้องมีขนาด 1 byte ถึง 10 MB",400));string[]allowed=[".png",".jpg",".jpeg",".webp",".txt",".log",".json"];var ext=Path.GetExtension(file.FileName).ToLowerInvariant();if(!allowed.Contains(ext))return BadRequest(Problem("ชนิด Evidence ไม่รองรับ","รองรับ PNG, JPG, WEBP, TXT, LOG และ JSON",400));var relative=Path.Combine(runId.ToString("N"),$"{caseId:N}{ext}");var root=EvidenceRoot();var full=Path.GetFullPath(Path.Combine(root,relative));if(!full.StartsWith(root,StringComparison.OrdinalIgnoreCase))return BadRequest();Directory.CreateDirectory(Path.GetDirectoryName(full)!);await using(var stream=System.IO.File.Create(full)){await file.CopyToAsync(stream,ct);}try{await service.AttachEvidenceAsync(runId,caseId,projectId,relative.Replace('\\','/'),ct);return Ok(new{evidencePath=relative.Replace('\\','/')});}catch(EntityNotFoundException){System.IO.File.Delete(full);return NotFound();}}
 [HttpGet("runs/{runId:guid}/cases/{caseId:guid}/evidence")]public async Task<IActionResult>DownloadEvidence(Guid runId,Guid caseId,[FromQuery]Guid projectId,CancellationToken ct){try{var relative=await service.GetEvidencePathAsync(runId,caseId,projectId,ct);if(string.IsNullOrWhiteSpace(relative))return NotFound();var root=EvidenceRoot();var full=Path.GetFullPath(Path.Combine(root,relative));if(!full.StartsWith(root,StringComparison.OrdinalIgnoreCase)||!System.IO.File.Exists(full))return NotFound();var provider=new FileExtensionContentTypeProvider();if(!provider.TryGetContentType(full,out var contentType))contentType="application/octet-stream";return PhysicalFile(full,contentType,Path.GetFileName(full));}catch(EntityNotFoundException){return NotFound();}}
 [HttpGet("agents")]public Task<IReadOnlyList<AutomationRunnerAgentDto>>ListAgents([FromQuery]Guid projectId,CancellationToken ct)=>service.ListAgentsAsync(projectId,ct);
 [HttpPost("agents/heartbeat")]public async Task<ActionResult<AutomationRunnerAgentDto>>Heartbeat([FromQuery]Guid projectId,AutomationRunnerHeartbeatRequest request,CancellationToken ct){try{return Ok(await service.HeartbeatAgentAsync(projectId,request,ct));}catch(ArgumentException ex){return BadRequest(Problem("Runner heartbeat invalid",ex.Message,400));}catch(InvalidOperationException ex){return Conflict(Problem("Runner lease invalid",ex.Message,409));}}
 [HttpGet("schedules")]public Task<IReadOnlyList<AutomationScheduleDto>>ListSchedules([FromQuery]Guid projectId,CancellationToken ct)=>service.ListSchedulesAsync(projectId,ct);
 [HttpPost("schedules")]public async Task<ActionResult<AutomationScheduleDto>>CreateSchedule([FromQuery]Guid projectId,CreateAutomationScheduleRequest request,CancellationToken ct){if(projectId!=request.ProjectId)return BadRequest();try{return Ok(await service.CreateScheduleAsync(request,UserId(),ct));}catch(ArgumentException ex){return BadRequest(Problem("Automation schedule invalid",ex.Message,400));}}
 [HttpDelete("schedules/{scheduleId:guid}")]public async Task<IActionResult>DisableSchedule(Guid scheduleId,[FromQuery]Guid projectId,CancellationToken ct){try{await service.DisableScheduleAsync(scheduleId,projectId,ct);return NoContent();}catch(EntityNotFoundException){return NotFound();}}
 [HttpGet("notifications")]public Task<IReadOnlyList<AutomationNotificationDto>>Notifications([FromQuery]Guid projectId,CancellationToken ct)=>service.ListNotificationsAsync(projectId,ct);
 private string EvidenceRoot(){var root=Path.GetFullPath(Path.Combine(environment.ContentRootPath,"App_Data","AutomationEvidence"));Directory.CreateDirectory(root);return root+Path.DirectorySeparatorChar;}
 private Guid?UserId()=>Guid.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier)??User.FindFirstValue("sub"),out var id)?id:null;
}
