using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProMaxx2.QA.Domain.Defects;
using ProMaxx2.QA.Infrastructure.Persistence;
using ProMaxx2.QA.Api.Services;
using ProMaxx2.QA.Application.Common;
using ProMaxx2.QA.Application.Identity;

namespace ProMaxx2.QA.Api.Controllers;

[ApiController,Route("api/v1/defects"),Authorize(Policy="DefectView"),RequireProjectAccess]
public sealed class DefectsController(QaDbContext db,ProjectAccessContext projectCtx,BusinessCodeGenerator codeGen,DefectActivityService activityService):ControllerBase
{
 [HttpGet,Authorize(Policy="DefectView")]public async Task<ActionResult<DefectListResultDto>>List([FromQuery]Guid?projectId,[FromQuery]Guid?releaseId,[FromQuery]Guid?buildId,[FromQuery]Guid?moduleId,[FromQuery]Guid?assigneeUserId,[FromQuery]string?severity,[FromQuery]string?status,[FromQuery]string?search,[FromQuery]int page=1,[FromQuery]int size=20,CancellationToken ct=default){var q=db.Defects.AsNoTracking().Where(x=>!x.IsDeleted);if(projectId.HasValue)q=q.Where(x=>x.ProjectId==projectId);else if(projectCtx.AllowedProjectIds.Length>0)q=q.Where(x=>projectCtx.AllowedProjectIds.Contains(x.ProjectId));else q=q.Where(_=>false);if(releaseId.HasValue)q=q.Where(x=>x.ReleaseId==releaseId);if(buildId.HasValue)q=q.Where(x=>x.BuildId==buildId);if(moduleId.HasValue)q=q.Where(x=>x.ModuleId==moduleId);if(assigneeUserId.HasValue)q=q.Where(x=>x.AssigneeUserId==assigneeUserId);if(!string.IsNullOrWhiteSpace(severity))q=q.Where(x=>x.Severity==severity);if(!string.IsNullOrWhiteSpace(status))q=q.Where(x=>x.Status==status);if(!string.IsNullOrWhiteSpace(search))q=q.Where(x=>x.DefectCode.Contains(search)||x.Title.Contains(search));var total=await q.CountAsync(ct);var rows=await q.OrderByDescending(x=>x.CreatedAt).Skip((page-1)*size).Take(size).Select(x=>new DefectDto(x.DefectId,x.ProjectId,x.ReleaseId,x.BuildId,x.ModuleId,x.DefectCode,x.Title,x.Description,x.StepsToReproduce,x.ExpectedResult,x.ActualResult,x.Severity,x.Status,x.AssigneeUserId,x.CreatedByUserId,x.CreatedAt,x.UpdatedAt)).ToListAsync(ct);var open=await db.Defects.AsNoTracking().Where(x=>!x.IsDeleted&&x.Status=="Open").CountAsync(ct);var inProgress=await db.Defects.AsNoTracking().Where(x=>!x.IsDeleted&&x.Status=="In Progress").CountAsync(ct);var closed=await db.Defects.AsNoTracking().Where(x=>!x.IsDeleted&&x.Status=="Closed").CountAsync(ct);return Ok(new DefectListResultDto(rows,total,open,inProgress,closed));}
 [HttpGet("{id:guid}"),Authorize(Policy="DefectView")]public async Task<ActionResult<DefectDto>>Get(Guid id,CancellationToken ct){var entity=await db.Defects.AsNoTracking().FirstOrDefaultAsync(x=>x.DefectId==id&&!x.IsDeleted,ct);if(entity is null)return NotFound();return Ok(await MapAsync(entity,ct));}
 [HttpGet("{id:guid}/activities"),Authorize(Policy="DefectView")]public async Task<ActionResult<IReadOnlyList<DefectActivityDto>>>Activities(Guid id,CancellationToken ct){var entity=await db.Defects.AsNoTracking().FirstOrDefaultAsync(x=>x.DefectId==id&&!x.IsDeleted,ct);if(entity is null)return NotFound();return Ok(await activityService.GetActivitiesAsync(id,ct));}
 [HttpPost("{id:guid}/comments"),Authorize(Policy="DefectEdit")]public async Task<IActionResult>AddComment(Guid id,AddDefectCommentRequest r,CancellationToken ct){var entity=await db.Defects.FirstOrDefaultAsync(x=>x.DefectId==id&&!x.IsDeleted,ct);if(entity is null)return NotFound();await activityService.AddCommentAsync(id,r.Body,UserId(),ct);return NoContent();}
 [HttpDelete("{defectId:guid}/comments/{commentId:guid}"),Authorize(Policy="DefectEdit")]public async Task<IActionResult>DeleteComment(Guid defectId,Guid commentId,CancellationToken ct){await activityService.DeleteCommentAsync(defectId,commentId,UserId(),ct);return NoContent();}
 [HttpGet("{id:guid}/test-cases"),Authorize(Policy="DefectView")]public async Task<ActionResult<IReadOnlyList<DefectTestCaseDto>>>TestCases(Guid id,CancellationToken ct){var entity=await db.Defects.AsNoTracking().FirstOrDefaultAsync(x=>x.DefectId==id&&!x.IsDeleted,ct);if(entity is null)return NotFound();return Ok(await db.DefectTestCases.AsNoTracking().Where(x=>x.DefectId==id).Join(db.TestCases,x=>x.TestCaseId,y=>y.TestCaseId,(x,y)=>new DefectTestCaseDto(y.TestCaseId,y.TestCaseCode,y.Title)).ToListAsync(ct));}
 [HttpPost("{id:guid}/test-cases"),Authorize(Policy="DefectEdit")]public async Task<IActionResult>LinkTestCase(Guid id,LinkDefectTestCaseRequest r,CancellationToken ct){var entity=await db.Defects.FirstOrDefaultAsync(x=>x.DefectId==id&&!x.IsDeleted,ct);if(entity is null)return NotFound();if(!await db.TestCases.AnyAsync(x=>x.TestCaseId==r.TestCaseId&&!x.IsDeleted,ct))return BadRequest("Test Case not found.");if(await db.DefectTestCases.AnyAsync(x=>x.DefectId==id&&x.TestCaseId==r.TestCaseId,ct))return Conflict("Already linked.");db.DefectTestCases.Add(new Domain.Defects.DefectTestCase(id,r.TestCaseId));await db.SaveChangesAsync(ct);await activityService.LogAsync(id,"LinkTestCase",$"Linked test case {r.TestCaseId}",UserId(),ct);return NoContent();}
 [HttpDelete("{id:guid}/test-cases/{testCaseId:guid}"),Authorize(Policy="DefectEdit")]public async Task<IActionResult>UnlinkTestCase(Guid id,Guid testCaseId,CancellationToken ct){var link=await db.DefectTestCases.FirstOrDefaultAsync(x=>x.DefectId==id&&x.TestCaseId==testCaseId,ct);if(link is null)return NotFound();db.DefectTestCases.Remove(link);await db.SaveChangesAsync(ct);await activityService.LogAsync(id,"UnlinkTestCase",$"Unlinked test case {testCaseId}",UserId(),ct);return NoContent();}
 [HttpPost("bulk"),Authorize(Policy="DefectEdit")]public async Task<IActionResult>Bulk(BulkDefectRequest r,CancellationToken ct){if(r.Ids is null||r.Ids.Count==0)return BadRequest("No defect IDs provided.");var entities=await db.Defects.Where(x=>r.Ids.Contains(x.DefectId)&&!x.IsDeleted).ToListAsync(ct);foreach(var e in entities){if(r.Delete.HasValue&&r.Delete.Value){e.SoftDelete(UserId());}else{if(!string.IsNullOrWhiteSpace(r.Status))e.UpdateStatus(r.Status,UserId());if(!string.IsNullOrWhiteSpace(r.Severity))e.UpdateSeverity(r.Severity,UserId());if(r.AssigneeUserId.HasValue)e.Assign(r.AssigneeUserId.Value,UserId());}}await db.SaveChangesAsync(ct);return Ok(new{updated=entities.Count});}
 [HttpPost,Authorize(Policy="DefectEdit")]public async Task<ActionResult<DefectDto>>Create(SaveDefectRequest r,CancellationToken ct){if(!await db.Projects.AnyAsync(x=>x.ProjectId==r.ProjectId&&x.IsActive,ct))return BadRequest("Project is not active.");var code=await codeGen.NextAvailable("DEF",r.ProjectId,ct);var entity=new Defect(r.ProjectId,r.ReleaseId,r.BuildId,r.ModuleId,code,r.Title,r.Severity,r.Status,r.Description,r.StepsToReproduce,r.ExpectedResult,r.ActualResult,r.AssigneeUserId,UserId());await db.Defects.AddAsync(entity,ct);await db.SaveChangesAsync(ct);await activityService.LogAsync(entity.DefectId,"Created","Defect created",UserId(),ct);return Ok(await MapAsync(entity,ct));}
 [HttpPut("{id:guid}"),Authorize(Policy="DefectEdit")]public async Task<ActionResult<DefectDto>>Update(Guid id,SaveDefectRequest r,CancellationToken ct){var entity=await db.Defects.FirstOrDefaultAsync(x=>x.DefectId==id&&!x.IsDeleted,ct);if(entity is null)return NotFound();var changes=entity.GetChangeSummary(r);entity.Update(r.Title,r.Severity,r.Status,r.Description,r.StepsToReproduce,r.ExpectedResult,r.ActualResult,r.AssigneeUserId,UserId());await db.SaveChangesAsync(ct);if(changes.Count>0)await activityService.LogAsync(id,"Updated",$"Updated: {string.Join(", ",changes)}",UserId(),ct);return Ok(await MapAsync(entity,ct));}
 [HttpPatch("{id:guid}/status"),Authorize(Policy="DefectEdit")]public async Task<ActionResult<DefectDto>>ChangeStatus(Guid id,ChangeDefectStatusRequest r,CancellationToken ct){var entity=await db.Defects.FirstOrDefaultAsync(x=>x.DefectId==id&&!x.IsDeleted,ct);if(entity is null)return NotFound();var old=entity.Status;entity.UpdateStatus(r.Status,UserId());await db.SaveChangesAsync(ct);await activityService.LogAsync(id,"StatusChanged",$"Status changed from {old} to {r.Status}",UserId(),ct);return Ok(await MapAsync(entity,ct));}
 [HttpPatch("{id:guid}/severity"),Authorize(Policy="DefectEdit")]public async Task<ActionResult<DefectDto>>ChangeSeverity(Guid id,ChangeDefectSeverityRequest r,CancellationToken ct){var entity=await db.Defects.FirstOrDefaultAsync(x=>x.DefectId==id&&!x.IsDeleted,ct);if(entity is null)return NotFound();var old=entity.Severity;entity.UpdateSeverity(r.Severity,UserId());await db.SaveChangesAsync(ct);await activityService.LogAsync(id,"SeverityChanged",$"Severity changed from {old} to {r.Severity}",UserId(),ct);return Ok(await MapAsync(entity,ct));}
 [HttpDelete("{id:guid}"),Authorize(Policy="DefectEdit")]public async Task<IActionResult>Delete(Guid id,CancellationToken ct){var entity=await db.Defects.FirstOrDefaultAsync(x=>x.DefectId==id&&!x.IsDeleted,ct);if(entity is null)return NotFound();entity.SoftDelete(UserId());await db.SaveChangesAsync(ct);await activityService.LogAsync(id,"Deleted","Defect deleted",UserId(),ct);return NoContent();}
 private async Task<DefectDto>MapAsync(Domain.Defects.Defect x,CancellationToken ct)=>new(x.DefectId,x.ProjectId,x.ReleaseId,x.BuildId,x.ModuleId,x.DefectCode,x.Title,x.Description,x.StepsToReproduce,x.ExpectedResult,x.ActualResult,x.Severity,x.Status,x.AssigneeUserId,x.CreatedByUserId,x.CreatedAt,x.UpdatedAt);
 private Guid?UserId()=>Guid.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier)??User.FindFirstValue("sub"),out var id)?id:null;
}
public sealed record SaveDefectRequest(Guid ProjectId,Guid?ReleaseId,Guid?BuildId,Guid?ModuleId,string Title,string Severity="Medium",string Status="Open",string?Description=null,string?StepsToReproduce=null,string?ExpectedResult=null,string?ActualResult=null,Guid?AssigneeUserId=null);
public sealed record ChangeDefectStatusRequest(string Status);
public sealed record ChangeDefectSeverityRequest(string Severity);
public sealed record AddDefectCommentRequest(string Body);
public sealed record LinkDefectTestCaseRequest(Guid TestCaseId);
public sealed record BulkDefectRequest(IReadOnlyList<Guid>?Ids,string?Status=null,string?Severity=null,Guid?AssigneeUserId=null,bool?Delete=null);
public sealed record DefectDto(Guid DefectId,Guid ProjectId,Guid?ReleaseId,Guid?BuildId,Guid?ModuleId,string DefectCode,string Title,string?Description,string?StepsToReproduce,string?ExpectedResult,string?ActualResult,string Severity,string Status,Guid?AssigneeUserId,Guid?CreatedByUserId,DateTime CreatedAt,DateTime?UpdatedAt);
public sealed record DefectActivityDto(Guid ActivityId,Guid DefectId,string ActivityType,string? Description,Guid? PerformedByUserId,DateTime PerformedAt);
public sealed record DefectTestCaseDto(Guid TestCaseId,string TestCaseCode,string Title);
public sealed record DefectSummaryDto(int Open,int InProgress,int Closed);
public sealed record DefectListResultDto(IReadOnlyList<DefectDto> Rows,int Total,int Open,int InProgress,int Closed);
