using System.Security.Claims;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using ProMaxx2.QA.Application.Projects;using ProMaxx2.QA.Application.Releases;
namespace ProMaxx2.QA.Api.Controllers;
[ApiController,Route("api/v1"),Authorize(Policy="ProjectView")]
public sealed class ReleasesController(ReleaseService service):ControllerBase
{
 [HttpGet("releases")]public Task<IReadOnlyList<ReleaseDto>>List([FromQuery]Guid? projectId,CancellationToken ct)=>service.ListAsync(projectId,ct);
 [HttpGet("projects/{projectId:guid}/releases")]public Task<IReadOnlyList<ReleaseDto>>ListForProject(Guid projectId,CancellationToken ct)=>service.ListAsync(projectId,ct);
 [HttpGet("releases/{id:guid}")]public async Task<ActionResult<ReleaseDto>>Get(Guid id,CancellationToken ct){try{return Ok(await service.GetAsync(id,ct));}catch(EntityNotFoundException){return NotFound();}}
 [HttpPost("projects/{projectId:guid}/releases"),Authorize(Policy="ProjectEdit")]public async Task<ActionResult<ReleaseDto>>Create(Guid projectId,CreateReleaseRequest request,CancellationToken ct){try{var r=await service.CreateAsync(projectId,request,UserId(),ct);return CreatedAtAction(nameof(Get),new{id=r.ReleaseId},r);}catch(DuplicateCodeException ex){return Conflict(Problem("รหัส Release ซ้ำ",ex.Message,409));}catch(ArgumentException ex){return BadRequest(Problem("ข้อมูลไม่ถูกต้อง",ex.Message,400));}}
 [HttpPut("releases/{id:guid}"),Authorize(Policy="ProjectEdit")]public async Task<ActionResult<ReleaseDto>>Update(Guid id,UpdateReleaseRequest request,CancellationToken ct){try{return Ok(await service.UpdateAsync(id,request,UserId(),ct));}catch(EntityNotFoundException){return NotFound();}catch(ArgumentException ex){return BadRequest(Problem("ข้อมูลไม่ถูกต้อง",ex.Message,400));}}
 [HttpPost("releases/{id:guid}/status"),Authorize(Policy="ProjectEdit")]public async Task<ActionResult<ReleaseDto>>Status(Guid id,ChangeReleaseStatusRequest request,CancellationToken ct){try{return Ok(await service.ChangeStatusAsync(id,request.Status,UserId(),ct));}catch(EntityNotFoundException){return NotFound();}catch(ArgumentException ex){return BadRequest(Problem("สถานะไม่ถูกต้อง",ex.Message,400));}}
 [HttpGet("releases/{releaseId:guid}/builds")]public Task<IReadOnlyList<BuildDto>>Builds(Guid releaseId,CancellationToken ct)=>service.ListBuildsAsync(releaseId,ct);
 [HttpPost("releases/{releaseId:guid}/builds"),Authorize(Policy="ProjectEdit")]public async Task<ActionResult<BuildDto>>CreateBuild(Guid releaseId,CreateBuildRequest request,CancellationToken ct){try{return Ok(await service.CreateBuildAsync(releaseId,request,UserId(),ct));}catch(EntityNotFoundException){return NotFound();}catch(DuplicateCodeException ex){return Conflict(Problem("หมายเลข Build ซ้ำ",ex.Message,409));}catch(ArgumentException ex){return BadRequest(Problem("ข้อมูลไม่ถูกต้อง",ex.Message,400));}}
 [HttpGet("builds/{id:guid}")]public async Task<ActionResult<BuildDto>>GetBuild(Guid id,CancellationToken ct){try{return Ok(await service.GetBuildAsync(id,ct));}catch(EntityNotFoundException){return NotFound();}}
 [HttpPut("builds/{id:guid}"),Authorize(Policy="ProjectEdit")]public async Task<ActionResult<BuildDto>>UpdateBuild(Guid id,UpdateBuildRequest request,CancellationToken ct){try{return Ok(await service.UpdateBuildAsync(id,request,ct));}catch(EntityNotFoundException){return NotFound();}}
 [HttpPost("builds/{id:guid}/mark-release-candidate"),Authorize(Policy="ProjectEdit")]public async Task<ActionResult<BuildDto>>MarkRc(Guid id,CancellationToken ct){try{return Ok(await service.MarkRcAsync(id,ct));}catch(EntityNotFoundException){return NotFound();}}
 private Guid? UserId()=>Guid.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier)??User.FindFirstValue("sub"),out var id)?id:null;private static ProblemDetails Problem(string title,string detail,int status)=>new(){Title=title,Detail=detail,Status=status};
}
