using System.Security.Claims;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using ProMaxx2.QA.Application.Projects;using ProMaxx2.QA.Application.Requirements;
namespace ProMaxx2.QA.Api.Controllers;
[ApiController,Route("api/v1/requirements"),Authorize(Policy="RequirementView")]
public sealed class RequirementsController(RequirementService service):ControllerBase
{
 [HttpGet]public Task<IReadOnlyList<RequirementDto>>List([FromQuery]Guid?projectId,[FromQuery]Guid?releaseId,[FromQuery]Guid?moduleId,[FromQuery]string?status,[FromQuery]string?priority,[FromQuery]bool?inScope,[FromQuery]string?search,CancellationToken ct)=>service.ListAsync(new(projectId,releaseId,moduleId,status,priority,inScope,search),ct);
 [HttpGet("{id:guid}")]public async Task<ActionResult<RequirementDto>>Get(Guid id,CancellationToken ct){try{return Ok(await service.GetAsync(id,ct));}catch(EntityNotFoundException){return NotFound();}}
 [HttpPost,Authorize(Policy="RequirementEdit")]public async Task<ActionResult<RequirementDto>>Create(CreateRequirementRequest request,CancellationToken ct){try{var r=await service.CreateAsync(request,UserId(),ct);return CreatedAtAction(nameof(Get),new{id=r.RequirementId},r);}catch(DuplicateCodeException ex){return Conflict(P("รหัส Requirement ซ้ำ",ex.Message,409));}catch(ArgumentException ex){return BadRequest(P("ข้อมูลไม่ถูกต้อง",ex.Message,400));}}
 [HttpPut("{id:guid}"),Authorize(Policy="RequirementEdit")]public async Task<ActionResult<RequirementDto>>Update(Guid id,UpdateRequirementRequest request,CancellationToken ct){try{return Ok(await service.UpdateAsync(id,request,UserId(),ct));}catch(EntityNotFoundException){return NotFound();}catch(ArgumentException ex){return BadRequest(P("ข้อมูลไม่ถูกต้อง",ex.Message,400));}}
 [HttpPost("{id:guid}/revision"),Authorize(Policy="RequirementEdit")]public async Task<ActionResult<RequirementDto>>Revision(Guid id,CreateRevisionRequest request,CancellationToken ct){try{return Ok(await service.ReviseAsync(id,request,UserId(),ct));}catch(EntityNotFoundException){return NotFound();}catch(ArgumentException ex){return BadRequest(P("ข้อมูล Revision ไม่ถูกต้อง",ex.Message,400));}}
 [HttpGet("{id:guid}/revisions")]public Task<IReadOnlyList<RequirementRevisionDto>>Revisions(Guid id,CancellationToken ct)=>service.RevisionsAsync(id,ct);
 [HttpPost("{id:guid}/status"),Authorize(Policy="RequirementEdit")]public async Task<ActionResult<RequirementDto>>Status(Guid id,ChangeRequirementStatusRequest request,CancellationToken ct){try{return Ok(await service.StatusAsync(id,request.Status,UserId(),ct));}catch(EntityNotFoundException){return NotFound();}catch(ArgumentException ex){return BadRequest(P("สถานะไม่ถูกต้อง",ex.Message,400));}}
 [HttpDelete("{id:guid}"),Authorize(Policy="RequirementEdit")]public async Task<IActionResult>Delete(Guid id,CancellationToken ct){try{await service.DeleteAsync(id,UserId(),ct);return NoContent();}catch(EntityNotFoundException){return NotFound();}}
 private Guid?UserId()=>Guid.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier)??User.FindFirstValue("sub"),out var id)?id:null;private static ProblemDetails P(string title,string detail,int status)=>new(){Title=title,Detail=detail,Status=status};
}
