using System.Security.Claims;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using ProMaxx2.QA.Application.Projects;using ProMaxx2.QA.Application.Requirements;using ProMaxx2.QA.Api.Services;
namespace ProMaxx2.QA.Api.Controllers;
[ApiController,Route("api/v1/requirements"),Authorize(Policy="RequirementView"),RequireProjectAccess]
public sealed class RequirementsController(RequirementService service,RequirementAiService ai):ControllerBase
{
 [HttpGet]public Task<IReadOnlyList<RequirementDto>>List([FromQuery]Guid?projectId,[FromQuery]Guid?releaseId,[FromQuery]Guid?moduleId,[FromQuery]string?status,[FromQuery]string?priority,[FromQuery]bool?inScope,[FromQuery]string?search,CancellationToken ct)=>service.ListAsync(new(projectId,releaseId,moduleId,status,priority,inScope,search),ct);
 [HttpGet("{id:guid}")]public async Task<ActionResult<RequirementDto>>Get(Guid id,CancellationToken ct){try{return Ok(await service.GetAsync(id,ct));}catch(EntityNotFoundException){return NotFound();}}
 [HttpPost,Authorize(Policy="RequirementEdit")]public async Task<ActionResult<RequirementDto>>Create(CreateRequirementRequest request,CancellationToken ct){try{var r=await service.CreateAsync(request,UserId(),ct);return CreatedAtAction(nameof(Get),new{id=r.RequirementId},r);}catch(DuplicateCodeException ex){return Conflict(P("รหัส Requirement ซ้ำ",ex.Message,409));}catch(ArgumentException ex){return BadRequest(P("ข้อมูลไม่ถูกต้อง",ex.Message,400));}}
 [HttpPut("{id:guid}"),Authorize(Policy="RequirementEdit")]public async Task<ActionResult<RequirementDto>>Update(Guid id,UpdateRequirementRequest request,CancellationToken ct){try{return Ok(await service.UpdateAsync(id,request,UserId(),ct));}catch(EntityNotFoundException){return NotFound();}catch(ArgumentException ex){return BadRequest(P("ข้อมูลไม่ถูกต้อง",ex.Message,400));}}
 [HttpPost("{id:guid}/revision"),Authorize(Policy="RequirementEdit")]public async Task<ActionResult<RequirementDto>>Revision(Guid id,CreateRevisionRequest request,CancellationToken ct){try{return Ok(await service.ReviseAsync(id,request,UserId(),ct));}catch(EntityNotFoundException){return NotFound();}catch(ArgumentException ex){return BadRequest(P("ข้อมูล Revision ไม่ถูกต้อง",ex.Message,400));}}
 [HttpGet("{id:guid}/revisions")]public Task<IReadOnlyList<RequirementRevisionDto>>Revisions(Guid id,CancellationToken ct)=>service.RevisionsAsync(id,ct);
 [HttpPost("{id:guid}/status"),Authorize(Policy="RequirementEdit")]public async Task<ActionResult<RequirementDto>>Status(Guid id,ChangeRequirementStatusRequest request,CancellationToken ct){try{return Ok(await service.StatusAsync(id,request.Status,UserId(),ct));}catch(EntityNotFoundException){return NotFound();}catch(ArgumentException ex){return BadRequest(P("สถานะไม่ถูกต้อง",ex.Message,400));}}
 [HttpDelete("{id:guid}"),Authorize(Policy="RequirementEdit")]public async Task<IActionResult>Delete(Guid id,CancellationToken ct){try{await service.DeleteAsync(id,UserId(),ct);return NoContent();}catch(EntityNotFoundException){return NotFound();}}
 [HttpPost("generate-ai"),Authorize(Policy="RequirementEdit"),RequestSizeLimit(21_000_000)]public async Task<ActionResult<GeneratedRequirement>>GenerateAi([FromForm]string prompt,[FromForm]string?projectName,[FromForm]string?moduleName,[FromForm]string?releaseName,List<IFormFile>?files,CancellationToken ct){try{var uploads=files??[];if(uploads.Count>5)return BadRequest(P("ไฟล์แนบมากเกินไป","แนบไฟล์ได้ไม่เกิน 5 ไฟล์",400));if(uploads.Sum(x=>x.Length)>20_000_000)return BadRequest(P("ไฟล์แนบมีขนาดใหญ่เกินไป","ขนาดไฟล์รวมต้องไม่เกิน 20 MB",400));string[]allowedExtensions=[".pdf",".txt",".md",".csv",".docx",".xlsx",".png",".jpg",".jpeg",".webp"];var attachments=new List<RequirementAiAttachment>();foreach(var file in uploads){var extension=Path.GetExtension(file.FileName).ToLowerInvariant();if(!allowedExtensions.Contains(extension))return BadRequest(P("ชนิดไฟล์ไม่รองรับ",$"ไม่รองรับไฟล์ {Path.GetFileName(file.FileName)}",400));await using var memory=new MemoryStream();await file.CopyToAsync(memory,ct);attachments.Add(new(Path.GetFileName(file.FileName),file.ContentType,memory.ToArray()));}return Ok(await ai.GenerateAsync(new(prompt,projectName,moduleName,releaseName,attachments),ct));}catch(ArgumentException ex){return BadRequest(P("ข้อมูลสำหรับ AI ไม่ครบ",ex.Message,400));}catch(InvalidOperationException ex){return StatusCode(ai.IsConfigured?502:503,P("AI Generate Requirement ไม่พร้อมใช้งาน",ex.Message,ai.IsConfigured?502:503));}catch(OperationCanceledException){return StatusCode(504,P("AI ใช้เวลาประมวลผลนานเกินไป","กรุณาลองใหม่อีกครั้ง หรือลดขนาดข้อมูล input",504));}catch(Exception ex){return StatusCode(500,P("AI Generate Requirement ไม่สำเร็จ",ex.InnerException?.Message??ex.Message,500));}}
 private Guid?UserId()=>Guid.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier)??User.FindFirstValue("sub"),out var id)?id:null;private static ProblemDetails P(string title,string detail,int status)=>new(){Title=title,Detail=detail,Status=status};
}
