using System.Security.Claims;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using ProMaxx2.QA.Application.Projects;using ProMaxx2.QA.Application.TestManagement;
namespace ProMaxx2.QA.Api.Controllers;
[ApiController,Route("api/v1"),Authorize(Policy="TestCaseView")]
public sealed class TestCasesController(TestCaseService service):ControllerBase
{
 [HttpGet("test-cases")]public Task<IReadOnlyList<TestCaseDto>>List([FromQuery]Guid?projectId,[FromQuery]string?search,CancellationToken ct)=>service.ListAsync(projectId,search,ct);[HttpGet("test-cases/{id:guid}")]public async Task<ActionResult<TestCaseDto>>Get(Guid id,CancellationToken ct){try{return Ok(await service.GetAsync(id,ct));}catch(EntityNotFoundException){return NotFound();}}
 [HttpPost("test-cases"),Authorize(Policy="TestCaseEdit")]public async Task<ActionResult<TestCaseDto>>Create(CreateTestCaseRequest request,CancellationToken ct){try{var r=await service.CreateAsync(request,UserId(),ct);return CreatedAtAction(nameof(Get),new{id=r.TestCaseId},r);}catch(DuplicateCodeException ex){return Conflict(new ProblemDetails{Title="รหัส Test Case ซ้ำ",Detail=ex.Message,Status=409});}catch(ArgumentException ex){return BadRequest(new ProblemDetails{Title="ข้อมูลไม่ถูกต้อง",Detail=ex.Message,Status=400});}}
 [HttpPost("test-cases/{id:guid}/revision"),Authorize(Policy="TestCaseEdit")]public async Task<ActionResult<TestCaseDto>>Revision(Guid id,CreateTestCaseRevisionRequest request,CancellationToken ct){try{return Ok(await service.ReviseAsync(id,request,UserId(),ct));}catch(EntityNotFoundException){return NotFound();}catch(ArgumentException ex){return BadRequest(new ProblemDetails{Title="ข้อมูล Revision ไม่ถูกต้อง",Detail=ex.Message,Status=400});}}
 [HttpPost("test-cases/{id:guid}/status"),Authorize(Policy="TestCaseEdit")]public async Task<ActionResult<TestCaseDto>>Status(Guid id,ChangeTestCaseStatusRequest request,CancellationToken ct){try{return Ok(await service.StatusAsync(id,request.Status,UserId(),ct));}catch(EntityNotFoundException){return NotFound();}catch(Exception ex)when(ex is ArgumentException or InvalidOperationException){return BadRequest(new ProblemDetails{Title="เปลี่ยนสถานะไม่ได้",Detail=ex.Message,Status=400});}}[HttpDelete("test-cases/{id:guid}"),Authorize(Policy="TestCaseEdit")]public async Task<IActionResult>Delete(Guid id,CancellationToken ct){try{await service.DeleteAsync(id,UserId(),ct);return NoContent();}catch(EntityNotFoundException){return NotFound();}}
 [HttpPost("requirements/{requirementId:guid}/test-cases/{testCaseId:guid}"),Authorize(Policy="TestCaseEdit")]public async Task<IActionResult>Link(Guid requirementId,Guid testCaseId,[FromQuery]string?coverageType,CancellationToken ct){try{await service.LinkAsync(requirementId,testCaseId,coverageType,ct);return NoContent();}catch(EntityNotFoundException){return NotFound();}}[HttpDelete("requirements/{requirementId:guid}/test-cases/{testCaseId:guid}"),Authorize(Policy="TestCaseEdit")]public async Task<IActionResult>Unlink(Guid requirementId,Guid testCaseId,CancellationToken ct){await service.UnlinkAsync(requirementId,testCaseId,ct);return NoContent();}
 [HttpGet("releases/{releaseId:guid}/rtm")]public Task<IReadOnlyList<RtmRow>>Rtm(Guid releaseId,CancellationToken ct)=>service.RtmAsync(releaseId,ct);[HttpGet("releases/{releaseId:guid}/coverage-summary")]public Task<CoverageSummary>Coverage(Guid releaseId,CancellationToken ct)=>service.CoverageAsync(releaseId,ct);private Guid?UserId()=>Guid.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier)??User.FindFirstValue("sub"),out var id)?id:null;
}
