using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using ProMaxx2.QA.Application.Projects;using ProMaxx2.QA.Application.TestManagement;using ProMaxx2.QA.Application.Requirements;using ProMaxx2.QA.Api.Services;using ProMaxx2.QA.Application.Common;
namespace ProMaxx2.QA.Api.Controllers;
public sealed record GenerateTestSuiteAiRequest(Guid ProjectId,Guid ModuleId,IReadOnlyList<string>SuiteTypes,IReadOnlyList<string>RiskTiers);
[ApiController,Route("api/v1/test-suites"),Authorize(Policy="TestCaseView"),RequireProjectAccess]
public sealed class TestSuitesController(TestSuiteService service,TestSuiteAiService ai,ProjectService projects,RequirementService requirements,TestCaseService testCases):ControllerBase
{
 [HttpGet]public Task<PagedResult<TestSuiteListDto>>List([FromQuery]Guid?projectId,[FromQuery]string?search,[FromQuery]string?suiteType,[FromQuery]string?riskTier,[FromQuery]bool?isActive,[FromQuery]int page=1,[FromQuery]int size=20,CancellationToken ct=default)=>service.ListAsync(projectId,search,suiteType,riskTier,isActive,page,size,ct);[HttpGet("{id:guid}")]public async Task<ActionResult<TestSuiteDto>>Get(Guid id,CancellationToken ct){try{return Ok(await service.GetAsync(id,ct));}catch(EntityNotFoundException){return NotFound();}}
 [HttpPost,Authorize(Policy="TestCaseEdit")]public async Task<ActionResult<TestSuiteDto>>Create(SaveTestSuiteRequest r,CancellationToken ct){try{var result=await service.CreateAsync(r,ct);return CreatedAtAction(nameof(Get),new{id=result.TestSuiteId},result);}catch(DuplicateCodeException ex){return Conflict(new ProblemDetails{Title="รหัส Test Suite ซ้ำ",Detail=ex.Message,Status=409});}catch(ArgumentException ex){return BadRequest(new ProblemDetails{Title="ข้อมูลไม่ถูกต้อง",Detail=ex.Message,Status=400});}}
 [HttpPost("generate-ai"),Authorize(Policy="TestCaseEdit")]
 public async Task<ActionResult<IReadOnlyList<GeneratedTestSuite>>>GenerateAi(GenerateTestSuiteAiRequest request,CancellationToken ct){try{var project=(await projects.ListAsync(ct)).SingleOrDefault(x=>x.ProjectId==request.ProjectId)??throw new ArgumentException("ไม่พบ Project ที่เลือก");var module=(await projects.ListModulesAsync(request.ProjectId,ct)).SingleOrDefault(x=>x.ModuleId==request.ModuleId&&x.IsActive)??throw new ArgumentException("ไม่พบ Module ที่เลือก");var requirementRows=(await requirements.ListAsync(new(request.ProjectId,null,request.ModuleId,null,null,true,null,1,1000),ct)).Rows;var caseRows=(await testCases.ListAsync(request.ProjectId,request.ModuleId,null,null,null,null,null,null,null,1,250,ct)).Rows.Where(x=>x.Status!="Deprecated").ToList();var caseDetails=(await Task.WhenAll(caseRows.Select(x=>testCases.GetAsync(x.TestCaseId,ct)))).Where(x=>x is not null).Select(x=>x!).ToList();return Ok(await ai.GenerateAsync(project.ProjectName,module.ModuleName,requirementRows,caseDetails,request.SuiteTypes,request.RiskTiers,ct));}catch(ArgumentException ex){return BadRequest(new ProblemDetails{Title="ข้อมูลสำหรับ AI ไม่ครบ",Detail=ex.Message,Status=400});}catch(InvalidOperationException ex){var status=ai.IsConfigured?502:503;return StatusCode(status,new ProblemDetails{Title="AI Generate Test Suite ไม่พร้อมใช้งาน",Detail=ex.Message,Status=status});}catch(OperationCanceledException){return StatusCode(504,new ProblemDetails{Title="AI ใช้เวลาประมวลผลนานเกินไป",Detail="กรุณาลองใหม่อีกครั้ง หรือลดจำนวน Test Case ใน Module",Status=504});}catch(Exception ex){return StatusCode(500,new ProblemDetails{Title="AI Generate Test Suite ไม่สำเร็จ",Detail=ex.InnerException?.Message??ex.Message,Status=500});}}
 [HttpPut("{id:guid}"),Authorize(Policy="TestCaseEdit")]public async Task<ActionResult<TestSuiteDto>>Update(Guid id,SaveTestSuiteRequest r,CancellationToken ct){try{return Ok(await service.UpdateAsync(id,r,ct));}catch(EntityNotFoundException){return NotFound();}catch(ArgumentException ex){return BadRequest(new ProblemDetails{Title="ข้อมูลไม่ถูกต้อง",Detail=ex.Message,Status=400});}}
 [HttpDelete("{id:guid}"),Authorize(Policy="TestCaseEdit")]public async Task<IActionResult>Delete(Guid id,CancellationToken ct){try{await service.DeactivateAsync(id,ct);return NoContent();}catch(EntityNotFoundException){return NotFound();}}
 [HttpDelete("{id:guid}/hard"),Authorize(Policy="TestCaseEdit")]public async Task<IActionResult>HardDelete(Guid id,CancellationToken ct){try{await service.HardDeleteAsync(id,ct);return NoContent();}catch(EntityNotFoundException){return NotFound();}catch(InvalidOperationException ex){return BadRequest(new ProblemDetails{Title="ไม่สามารถลบได้",Detail=ex.Message,Status=400});}}
 [HttpPost("{id:guid}/cases"),Authorize(Policy="TestCaseEdit")]public async Task<IActionResult>AddCases(Guid id,AddSuiteCasesRequest r,CancellationToken ct){try{await service.AddCasesAsync(id,r,ct);return NoContent();}catch(EntityNotFoundException){return NotFound();}}[HttpPut("{id:guid}/cases/{caseId:guid}"),Authorize(Policy="TestCaseEdit")]public async Task<IActionResult>UpdateCase(Guid id,Guid caseId,UpdateSuiteCaseRequest r,CancellationToken ct){try{await service.UpdateCaseAsync(id,caseId,r,ct);return NoContent();}catch(EntityNotFoundException){return NotFound();}catch(ArgumentOutOfRangeException ex){return BadRequest(new ProblemDetails{Title="ลำดับไม่ถูกต้อง",Detail=ex.Message,Status=400});}}[HttpDelete("{id:guid}/cases/{caseId:guid}"),Authorize(Policy="TestCaseEdit")]public async Task<IActionResult>RemoveCase(Guid id,Guid caseId,CancellationToken ct){await service.RemoveCaseAsync(id,caseId,ct);return NoContent();}
}
