using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using ProMaxx2.QA.Application.Projects;using ProMaxx2.QA.Application.TestManagement;using ProMaxx2.QA.Application.Requirements;using ProMaxx2.QA.Api.Services;
namespace ProMaxx2.QA.Api.Controllers;
public sealed record GenerateTestSuiteAiRequest(Guid ProjectId,Guid ModuleId,IReadOnlyList<string>SuiteTypes,IReadOnlyList<string>RiskTiers);
[ApiController,Route("api/v1/test-suites"),Authorize(Policy="TestCaseView"),RequireProjectAccess]
public sealed class TestSuitesController(TestSuiteService service,TestSuiteAiService ai,ProjectService projects,RequirementService requirements,TestCaseService testCases):ControllerBase
{
 [HttpGet]public Task<IReadOnlyList<TestSuiteDto>>List([FromQuery]Guid?projectId,[FromQuery]string?search,CancellationToken ct)=>service.ListAsync(projectId,search,ct);[HttpGet("{id:guid}")]public async Task<ActionResult<TestSuiteDto>>Get(Guid id,CancellationToken ct){try{return Ok(await service.GetAsync(id,ct));}catch(EntityNotFoundException){return NotFound();}}
 [HttpPost,Authorize(Policy="TestCaseEdit")]public async Task<ActionResult<TestSuiteDto>>Create(SaveTestSuiteRequest r,CancellationToken ct){try{var result=await service.CreateAsync(r,ct);return CreatedAtAction(nameof(Get),new{id=result.TestSuiteId},result);}catch(DuplicateCodeException ex){return Conflict(new ProblemDetails{Title="รหัส Test Suite ซ้ำ",Detail=ex.Message,Status=409});}catch(ArgumentException ex){return BadRequest(new ProblemDetails{Title="ข้อมูลไม่ถูกต้อง",Detail=ex.Message,Status=400});}}
 [HttpPost("generate-ai"),Authorize(Policy="TestCaseEdit")]
 public async Task<ActionResult<IReadOnlyList<GeneratedTestSuite>>>GenerateAi(GenerateTestSuiteAiRequest request,CancellationToken ct){try{var project=(await projects.ListAsync(ct)).SingleOrDefault(x=>x.ProjectId==request.ProjectId)??throw new ArgumentException("ไม่พบ Project ที่เลือก");var module=(await projects.ListModulesAsync(request.ProjectId,ct)).SingleOrDefault(x=>x.ModuleId==request.ModuleId&&x.IsActive)??throw new ArgumentException("ไม่พบ Module ที่เลือก");var requirementRows=await requirements.ListAsync(new(request.ProjectId,null,request.ModuleId,null,null,true,null),ct);var caseRows=(await testCases.ListAsync(request.ProjectId,null,ct)).Where(x=>x.ModuleId==request.ModuleId&&x.Status!="Deprecated").ToList();return Ok(await ai.GenerateAsync(project.ProjectName,module.ModuleName,requirementRows,caseRows,request.SuiteTypes,request.RiskTiers,ct));}catch(ArgumentException ex){return BadRequest(new ProblemDetails{Title="ข้อมูลสำหรับ AI ไม่ครบ",Detail=ex.Message,Status=400});}catch(InvalidOperationException ex){var status=ai.IsConfigured?502:503;return StatusCode(status,new ProblemDetails{Title="AI Generate Test Suite ไม่พร้อมใช้งาน",Detail=ex.Message,Status=status});}catch(OperationCanceledException){return StatusCode(504,new ProblemDetails{Title="AI ใช้เวลาประมวลผลนานเกินไป",Detail="กรุณาลองใหม่อีกครั้ง หรือลดจำนวน Test Case ใน Module",Status=504});}catch(Exception ex){return StatusCode(500,new ProblemDetails{Title="AI Generate Test Suite ไม่สำเร็จ",Detail=ex.InnerException?.Message??ex.Message,Status=500});}}
 [HttpPut("{id:guid}"),Authorize(Policy="TestCaseEdit")]public async Task<ActionResult<TestSuiteDto>>Update(Guid id,SaveTestSuiteRequest r,CancellationToken ct){try{return Ok(await service.UpdateAsync(id,r,ct));}catch(EntityNotFoundException){return NotFound();}catch(ArgumentException ex){return BadRequest(new ProblemDetails{Title="ข้อมูลไม่ถูกต้อง",Detail=ex.Message,Status=400});}}
 [HttpDelete("{id:guid}"),Authorize(Policy="TestCaseEdit")]public async Task<IActionResult>Delete(Guid id,CancellationToken ct){try{await service.DeactivateAsync(id,ct);return NoContent();}catch(EntityNotFoundException){return NotFound();}}
 [HttpPost("{id:guid}/cases"),Authorize(Policy="TestCaseEdit")]public async Task<IActionResult>AddCases(Guid id,AddSuiteCasesRequest r,CancellationToken ct){try{await service.AddCasesAsync(id,r,ct);return NoContent();}catch(EntityNotFoundException){return NotFound();}}[HttpPut("{id:guid}/cases/{caseId:guid}"),Authorize(Policy="TestCaseEdit")]public async Task<IActionResult>UpdateCase(Guid id,Guid caseId,UpdateSuiteCaseRequest r,CancellationToken ct){try{await service.UpdateCaseAsync(id,caseId,r,ct);return NoContent();}catch(EntityNotFoundException){return NotFound();}catch(ArgumentOutOfRangeException ex){return BadRequest(new ProblemDetails{Title="ลำดับไม่ถูกต้อง",Detail=ex.Message,Status=400});}}[HttpDelete("{id:guid}/cases/{caseId:guid}"),Authorize(Policy="TestCaseEdit")]public async Task<IActionResult>RemoveCase(Guid id,Guid caseId,CancellationToken ct){await service.RemoveCaseAsync(id,caseId,ct);return NoContent();}
}
