namespace ProMaxx2.QA.Domain.TestManagement;
public sealed class TestCase
{
 private TestCase(){}
 public TestCase(Guid projectId,Guid moduleId,string code,string title,string?objective,string?preconditions,string priority,string?testType,bool automation,Guid?ownerId,IEnumerable<TestStepInput>steps,Guid?createdBy){Validate(title,priority,steps);TestCaseId=Guid.NewGuid();ProjectId=projectId;ModuleId=moduleId;TestCaseCode=code.Trim().ToUpperInvariant();Title=title.Trim();Objective=objective?.Trim();Preconditions=preconditions?.Trim();Priority=priority.ToUpperInvariant();TestType=testType?.Trim();AutomationCandidate=automation;OwnerUserId=ownerId;Status="Draft";RevisionNo=1;CreatedAt=DateTime.UtcNow;CreatedBy=createdBy;SetSteps(steps,1);}
 public Guid TestCaseId{get;private set;}public Guid ProjectId{get;private set;}public Guid ModuleId{get;private set;}public Guid?TestScenarioId{get;private set;}public string TestCaseCode{get;private set;}=string.Empty;public string Title{get;private set;}=string.Empty;public string?Objective{get;private set;}public string?Preconditions{get;private set;}public string Priority{get;private set;}="P2";public string?TestType{get;private set;}public bool AutomationCandidate{get;private set;}public string?AutomationTarget{get;private set;}public string Status{get;private set;}="Draft";public int RevisionNo{get;private set;}public Guid?OwnerUserId{get;private set;}public bool IsDeleted{get;private set;}public DateTime CreatedAt{get;private set;}public Guid?CreatedBy{get;private set;}public DateTime?UpdatedAt{get;private set;}public Guid?UpdatedBy{get;private set;}public ICollection<TestStep>Steps{get;private set;}=[];public ICollection<TestCaseRevision>Revisions{get;private set;}=[];
 public void ChangeStatus(string status,Guid?userId){string[]allowed=["Draft","Review","Ready","Deprecated"];if(status.Equals("Ready",StringComparison.OrdinalIgnoreCase)&&!Steps.Any(x=>x.RevisionNo==RevisionNo))throw new InvalidOperationException("Ready test case requires at least one step.");Status=allowed.SingleOrDefault(x=>x.Equals(status,StringComparison.OrdinalIgnoreCase))??throw new ArgumentException("Invalid test case status.");UpdatedAt=DateTime.UtcNow;UpdatedBy=userId;}public void SoftDelete(Guid?userId){IsDeleted=true;UpdatedAt=DateTime.UtcNow;UpdatedBy=userId;}
  public void SetAutomationTarget(string? target,Guid?userId){if(!AutomationCandidate)throw new InvalidOperationException("Only automation candidates can have an automation target.");var normalized=string.IsNullOrWhiteSpace(target)?null:target.Trim().ToLowerInvariant();if(normalized is not null and not "pos" and not "app")throw new ArgumentException("Automation target must be pos, app, or empty.");AutomationTarget=normalized;UpdatedAt=DateTime.UtcNow;UpdatedBy=userId;}
  public void SetAutomationCandidate(bool automation,Guid?userId){AutomationCandidate=automation;if(!automation)AutomationTarget=null;UpdatedAt=DateTime.UtcNow;UpdatedBy=userId;}
 public void CreateRevision(string title,string?objective,string?preconditions,IEnumerable<TestStepInput>steps,string reason,Guid?userId){if(string.IsNullOrWhiteSpace(reason))throw new ArgumentException("Change reason is required.");Validate(title,Priority,steps);RevisionNo++;Title=title.Trim();Objective=objective?.Trim();Preconditions=preconditions?.Trim();SetSteps(steps,RevisionNo);UpdatedAt=DateTime.UtcNow;UpdatedBy=userId;Revisions.Add(new TestCaseRevision(TestCaseId,RevisionNo,reason,userId,UpdatedAt.Value));}
 public void Update(Guid moduleId,string title,string?objective,string?preconditions,string priority,string?testType,bool automation,Guid?ownerId,IEnumerable<TestStepInput>steps,string reason,Guid?userId){Validate(title,priority,steps);CreateRevision(title,objective,preconditions,steps,reason,userId);ModuleId=moduleId;Priority=priority.ToUpperInvariant();TestType=testType?.Trim();AutomationCandidate=automation;if(!automation)AutomationTarget=null;OwnerUserId=ownerId;}
 private void SetSteps(IEnumerable<TestStepInput>steps,int revision){foreach(var s in steps.OrderBy(x=>x.StepNo)){if(string.IsNullOrWhiteSpace(s.Action)||string.IsNullOrWhiteSpace(s.ExpectedResult))throw new ArgumentException("Every step requires action and expected result.");Steps.Add(new TestStep(TestCaseId,revision,s.StepNo,s.Action,s.TestData,s.ExpectedResult));}}
 private static void Validate(string title,string priority,IEnumerable<TestStepInput>steps){if(string.IsNullOrWhiteSpace(title))throw new ArgumentException("Title is required.");if(!new[]{"P0","P1","P2","P3"}.Contains(priority.ToUpperInvariant()))throw new ArgumentException("Priority must be P0-P3.");_ = steps??throw new ArgumentNullException(nameof(steps));}
}
public sealed record TestStepInput(int StepNo,string Action,string?TestData,string ExpectedResult);
public sealed class TestStep{private TestStep(){}public TestStep(Guid caseId,int revision,int no,string action,string?data,string expected){TestCaseId=caseId;RevisionNo=revision;StepNo=no;Action=action.Trim();TestDataText=data?.Trim();ExpectedResult=expected.Trim();}public Guid TestStepId{get;private set;}public Guid TestCaseId{get;private set;}public int RevisionNo{get;private set;}public int StepNo{get;private set;}public string Action{get;private set;}=string.Empty;public string?TestDataText{get;private set;}public string ExpectedResult{get;private set;}=string.Empty;public TestCase TestCase{get;private set;}=null!;}
public sealed class RequirementTestCase{private RequirementTestCase(){}public RequirementTestCase(Guid requirementId,Guid testCaseId,string?coverageType){RequirementId=requirementId;TestCaseId=testCaseId;CoverageType=coverageType;CreatedAt=DateTime.UtcNow;}public Guid RequirementId{get;private set;}public Guid TestCaseId{get;private set;}public string?CoverageType{get;private set;}public DateTime CreatedAt{get;private set;}}
public sealed class TestCaseRevision{private TestCaseRevision(){}public TestCaseRevision(Guid testCaseId,int revisionNo,string changeReason,Guid?changedBy,DateTime changedAt){TestCaseId=testCaseId;RevisionNo=revisionNo;ChangeReason=changeReason.Trim();ChangedBy=changedBy;ChangedAt=changedAt;}public Guid TestCaseRevisionId{get;private set;}public Guid TestCaseId{get;private set;}public int RevisionNo{get;private set;}public string ChangeReason{get;private set;}=string.Empty;public Guid?ChangedBy{get;private set;}public DateTime ChangedAt{get;private set;}public TestCase TestCase{get;private set;}=null!;}
