namespace ProMaxx2.QA.Application.Dashboard;

public sealed record DashboardModuleHealth(Guid ModuleId,Guid? ParentModuleId,string ModuleCode,string ModuleName,int SortOrder,int Requirements,int CoveredRequirements,int TestCases,int Executed,int Passed,int Failed,int Blocked,decimal CoveragePercent,decimal ExecutionPercent,decimal PassRate,string Health);
public sealed record DashboardUserPerformance(Guid UserId,string DisplayName,int Executions,int Passed,int Failed,int Blocked,decimal PassRate,DateTime?LastExecutedAt);
public sealed record DashboardStatusSlice(string Status,int Count,string Color);
public sealed record DashboardSeveritySlice(string Severity,int Count,string Color);
public sealed record DashboardSummary(int TotalRequirements,int CoveredRequirements,decimal RequirementCoverage,int TotalCases,int ExecutedCases,decimal ExecutionProgress,int PassedCases,decimal PassRate,int OpenP0,int OpenP1,decimal? OverallScore,int TotalDefects,int OpenDefects,int CriticalDefects,int HighDefects,decimal DefectQuality,string RecommendedDecision,IReadOnlyList<DashboardModuleHealth>Modules,IReadOnlyList<DashboardUserPerformance>Users,IReadOnlyList<DashboardStatusSlice>StatusDistribution,IReadOnlyList<DashboardSeveritySlice>DefectSeverityDistribution,DateTime GeneratedAt);
public sealed record DashboardShareScope(string Code,Guid? ProjectId,Guid? ReleaseId,Guid? BuildId,DateTime ExpiresAt);
public sealed record DashboardTimelineRelease(Guid ReleaseId,string ReleaseCode,string Version,string Status,DateOnly?PlannedReleaseDate,DateOnly?ActualReleaseDate);
public sealed record DashboardTimelineCycle(Guid TestCycleId,string CycleCode,string CycleName,string Status,DateTime?StartDate,DateTime?EndDate,decimal ProgressPercent);
public sealed record DashboardTimeline(IReadOnlyList<DashboardTimelineRelease>Releases,IReadOnlyList<DashboardTimelineCycle>Cycles);
public interface IDashboardRepository{Task<DashboardSummary>GetAsync(Guid?projectId,Guid?releaseId,Guid?buildId,CancellationToken ct);Task<DashboardTimeline>GetTimelineAsync(Guid?projectId,Guid?releaseId,Guid?buildId,CancellationToken ct);Task<DashboardShareScope>CreateShareAsync(Guid?projectId,Guid?releaseId,Guid?buildId,DateTime expiresAt,CancellationToken ct);Task<DashboardShareScope?>FindShareAsync(string code,CancellationToken ct);}
public sealed class DashboardService(IDashboardRepository repository){public Task<DashboardSummary>GetAsync(Guid?p,Guid?r,Guid?b,CancellationToken ct)=>repository.GetAsync(p,r,b,ct);public Task<DashboardTimeline>GetTimelineAsync(Guid?p,Guid?r,Guid?b,CancellationToken ct)=>repository.GetTimelineAsync(p,r,b,ct);public Task<DashboardShareScope>CreateShareAsync(Guid?p,Guid?r,Guid?b,DateTime expiresAt,CancellationToken ct)=>repository.CreateShareAsync(p,r,b,expiresAt,ct);public Task<DashboardShareScope?>FindShareAsync(string code,CancellationToken ct)=>repository.FindShareAsync(code,ct);}
