using ProMaxx2.QA.Domain.Releases;
using ProMaxx2.QA.Application.Common;
using ProMaxx2.QA.Application.Projects;

namespace ProMaxx2.QA.Application.Releases;
public sealed record ReleaseDto(Guid ReleaseId,Guid ProjectId,string ReleaseCode,string Version,string? ReleaseType,string? Scope,DateOnly? PlannedReleaseDate,DateOnly? ActualReleaseDate,string Status,Guid? ReleaseOwnerUserId,DateTime CreatedAt);
public sealed record CreateReleaseRequest(string ReleaseCode,string Version,string? ReleaseType,DateOnly? PlannedReleaseDate,string? Scope,Guid? ReleaseOwnerUserId);
public sealed record UpdateReleaseRequest(string Version,string? ReleaseType,DateOnly? PlannedReleaseDate,string? Scope,Guid? ReleaseOwnerUserId);public sealed record ChangeReleaseStatusRequest(string Status);
public sealed record BuildDto(Guid BuildId,Guid ReleaseId,string BuildNumber,string? ApplicationVersion,string? PackageVersion,string? CommitReference,DateTime? BuildDate,string? ChangeNotes,string? KnownIssues,bool IsReleaseCandidate,bool IsActive,string Status);
public sealed record CreateBuildRequest(string BuildNumber,string? ApplicationVersion,string? PackageVersion,string? CommitReference,DateTime? BuildDate,string? ChangeNotes,string? KnownIssues);
public sealed record UpdateBuildRequest(string? ApplicationVersion,string? PackageVersion,string? CommitReference,DateTime? BuildDate,string? ChangeNotes,string? KnownIssues);
public sealed record ChangeBuildStatusRequest(string Status);
public interface IReleaseRepository{Task<IReadOnlyList<ReleaseDto>> ListAsync(Guid? projectId,CancellationToken ct);Task<ReleaseDto?> GetAsync(Guid id,CancellationToken ct);Task<Release?> FindAsync(Guid id,CancellationToken ct);Task<bool> CodeExistsAsync(Guid projectId,string code,CancellationToken ct);Task AddAsync(Release entity,CancellationToken ct);Task<IReadOnlyList<BuildDto>> ListBuildsAsync(Guid releaseId,CancellationToken ct);Task<BuildDto?> GetBuildAsync(Guid id,CancellationToken ct);Task<Build?> FindBuildAsync(Guid id,CancellationToken ct);Task<int> CountBlockedAsync(Guid buildId,CancellationToken ct);Task<bool> BuildNumberExistsAsync(Guid releaseId,string number,CancellationToken ct);Task AddBuildAsync(Build entity,CancellationToken ct);Task SaveChangesAsync(CancellationToken ct);}
public sealed class ReleaseService(IReleaseRepository repository,IProjectRepository projects)
{
 public Task<IReadOnlyList<ReleaseDto>> ListAsync(Guid? projectId,CancellationToken ct)=>repository.ListAsync(projectId,ct);public async Task<ReleaseDto> GetAsync(Guid id,CancellationToken ct)=>await repository.GetAsync(id,ct)??throw new Projects.EntityNotFoundException("Release not found.");
 public async Task<ReleaseDto>CreateAsync(Guid projectId,CreateReleaseRequest r,Guid? userId,CancellationToken ct){var project=await projects.GetAsync(projectId,ct)??throw new Projects.EntityNotFoundException("Project not found.");var code=string.IsNullOrWhiteSpace(r.ReleaseCode)?BusinessCodeGenerator.Next($"{project.ProjectCode}-REL",(await repository.ListAsync(projectId,ct)).Select(x=>x.ReleaseCode)):r.ReleaseCode.Trim().ToUpperInvariant();if(await repository.CodeExistsAsync(projectId,code,ct))throw new Projects.DuplicateCodeException("Release code already exists in this project.");var e=new Release(projectId,code,r.Version,r.ReleaseType,r.Scope,r.PlannedReleaseDate,r.ReleaseOwnerUserId,userId);await repository.AddAsync(e,ct);await repository.SaveChangesAsync(ct);return(await repository.GetAsync(e.ReleaseId,ct))!;}
 public async Task<ReleaseDto>UpdateAsync(Guid id,UpdateReleaseRequest r,Guid? userId,CancellationToken ct){var e=await repository.FindAsync(id,ct)??throw new Projects.EntityNotFoundException("Release not found.");e.Update(r.Version,r.ReleaseType,r.Scope,r.PlannedReleaseDate,r.ReleaseOwnerUserId,userId);await repository.SaveChangesAsync(ct);return(await repository.GetAsync(id,ct))!;}
 public async Task<ReleaseDto>ChangeStatusAsync(Guid id,string status,Guid? userId,CancellationToken ct){var e=await repository.FindAsync(id,ct)??throw new Projects.EntityNotFoundException("Release not found.");e.ChangeStatus(status,userId);await repository.SaveChangesAsync(ct);return(await repository.GetAsync(id,ct))!;}
 public Task<IReadOnlyList<BuildDto>>ListBuildsAsync(Guid id,CancellationToken ct)=>repository.ListBuildsAsync(id,ct);public async Task<BuildDto>GetBuildAsync(Guid id,CancellationToken ct)=>await repository.GetBuildAsync(id,ct)??throw new Projects.EntityNotFoundException("Build not found.");
 public async Task<BuildDto>CreateBuildAsync(Guid releaseId,CreateBuildRequest r,Guid? userId,CancellationToken ct){_=await repository.GetAsync(releaseId,ct)??throw new Projects.EntityNotFoundException("Release not found.");if(await repository.BuildNumberExistsAsync(releaseId,r.BuildNumber.Trim(),ct))throw new Projects.DuplicateCodeException("Build number already exists in this release.");var e=new Build(releaseId,r.BuildNumber,r.ApplicationVersion,r.PackageVersion,r.CommitReference,r.BuildDate,r.ChangeNotes,r.KnownIssues,userId);await repository.AddBuildAsync(e,ct);await repository.SaveChangesAsync(ct);return(await repository.GetBuildAsync(e.BuildId,ct))!;}
 public async Task<BuildDto>UpdateBuildAsync(Guid id,UpdateBuildRequest r,CancellationToken ct){var e=await repository.FindBuildAsync(id,ct)??throw new Projects.EntityNotFoundException("Build not found.");e.Update(r.ApplicationVersion,r.PackageVersion,r.CommitReference,r.BuildDate,r.ChangeNotes,r.KnownIssues);await repository.SaveChangesAsync(ct);return(await repository.GetBuildAsync(id,ct))!;}
 public async Task<BuildDto>MarkRcAsync(Guid id,CancellationToken ct){var e=await repository.FindBuildAsync(id,ct)??throw new Projects.EntityNotFoundException("Build not found.");e.MarkReleaseCandidate();await repository.SaveChangesAsync(ct);return(await repository.GetBuildAsync(id,ct))!;}
 public async Task<BuildDto>ChangeBuildStatusAsync(Guid id,string status,CancellationToken ct){var e=await repository.FindBuildAsync(id,ct)??throw new Projects.EntityNotFoundException("Build not found.");e.ChangeStatus(status);await repository.SaveChangesAsync(ct);return(await repository.GetBuildAsync(id,ct))!;}
 public Task<int>CountBlockedAsync(Guid buildId,CancellationToken ct)=>repository.CountBlockedAsync(buildId,ct);
 public async Task DeactivateBuildAsync(Guid id,CancellationToken ct){var e=await repository.FindBuildAsync(id,ct)??throw new Projects.EntityNotFoundException("Build not found.");e.Deactivate();await repository.SaveChangesAsync(ct);}
}
