import { useState, useMemo, useEffect } from "react";
import type { ProjectItem } from "../shared/types";
import { apiUrl } from "../api";
import { notify, confirmDialog } from "../components/dialogStore";
import { Badge } from "../components/Badge";
import type { MasterOption } from "../shared/appShared";

const masterSettingGroups = [
  ["ReleaseType", "Release", "Release Type"],
  ["TestCasePriority", "Test Case", "Priority"],
  ["TestCaseType", "Test Case", "Type"],
  ["TestSuiteType", "Test Suite", "Type"],
  ["TestSuiteRiskTier", "Test Suite", "Risk Tier"],
  ["TestCycleType", "Test Cycle", "Cycle Type"],
] as const;
const masterSettingSections = [
  { name: "Release", description: "ค่าที่ใช้ในหน้าจัดการ Release", groups: masterSettingGroups.filter((x) => x[1] === "Release") },
  { name: "Test Case", description: "ค่าที่ใช้ในการออกแบบ Test Case", groups: masterSettingGroups.filter((x) => x[1] === "Test Case") },
  { name: "Test Suite", description: "ค่าที่ใช้จัดกลุ่ม Test Case", groups: masterSettingGroups.filter((x) => x[1] === "Test Suite") },
  { name: "Test Cycle", description: "ค่าที่ใช้ในการวางแผนรอบทดสอบ", groups: masterSettingGroups.filter((x) => x[1] === "Test Cycle") },
];
type EnvironmentSetting = { testEnvironmentId: string; projectId: string; environmentName: string; baseUrl?: string; isActive: boolean };
type AiConfiguration = { provider: "OpenAI" | "Google" | "Anthropic" | "OpenRouter" | "Local" | "opencode"; model: string; baseUrl?: string; isEnabled: boolean; hasApiKey: boolean; apiKeyHint?: string; updatedAt?: string };
const aiProviderModels: Record<AiConfiguration["provider"], string[]> = { OpenAI: ["gpt-5-mini", "gpt-5.4"], Google: ["gemini-3.5-flash", "gemini-3.1-pro"], Anthropic: ["claude-sonnet-5", "claude-haiku-4-5-20251001"], OpenRouter: ["openai/gpt-4o", "anthropic/claude-sonnet-4", "google/gemini-2.5-flash", "meta-llama/llama-4-maverick", "nvidia/nemotron-3.5-lightning:free"], Local: ["qwen3", "llama3.3", "mistral-small"], opencode: ["gpt-5-mini", "gpt-5", "gpt-4o", "claude-sonnet-4", "gemini-2.5-pro", "llama-3.3", "deepseek-v4-flash", "mimo-v2.5"] };
type AiModelOption = { id: string; displayName: string };
type CrmSyncSettingsView = { pollIntervalMinutes: number; updatedAt?: string | null };
type CrmProjectMapping = { crmProjectMappingId: string; projectId: string; crmProductId: string; crmVersionId?: string | null };
type EmailConfig = { smtpHost: string; smtpPort: number; senderEmail: string; senderDisplayName?: string | null; hasPassword: boolean; passwordHint?: string | null; isEnabled: boolean; updatedAt?: string | null };
export function MasterSettingsPage() {
  const [items, setItems] = useState<MasterOption[]>([]), [environments, setEnvironments] = useState<EnvironmentSetting[]>([]), [projects, setProjects] = useState<ProjectItem[]>([]), [reload, setReload] = useState(0);
  const [category, setCategory] = useState("ReleaseType"), [formCategory, setFormCategory] = useState<string | null>(null), [value, setValue] = useState(""), [displayName, setDisplayName] = useState(""), [sortOrder, setSortOrder] = useState(10), [editing, setEditing] = useState<MasterOption | null>(null);
  const [environment, setEnvironment] = useState<EnvironmentSetting | null>(null), [environmentFormOpen, setEnvironmentFormOpen] = useState(false), [environmentProjectId, setEnvironmentProjectId] = useState(""), [environmentName, setEnvironmentName] = useState(""), [baseUrl, setBaseUrl] = useState("");
  const [aiConfiguration, setAiConfiguration] = useState<AiConfiguration>({ provider: "OpenAI", model: "gpt-5-mini", isEnabled: true, hasApiKey: false }), [aiApiKey, setAiApiKey] = useState(""), [savingAi, setSavingAi] = useState(false);
  const [aiModels, setAiModels] = useState<AiModelOption[]>([]), [loadingAiModels, setLoadingAiModels] = useState(false), [aiModelsError, setAiModelsError] = useState("");
  const [crmSyncSettings, setCrmSyncSettings] = useState<CrmSyncSettingsView>({ pollIntervalMinutes: 2 }), [savingCrmSync, setSavingCrmSync] = useState(false);
  const [crmMappings, setCrmMappings] = useState<CrmProjectMapping[]>([]);
  const [crmMappingEditing, setCrmMappingEditing] = useState<CrmProjectMapping | null>(null), [crmMappingFormOpen, setCrmMappingFormOpen] = useState(false), [crmMappingProjectId, setCrmMappingProjectId] = useState(""), [crmMappingProductId, setCrmMappingProductId] = useState(""), [crmMappingVersionId, setCrmMappingVersionId] = useState("");
  const [emailConfig, setEmailConfig] = useState<EmailConfig>({ smtpHost: "smtp.gmail.com", smtpPort: 587, senderEmail: "", hasPassword: false, isEnabled: true }), [emailPassword, setEmailPassword] = useState(""), [savingEmail, setSavingEmail] = useState(false);
  const [emailTestTo, setEmailTestTo] = useState(""), [sendingTestEmail, setSendingTestEmail] = useState(false), [testEmailResult, setTestEmailResult] = useState<{ ok: boolean; message: string } | null>(null);
  const [activeSection, setActiveSection] = useState("AI");
  const headers = useMemo(() => ({ "Content-Type": "application/json", Authorization: `Bearer ${localStorage.getItem("qa.accessToken")}` }), []);
  useEffect(() => {
    const load = async () => {
      const read = async (url: string) => { const response = await fetch(url, { headers }); if (!response.ok) throw new Error(`โหลดข้อมูลไม่สำเร็จ (${response.status})`); return response.json(); };
      try { const [masterData, environmentData, projectData, aiData, crmSyncData, crmMappingData, emailData] = await Promise.all([read(`${apiUrl}/master-settings?includeInactive=true`), read(`${apiUrl}/master-settings/environments`), read(`${apiUrl}/projects`), read(`${apiUrl}/master-settings/ai`), read(`${apiUrl}/master-settings/crm-sync`), read(`${apiUrl}/master-settings/crm-mappings`), read(`${apiUrl}/master-settings/email`)]); setItems(masterData); setEnvironments(environmentData); setProjects(projectData); setAiConfiguration(aiData); setCrmSyncSettings(crmSyncData); setCrmMappings(crmMappingData); setEmailConfig(emailData); setEnvironmentProjectId((x) => x || projectData[0]?.projectId || ""); }
      catch (error) { notify(error instanceof Error ? `${error.message} กรุณาตรวจสอบว่า API ใช้งานเวอร์ชันล่าสุด` : "โหลดการตั้งค่ากลางไม่สำเร็จ", "error"); }
    };
    load();
  }, [reload, headers]);
  const resetOption = () => { setEditing(null); setFormCategory(null); setValue(""); setDisplayName(""); setSortOrder(10); };
  const saveOption = async () => {
    const response = await fetch(`${apiUrl}/master-settings${editing ? `/${editing.masterOptionId}` : ""}`, { method: editing ? "PUT" : "POST", headers, body: JSON.stringify({ category: editing?.category ?? category, value, displayName, sortOrder, isActive: editing?.isActive ?? true }) });
    if (!response.ok) { const p = await response.json(); notify(p.detail ?? "บันทึกข้อมูลไม่สำเร็จ", "error"); return; } resetOption(); setReload((x) => x + 1);
  };
  const toggleOption = async (item: MasterOption) => { await fetch(`${apiUrl}/master-settings/${item.masterOptionId}`, { method: "PUT", headers, body: JSON.stringify({ ...item, isActive: !item.isActive }) }); setReload((x) => x + 1); };
  const deleteOption = async (item: MasterOption) => { if (!await confirmDialog(`ยืนยันลบ ${item.displayName}?`)) return; const response = await fetch(`${apiUrl}/master-settings/${item.masterOptionId}`, { method: "DELETE", headers }); if (!response.ok) { const p = await response.json(); notify(p.detail ?? "ลบข้อมูลไม่สำเร็จ", "error"); return; } if (editing?.masterOptionId === item.masterOptionId) resetOption(); setReload((x) => x + 1); };
  const editEnvironment = (item?: EnvironmentSetting) => { setEnvironment(item ?? null); setEnvironmentFormOpen(true); setEnvironmentProjectId(item?.projectId ?? projects[0]?.projectId ?? ""); setEnvironmentName(item?.environmentName ?? ""); setBaseUrl(item?.baseUrl ?? ""); };
  const resetEnvironment = () => { setEnvironment(null); setEnvironmentFormOpen(false); setEnvironmentName(""); setBaseUrl(""); };
  const saveEnvironment = async () => { const response = await fetch(`${apiUrl}/master-settings/environments${environment ? `/${environment.testEnvironmentId}` : ""}`, { method: environment ? "PUT" : "POST", headers, body: JSON.stringify({ projectId: environmentProjectId, environmentName, baseUrl: baseUrl || null, isActive: environment?.isActive ?? true }) }); if (!response.ok) { const p = await response.json(); notify(p.detail ?? "บันทึก Environment ไม่สำเร็จ", "error"); return; } resetEnvironment(); setReload((x) => x + 1); };
  const toggleEnvironment = async (item: EnvironmentSetting) => { await fetch(`${apiUrl}/master-settings/environments/${item.testEnvironmentId}`, { method: "PUT", headers, body: JSON.stringify({ ...item, isActive: !item.isActive }) }); setReload((x) => x + 1); };
  const deleteEnvironment = async (item: EnvironmentSetting) => { if (!await confirmDialog(`ยืนยันลบ Environment ${item.environmentName}?`)) return; const response = await fetch(`${apiUrl}/master-settings/environments/${item.testEnvironmentId}`, { method: "DELETE", headers }); if (!response.ok) { const p = await response.json(); notify(p.detail ?? "ลบ Environment ไม่สำเร็จ", "error"); return; } if (environment?.testEnvironmentId === item.testEnvironmentId) resetEnvironment(); setReload((x) => x + 1); };
  const openOptionForm = (targetCategory: string, item?: MasterOption) => { setCategory(targetCategory); setFormCategory(targetCategory); setEditing(item ?? null); setValue(item?.value ?? ""); setDisplayName(item?.displayName ?? ""); setSortOrder(item?.sortOrder ?? 10); };
  const saveAiConfiguration = async () => { setSavingAi(true); try { const response = await fetch(`${apiUrl}/master-settings/ai`, { method: "PUT", headers, body: JSON.stringify({ provider: aiConfiguration.provider, model: aiConfiguration.model, baseUrl: aiConfiguration.baseUrl || null, apiKey: aiApiKey || null, isEnabled: aiConfiguration.isEnabled, clearApiKey: false }) }); if (!response.ok) { const problem = await response.json(); throw new Error(problem.detail ?? "บันทึกการตั้งค่า AI ไม่สำเร็จ"); } setAiConfiguration(await response.json()); setAiApiKey(""); notify("บันทึกการตั้งค่า AI เรียบร้อยแล้ว", "success"); } catch (error) { notify(error instanceof Error ? error.message : "บันทึกการตั้งค่า AI ไม่สำเร็จ", "error"); } finally { setSavingAi(false); } };
  const loadAiModels = async () => { setLoadingAiModels(true); setAiModelsError(""); try { const response = await fetch(`${apiUrl}/master-settings/ai/models`, { method: "POST", headers, body: JSON.stringify({ provider: aiConfiguration.provider, baseUrl: aiConfiguration.baseUrl || null, apiKey: aiApiKey || null }) }); if (!response.ok) { const problem = await response.json(); throw new Error(problem.detail ?? "โหลดรายการ Model ไม่สำเร็จ"); } const models = await response.json() as AiModelOption[]; setAiModels(models); if (!models.length) setAiModelsError("Provider ไม่ส่งรายการ Model กลับมา"); } catch (error) { setAiModelsError(error instanceof Error ? error.message : "โหลดรายการ Model ไม่สำเร็จ"); } finally { setLoadingAiModels(false); } };
  const saveCrmSyncSettings = async () => { setSavingCrmSync(true); try { const response = await fetch(`${apiUrl}/master-settings/crm-sync`, { method: "PUT", headers, body: JSON.stringify({ pollIntervalMinutes: crmSyncSettings.pollIntervalMinutes }) }); if (!response.ok) { const problem = await response.json(); throw new Error(problem.detail ?? "บันทึกรอบ Poll ไม่สำเร็จ"); } setCrmSyncSettings(await response.json()); notify("บันทึกรอบ Poll เรียบร้อยแล้ว", "success"); } catch (error) { notify(error instanceof Error ? error.message : "บันทึกรอบ Poll ไม่สำเร็จ", "error"); } finally { setSavingCrmSync(false); } };
  // ค่าเริ่มต้น CRM Product Id = "34" — ตอนนี้ทุก Project ที่เจอใน CRM จริงใช้ Product เดียวกันนี้ (ยืนยันจากผู้ใช้)
  // ยังแก้ไขเป็นค่าอื่นได้ตามปกติ นี่แค่ prefill ให้ไม่ต้องพิมพ์ซ้ำทุกครั้งตอนเพิ่ม Mapping ใหม่
  const editCrmMapping = (item?: CrmProjectMapping) => { setCrmMappingEditing(item ?? null); setCrmMappingFormOpen(true); setCrmMappingProjectId(item?.projectId ?? projects.find((p) => !crmMappings.some((m) => m.projectId === p.projectId))?.projectId ?? projects[0]?.projectId ?? ""); setCrmMappingProductId(item?.crmProductId ?? "34"); setCrmMappingVersionId(item?.crmVersionId ?? ""); };
  const resetCrmMapping = () => { setCrmMappingEditing(null); setCrmMappingFormOpen(false); setCrmMappingProductId(""); setCrmMappingVersionId(""); };
  const saveCrmMapping = async () => { const response = await fetch(`${apiUrl}/master-settings/crm-mappings${crmMappingEditing ? `/${crmMappingEditing.crmProjectMappingId}` : ""}`, { method: crmMappingEditing ? "PUT" : "POST", headers, body: JSON.stringify({ projectId: crmMappingProjectId, crmProductId: crmMappingProductId, crmVersionId: crmMappingVersionId || null }) }); if (!response.ok) { const p = await response.json(); notify(p.detail ?? "บันทึก CRM Mapping ไม่สำเร็จ", "error"); return; } resetCrmMapping(); setReload((x) => x + 1); };
  const deleteCrmMapping = async (item: CrmProjectMapping) => { if (!await confirmDialog("ยืนยันลบ CRM Mapping นี้?")) return; const response = await fetch(`${apiUrl}/master-settings/crm-mappings/${item.crmProjectMappingId}`, { method: "DELETE", headers }); if (!response.ok) { const p = await response.json(); notify(p.detail ?? "ลบ CRM Mapping ไม่สำเร็จ", "error"); return; } if (crmMappingEditing?.crmProjectMappingId === item.crmProjectMappingId) resetCrmMapping(); setReload((x) => x + 1); };
  const saveEmailConfig = async () => { setSavingEmail(true); try { const response = await fetch(`${apiUrl}/master-settings/email`, { method: "PUT", headers, body: JSON.stringify({ smtpHost: emailConfig.smtpHost, smtpPort: emailConfig.smtpPort, senderEmail: emailConfig.senderEmail, senderDisplayName: emailConfig.senderDisplayName || null, password: emailPassword || null, isEnabled: emailConfig.isEnabled, clearPassword: false }) }); if (!response.ok) { const problem = await response.json(); throw new Error(problem.detail ?? "บันทึกการตั้งค่า Email ไม่สำเร็จ"); } setEmailConfig(await response.json()); setEmailPassword(""); notify("บันทึกการตั้งค่า Email เรียบร้อยแล้ว", "success"); } catch (error) { notify(error instanceof Error ? error.message : "บันทึกการตั้งค่า Email ไม่สำเร็จ", "error"); } finally { setSavingEmail(false); } };
  // ทดสอบด้วยค่าที่บันทึกไว้แล้วในฐานข้อมูล (ไม่ใช่ค่าที่กำลังพิมพ์ในฟอร์ม) — ต้องกด "บันทึกการตั้งค่า" ก่อนถึงจะทดสอบค่าล่าสุดได้
  const sendTestEmail = async () => { if (!emailTestTo.trim()) return; setSendingTestEmail(true); setTestEmailResult(null); try { const response = await fetch(`${apiUrl}/master-settings/email/test`, { method: "POST", headers, body: JSON.stringify({ toEmail: emailTestTo.trim() }) }); if (!response.ok) { const p = await response.json(); throw new Error(p.detail ?? "ส่งอีเมลทดสอบไม่สำเร็จ"); } setTestEmailResult({ ok: true, message: `ส่งอีเมลทดสอบไปที่ ${emailTestTo.trim()} สำเร็จ` }); } catch (error) { setTestEmailResult({ ok: false, message: error instanceof Error ? error.message : "ส่งอีเมลทดสอบไม่สำเร็จ" }); } finally { setSendingTestEmail(false); } };
  const optionForm = (targetCategory: string) => formCategory === targetCategory && <div className="master-inline-editor"><label>รหัสค่า<input autoFocus value={value} onChange={(e) => setValue(e.target.value)} placeholder="เช่น Major" /></label><label>ชื่อที่แสดง<input value={displayName} onChange={(e) => setDisplayName(e.target.value)} /></label><label className="master-order-field">ลำดับ<input type="number" value={sortOrder} onChange={(e) => setSortOrder(Number(e.target.value))} /></label><div className="master-setting-actions"><button className="btn" onClick={resetOption}><span className="material-symbols-outlined" aria-hidden="true">close</span> ยกเลิก</button><button className="btn primary" disabled={!value.trim() || !displayName.trim()} onClick={saveOption}>{editing ? "บันทึกการแก้ไข" : "เพิ่มข้อมูล"}</button></div></div>;
  const activeMasterSection = masterSettingSections.find((section) => section.name === activeSection);
  const aiReady = aiConfiguration.isEnabled && aiConfiguration.hasApiKey;
  const emailReady = emailConfig.isEnabled && emailConfig.hasPassword && !!emailConfig.senderEmail;
  return <div className="master-settings-page">
    <nav className="settings-nav" aria-label="หมวดการตั้งค่า">
      <button type="button" className={activeSection === "AI" ? "active" : ""} onClick={() => setActiveSection("AI")}>
        <span className="settings-nav-icon">AI</span><span className="settings-nav-label">AI Configuration</span>
        <Badge tone={aiReady ? "green" : "yellow"}>{aiReady ? "พร้อม" : "ยังไม่พร้อม"}</Badge>
      </button>
      {masterSettingSections.map((section) => <button type="button" key={section.name} className={activeSection === section.name ? "active" : ""} onClick={() => setActiveSection(section.name)}>
        <span className="settings-nav-icon">{section.name === "Release" ? "R" : section.name === "Test Case" ? "TC" : section.name === "Test Suite" ? "TS" : "CY"}</span>
        <span className="settings-nav-label">{section.name}</span>
        <span className="count-pill">{items.filter((x) => section.groups.some((g) => g[0] === x.category) && x.isActive).length}</span>
      </button>)}
      <button type="button" className={activeSection === "Environment" ? "active" : ""} onClick={() => setActiveSection("Environment")}>
        <span className="settings-nav-icon">E</span><span className="settings-nav-label">Environment</span>
        <span className="count-pill">{environments.filter((x) => x.isActive).length}</span>
      </button>
      <button type="button" className={activeSection === "CrmSync" ? "active" : ""} onClick={() => setActiveSection("CrmSync")}>
        <span className="settings-nav-icon">C</span><span className="settings-nav-label">CRM Sync</span>
        <span className="count-pill">{crmSyncSettings.pollIntervalMinutes} นาที</span>
      </button>
      <button type="button" className={activeSection === "CrmMapping" ? "active" : ""} onClick={() => setActiveSection("CrmMapping")}>
        <span className="settings-nav-icon">CM</span><span className="settings-nav-label">CRM Mapping</span>
        <span className="count-pill">{crmMappings.length}</span>
      </button>
      <button type="button" className={activeSection === "Email" ? "active" : ""} onClick={() => setActiveSection("Email")}>
        <span className="settings-nav-icon">✉</span><span className="settings-nav-label">Email / SMTP</span>
        <Badge tone={emailReady ? "green" : "yellow"}>{emailReady ? "พร้อม" : "ยังไม่พร้อม"}</Badge>
      </button>
    </nav>
    {activeSection === "AI" && <section className="settings-panel-card master-ai-configuration">
      <div className="settings-panel-head"><div><h2>AI Configuration</h2><p>ค่ากลางสำหรับ AI Generate ของ Requirement, Test Case และ Test Suite</p></div><Badge tone={aiReady ? "green" : "yellow"}>{aiReady ? "พร้อมใช้งาน" : "ยังไม่พร้อมใช้งาน"}</Badge></div>
      <div className="master-ai-body">
        <div className="master-ai-note"><b>การจัดเก็บที่ปลอดภัย</b><span>API key ถูกเข้ารหัสและเก็บเฉพาะฝั่ง Server เมื่อเปลี่ยน Provider ต้องกรอกคีย์ใหม่ ส่วน AI Local สามารถเว้นคีย์ได้</span></div>
        <div className="master-ai-form">
          <label className="master-ai-provider"><span className="master-ai-provider-label"><span>Provider</span><span className="master-ai-provider-badge">{aiConfiguration.provider}</span></span><select value={aiConfiguration.provider} onChange={(e) => { const provider = e.target.value as AiConfiguration["provider"]; setAiApiKey(""); setAiModels([]); setAiModelsError(""); setAiConfiguration((current) => ({ ...current, provider, model: aiProviderModels[provider][0], baseUrl: provider === "Local" ? "http://localhost:11434/v1" : provider === "OpenRouter" ? "https://openrouter.ai/api/v1" : provider === "opencode" ? "https://opencode.ai/zen/go/v1" : undefined, hasApiKey: false, apiKeyHint: undefined })); }}><option value="OpenAI">OpenAI</option><option value="Google">Google Gemini</option><option value="Anthropic">Anthropic Claude</option><option value="OpenRouter">OpenRouter</option><option value="Local">AI Local</option><option value="opencode">opencode</option></select></label>
          <label>Model<span className="master-model-label"><small>{aiModels.length ? `${aiModels.length} Models` : "เลือกหรือพิมพ์ Model ID"}</small><button type="button" onClick={loadAiModels} disabled={loadingAiModels}>{loadingAiModels ? <><span className="spinner inline" aria-hidden="true" /> กำลังโหลด...</> : "โหลดทั้งหมด"}</button></span><input list="ai-model-options" value={aiConfiguration.model} onChange={(e) => setAiConfiguration((current) => ({ ...current, model: e.target.value }))} placeholder="ระบุ Model ID" /><datalist id="ai-model-options">{(aiModels.length ? aiModels : aiProviderModels[aiConfiguration.provider].map((id) => ({ id, displayName: "" }))).map((model) => <option key={model.id} value={model.id}>{model.displayName}</option>)}</datalist>{aiModelsError && <small className="master-model-error">{aiModelsError}</small>}</label>
          {(aiConfiguration.provider === "Local" || aiConfiguration.provider === "OpenRouter" || aiConfiguration.provider === "opencode") && <label>Base URL<input value={aiConfiguration.baseUrl ?? ""} onChange={(e) => setAiConfiguration((current) => ({ ...current, baseUrl: e.target.value }))} placeholder={aiConfiguration.provider === "Local" ? "http://localhost:11434/v1" : aiConfiguration.provider === "OpenRouter" ? "https://openrouter.ai/api/v1" : "https://opencode.ai/zen/go/v1"} /></label>}
          <label>API key {aiConfiguration.provider === "Local" || aiConfiguration.provider === "opencode" ? <small>(ไม่บังคับ)</small> : null}<input type="password" autoComplete="new-password" value={aiApiKey} onChange={(e) => setAiApiKey(e.target.value)} placeholder={aiConfiguration.hasApiKey ? `ตั้งค่าแล้ว ${aiConfiguration.apiKeyHint ?? ""} — เว้นว่างเพื่อใช้ค่าเดิม` : (aiConfiguration.provider === "Local" || aiConfiguration.provider === "opencode") ? "เว้นว่างได้ หาก Server ไม่ใช้คีย์" : `กรอก API key สำหรับ ${aiConfiguration.provider}`} /></label>
          <label className="master-ai-toggle"><input type="checkbox" checked={aiConfiguration.isEnabled} onChange={(e) => setAiConfiguration((current) => ({ ...current, isEnabled: e.target.checked }))} /><span>เปิดใช้งาน AI ร่วมกันทุกระบบ</span></label>
          <div className="master-ai-actions"><small className="master-ai-hint">API key ถูกเข้ารหัสและเก็บเฉพาะฝั่ง Server · เมื่อเปลี่ยน Provider ต้องกรอกคีย์ใหม่</small><button className="btn primary" disabled={savingAi || !aiConfiguration.model.trim() || ((aiConfiguration.provider === "Local" || aiConfiguration.provider === "OpenRouter" || aiConfiguration.provider === "opencode") && !aiConfiguration.baseUrl?.trim()) || (aiConfiguration.provider !== "Local" && aiConfiguration.provider !== "opencode" && !aiConfiguration.hasApiKey && !aiApiKey.trim())} onClick={saveAiConfiguration}>{savingAi ? <><span className="spinner inline" aria-hidden="true" /> กำลังบันทึก...</> : <><span className="material-symbols-outlined" aria-hidden="true">check</span> บันทึกการตั้งค่า</>}</button></div>
        </div>
      </div>
    </section>}
    {activeMasterSection && <section className="settings-panel-card">
      <div className="settings-panel-head"><div><h2>{activeMasterSection.name}</h2><p>{activeMasterSection.description}</p></div></div>
      <div className="settings-groups">{activeMasterSection.groups.map((group) => <div className="master-subgroup" key={group[0]}><div className="master-subgroup-head"><h4>{group[2]}</h4><div><span>{items.filter((x) => x.category === group[0] && x.isActive).length}</span><button className="master-add-button" onClick={() => openOptionForm(group[0])}>+ เพิ่ม</button></div></div>{optionForm(group[0])}<div className="master-setting-list">{items.filter((x) => x.category === group[0]).map((item) => <div key={item.masterOptionId} className={!item.isActive ? "inactive" : ""}><span><b>{item.displayName}</b><small>{item.value} · ลำดับ {item.sortOrder}</small></span><button className="table-action icon-only" title="แก้ไข" aria-label={`แก้ไข ${item.displayName}`} onClick={() => openOptionForm(group[0], item)}><span className="material-symbols-outlined" aria-hidden="true">edit</span></button><button className="table-action danger-action icon-only" title="ลบ" aria-label={`ลบ ${item.displayName}`} onClick={() => deleteOption(item)}><span className="material-symbols-outlined" aria-hidden="true">close</span></button><button className="table-action icon-only" title={item.isActive ? "ปิดใช้" : "เปิดใช้"} aria-label={`${item.isActive ? "ปิดใช้" : "เปิดใช้"} ${item.displayName}`} onClick={() => toggleOption(item)}><span className="material-symbols-outlined" aria-hidden="true">power_settings_new</span></button></div>)}</div></div>)}</div>
    </section>}
    {activeSection === "Environment" && <section className="settings-panel-card">
      <div className="settings-panel-head"><div><h2>Environment</h2><p>URL ของแต่ละ Project ที่ใช้อ้างอิงตอนวางแผน Test Cycle และ Execution</p></div><button className="master-add-button" onClick={() => editEnvironment()}>+ เพิ่ม</button></div>
      {environmentFormOpen && <div className="master-setting-form environment-form"><label>Project<select disabled={!!environment} value={environmentProjectId} onChange={(e) => setEnvironmentProjectId(e.target.value)}>{projects.map((x) => <option key={x.projectId} value={x.projectId}>{x.projectName}</option>)}</select></label><label>Environment<input autoFocus value={environmentName} onChange={(e) => setEnvironmentName(e.target.value)} /></label><label>Base URL<input value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} /></label><div className="master-setting-actions"><button className="btn" onClick={resetEnvironment}><span className="material-symbols-outlined" aria-hidden="true">close</span> ยกเลิก</button><button className="btn primary" disabled={!environmentProjectId || !environmentName.trim()} onClick={saveEnvironment}>{environment ? "บันทึกการแก้ไข" : "เพิ่มข้อมูล"}</button></div></div>}
      <div className="master-setting-list">{environments.map((item) => <div key={item.testEnvironmentId} className={!item.isActive ? "inactive" : ""}><span><b>{item.environmentName}</b><small>{projects.find((x) => x.projectId === item.projectId)?.projectName ?? "-"} · {item.baseUrl || "ไม่ระบุ URL"}</small></span><button className="table-action icon-only" title="แก้ไข" aria-label={`แก้ไข ${item.environmentName}`} onClick={() => editEnvironment(item)}><span className="material-symbols-outlined" aria-hidden="true">edit</span></button><button className="table-action danger-action icon-only" title="ลบ" aria-label={`ลบ ${item.environmentName}`} onClick={() => deleteEnvironment(item)}><span className="material-symbols-outlined" aria-hidden="true">close</span></button><button className="table-action icon-only" title={item.isActive ? "ปิดใช้" : "เปิดใช้"} aria-label={`${item.isActive ? "ปิดใช้" : "เปิดใช้"} ${item.environmentName}`} onClick={() => toggleEnvironment(item)}><span className="material-symbols-outlined" aria-hidden="true">power_settings_new</span></button></div>)}</div>
    </section>}
    {activeSection === "CrmSync" && <section className="settings-panel-card master-ai-configuration">
      <div className="settings-panel-head"><div><h2>CRM Sync</h2><p>รอบเวลาที่ Background Worker เช็คว่า Ticket ที่ผูกกับ CRM มีการเปลี่ยน Status/ผู้รับผิดชอบไหม — ค่ากลางของทั้งระบบ (Login เข้า CRM เป็นแบบ self-service ต่อ user แล้ว ดูที่ปุ่ม "บัญชี CRM ของฉัน" มุมขวาบน)</p></div></div>
      <div className="master-ai-body">
        <div className="master-ai-form">
          <label>รอบ Poll การเปลี่ยนแปลงจาก CRM (นาที)<input type="number" min={1} max={60} value={crmSyncSettings.pollIntervalMinutes} onChange={(e) => setCrmSyncSettings((current) => ({ ...current, pollIntervalMinutes: Number(e.target.value) }))} /><small>1-60 นาที — เปลี่ยนค่านี้มีผลตั้งแต่รอบถัดไปเลย ไม่ต้อง restart</small></label>
          <div className="master-ai-actions"><button className="btn primary" disabled={savingCrmSync || crmSyncSettings.pollIntervalMinutes < 1 || crmSyncSettings.pollIntervalMinutes > 60} onClick={saveCrmSyncSettings}>{savingCrmSync ? <><span className="spinner inline" aria-hidden="true" /> กำลังบันทึก...</> : <><span className="material-symbols-outlined" aria-hidden="true">check</span> บันทึกการตั้งค่า</>}</button></div>
        </div>
      </div>
    </section>}
    {activeSection === "CrmMapping" && <section className="settings-panel-card">
      <div className="settings-panel-head"><div><h2>CRM Mapping</h2><p>ผูก Project ของ QA Hub เข้ากับ SysProductId/SysVersionId จริงของ CRM สำหรับใช้ตอนสร้าง Ticket</p></div><button className="master-add-button" disabled={crmMappings.length >= projects.length} onClick={() => editCrmMapping()}>+ เพิ่ม</button></div>
      {crmMappingFormOpen && <div className="master-setting-form environment-form"><label>Project<select disabled={!!crmMappingEditing} value={crmMappingProjectId} onChange={(e) => setCrmMappingProjectId(e.target.value)}>{projects.filter((x) => crmMappingEditing || !crmMappings.some((m) => m.projectId === x.projectId)).map((x) => <option key={x.projectId} value={x.projectId}>{x.projectName}</option>)}</select></label><label>CRM Product Id<input autoFocus value={crmMappingProductId} onChange={(e) => setCrmMappingProductId(e.target.value)} /></label><label>CRM Version Id (ไม่บังคับ)<input value={crmMappingVersionId} onChange={(e) => setCrmMappingVersionId(e.target.value)} /></label><div className="master-setting-actions"><button className="btn" onClick={resetCrmMapping}><span className="material-symbols-outlined" aria-hidden="true">close</span> ยกเลิก</button><button className="btn primary" disabled={!crmMappingProjectId || !crmMappingProductId.trim()} onClick={saveCrmMapping}>{crmMappingEditing ? "บันทึกการแก้ไข" : "เพิ่มข้อมูล"}</button></div></div>}
      <div className="master-setting-list">{crmMappings.map((item) => <div key={item.crmProjectMappingId}><span><b>{projects.find((x) => x.projectId === item.projectId)?.projectName ?? "-"}</b><small>Product: {item.crmProductId}{item.crmVersionId ? ` · Version: ${item.crmVersionId}` : ""}</small></span><button className="table-action icon-only" title="แก้ไข" aria-label="แก้ไข CRM Mapping" onClick={() => editCrmMapping(item)}><span className="material-symbols-outlined" aria-hidden="true">edit</span></button><button className="table-action danger-action icon-only" title="ลบ" aria-label="ลบ CRM Mapping" onClick={() => deleteCrmMapping(item)}><span className="material-symbols-outlined" aria-hidden="true">close</span></button></div>)}</div>
    </section>}
    {activeSection === "Email" && <section className="settings-panel-card master-ai-configuration">
      <div className="settings-panel-head"><div><h2>Email / SMTP</h2><p>ค่ากลางสำหรับส่งอีเมลแจ้งเตือน (เช่น ตอนมอบหมายงานผ่าน CRM หรือ CRM ส่งเคสกลับมาหาเจ้าของเรื่อง) — ใช้ Gmail App Password</p></div><Badge tone={emailReady ? "green" : "yellow"}>{emailReady ? "พร้อมใช้งาน" : "ยังไม่พร้อมใช้งาน"}</Badge></div>
      <div className="master-ai-body">
        <div className="master-ai-note"><b>การจัดเก็บที่ปลอดภัย</b><span>App Password ถูกเข้ารหัสและเก็บเฉพาะฝั่ง Server เว้นว่างไว้เพื่อคงค่าเดิม — สร้าง App Password ได้ที่ Google Account &gt; Security &gt; App passwords (ต้องเปิด 2-Step Verification ก่อน)</span></div>
        <div className="master-ai-form">
          <label>SMTP Host<input value={emailConfig.smtpHost} onChange={(e) => setEmailConfig((current) => ({ ...current, smtpHost: e.target.value }))} placeholder="smtp.gmail.com" /></label>
          <label>SMTP Port<input type="number" value={emailConfig.smtpPort} onChange={(e) => setEmailConfig((current) => ({ ...current, smtpPort: Number(e.target.value) }))} placeholder="587" /></label>
          <label>อีเมลผู้ส่ง (Gmail)<input value={emailConfig.senderEmail} onChange={(e) => setEmailConfig((current) => ({ ...current, senderEmail: e.target.value }))} placeholder="เช่น qahub@yourcompany.com" /></label>
          <label>ชื่อผู้ส่งที่แสดง (ไม่บังคับ)<input value={emailConfig.senderDisplayName ?? ""} onChange={(e) => setEmailConfig((current) => ({ ...current, senderDisplayName: e.target.value }))} placeholder="เช่น QA Hub" /></label>
          <label>App Password<input type="password" autoComplete="new-password" value={emailPassword} onChange={(e) => setEmailPassword(e.target.value)} placeholder={emailConfig.hasPassword ? "ตั้งค่าแล้ว — เว้นว่างเพื่อใช้ค่าเดิม" : "กรอก App Password 16 หลักของ Gmail"} /></label>
          <label className="master-ai-toggle"><input type="checkbox" checked={emailConfig.isEnabled} onChange={(e) => setEmailConfig((current) => ({ ...current, isEnabled: e.target.checked }))} /><span>เปิดใช้งานการส่งอีเมล</span></label>
          <div className="master-ai-actions"><small className="master-ai-hint">App Password ถูกเข้ารหัสและเก็บเฉพาะฝั่ง Server</small><button className="btn primary" disabled={savingEmail || !emailConfig.smtpHost.trim() || !emailConfig.senderEmail.trim() || (!emailConfig.hasPassword && !emailPassword.trim())} onClick={saveEmailConfig}>{savingEmail ? <><span className="spinner inline" aria-hidden="true" /> กำลังบันทึก...</> : <><span className="material-symbols-outlined" aria-hidden="true">check</span> บันทึกการตั้งค่า</>}</button></div>
        </div>
        <div className="master-ai-note">
          <b>ทดสอบส่งอีเมล</b>
          <span>ทดสอบด้วยค่าที่บันทึกไว้แล้ว (กด "บันทึกการตั้งค่า" ก่อน ถ้าเพิ่งแก้ไข)</span>
          <div className="master-ai-form" style={{ marginTop: 8 }}>
            <label>ส่งถึง<input value={emailTestTo} onChange={(e) => setEmailTestTo(e.target.value)} placeholder="อีเมลปลายทางสำหรับทดสอบ" /></label>
            <div className="master-ai-actions">
              {testEmailResult && <small className={testEmailResult.ok ? "master-ai-hint" : "master-model-error"}>{testEmailResult.message}</small>}
              <button className="btn" disabled={sendingTestEmail || !emailTestTo.trim()} onClick={sendTestEmail}>{sendingTestEmail ? <><span className="spinner inline" aria-hidden="true" /> กำลังส่ง...</> : "ส่งอีเมลทดสอบ"}</button>
            </div>
          </div>
        </div>
      </div>
    </section>}
  </div>;
}
