import type { BuildItem, ReleaseItem } from "../shared/types";
import { useState, useEffect, useMemo, useCallback } from "react";
import { apiUrl } from "../api";
import { ModalShell } from "../components/ModalShell";
import { Badge } from "../components/Badge";
import { confirmDialog } from "../components/dialogStore";
import { formatThaiDateTime } from "../dateTime";
import { type ModuleItem, type TestCaseItem, type TestCycleItem } from "../shared/appShared";

type RegressionMetrics = { impactedModules:number;recommendedCases:number;regressionCycles:number;totalCycleCases:number;executedCases:number;passedCases:number;failedCases:number;progressPercent:number;passRate:number;openDefects:number;overallStatus:string };
type RegressionCase = { testCaseId:string;testCaseCode:string;title:string;moduleId:string;moduleName:string;priority:string;testType?:string;revisionNo:number;status:string;lastResult?:string;impactType:string;reason:string;isRequired:boolean;riskScore:number };
type RegressionImpact = { releaseId:string;buildId:string;metrics:RegressionMetrics;cases:RegressionCase[];page:number;pageSize:number;totalItems:number;totalPages:number;allCaseIds?:string[] };
type RegressionEnvironment = { testEnvironmentId:string;projectId:string;environmentName:string;isActive:boolean };
type RegressionHistory = {regressionAnalysisId:string;releaseId:string;buildId:string;buildNumber:string;impactedModules:number;recommendedCases:number;minimumPriority:string;changeNotes?:string;analyzedByName?:string;analyzedAt:string};
type RegressionBuildMetrics = {buildId:string;buildNumber:string;totalCases:number;executedCases:number;passedCases:number;failedCases:number;blockedCases:number;notRunCases:number;passRate:number};
type RegressionBaseline = {baseline:RegressionBuildMetrics;target:RegressionBuildMetrics;executedDelta:number;passedDelta:number;failedDelta:number;passRateDelta:number};
type RegressionActivity = {regressionActivityId:string;action:string;details?:string;actorName?:string;createdAt:string};
type RegressionProfile = {id:string;name:string;visibility?:string;isOwner?:boolean;minimumPriority:string;includeSharedDependencies:boolean;databaseChange:boolean;apiChange:boolean;calculationChange:boolean;permissionChange:boolean;installerChange:boolean;defectFix:boolean;directImpactWeight:number;historicalDefectWeight:number;criticalPriorityWeight:number;sharedDependencyWeight:number};
type RegressionSchedule = {regressionScheduleId:string;releaseId:string;regressionProfileId?:string;name:string;isActive:boolean;createdAt:string;environmentId?:string;environmentName?:string;priority:number};
type RegressionNotification = {regressionScheduleId:string;buildId:string;buildNumber:string;scheduleName:string;message:string;createdAt:string};
type RegressionAutomationPreviewItem = {testCaseId:string;testCaseCode:string;title:string;automationCaseId?:string;automationCaseStatus?:string;eligible:boolean;skipReason?:string};
type RegressionAutomationPreview = {items:RegressionAutomationPreviewItem[];eligibleAutomationCaseIds:string[];eligibleCount:number;totalCount:number};

function RegressionAutomationRunModal({testCaseIds,projectId,builds,environments,headers,onClose,onDone}:{testCaseIds:string[];projectId?:string;builds:BuildItem[];environments:RegressionEnvironment[];headers:Record<string,string>;onClose:()=>void;onDone:(message:string)=>void}){
  const [preview,setPreview]=useState<RegressionAutomationPreview|null>(null),[loadingPreview,setLoadingPreview]=useState(true),[error,setError]=useState("");
  const [buildId,setBuildId]=useState(""),[environmentId,setEnvironmentId]=useState(""),[priority,setPriority]=useState(5),[running,setRunning]=useState(false);
  useEffect(()=>{
    setLoadingPreview(true);
    fetch(`${apiUrl}/regression/automation-run-preview`,{method:"POST",headers,body:JSON.stringify({testCaseIds})})
      .then(r=>r.ok?r.json():Promise.reject())
      .then((data:RegressionAutomationPreview)=>setPreview(data))
      .catch(()=>setError("โหลด Automation Run Preview ไม่สำเร็จ"))
      .finally(()=>setLoadingPreview(false));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  },[]);
  const run=async()=>{
    if(!preview||!buildId||!environmentId)return;
    setRunning(true);setError("");
    try{
      const r=await fetch(`${apiUrl}/automation/batch-run?projectId=${projectId}`,{method:"POST",headers,body:JSON.stringify({caseIds:preview.eligibleAutomationCaseIds,buildId,environmentId,agentId:null,priority})});
      if(!r.ok){const p=await r.json().catch(()=>null);throw new Error(p?.detail??"สั่งรัน Automation ไม่สำเร็จ")}
      const result=await r.json() as {created:unknown[];skippedCodes:string[];total:number};
      onDone(`สั่งรัน Automation แล้ว ${result.created.length} รายการ${result.skippedCodes.length?` (ข้าม ${result.skippedCodes.length} รายการที่ไม่ผ่านเงื่อนไข)`:""}`);
    }catch(e){setError(e instanceof Error?e.message:"สั่งรัน Automation ไม่สำเร็จ")}finally{setRunning(false)}
  };
  return <ModalShell labelledBy="regression-automation-run-title" onDismiss={() => { if (!running) onClose(); }}>
      <div className="modal-head"><div><h2 id="regression-automation-run-title">ส่ง Automation Run</h2><small>ตรวจสอบ Test Case ที่พร้อมรันอัตโนมัติจากรายการที่เลือก</small></div><button aria-label="ปิด" disabled={running} onClick={onClose}><span className="material-symbols-outlined" aria-hidden="true">close</span></button></div>
      {error&&<div className="inline-alert error"><span>{error}</span></div>}
      {loadingPreview?<div className="empty"><div className="spinner" /><p>กำลังตรวจสอบ...</p></div>:preview&&<>
        <p>พร้อมรัน {preview.eligibleCount} / {preview.totalCount} รายการ</p>
        <div className="table-wrap"><table className="table-cards"><thead><tr><th>Test Case</th><th>สถานะ</th></tr></thead><tbody>
          {preview.items.map(x=><tr key={x.testCaseId}><td>{x.testCaseCode} · {x.title}</td><td>{x.eligible?<Badge tone="green">พร้อมรัน</Badge>:<span className="muted-text">{x.skipReason}</span>}</td></tr>)}
        </tbody></table></div>
        {preview.eligibleCount>0&&<div className="form-grid">
          <label>Build<select value={buildId} onChange={e=>setBuildId(e.target.value)}><option value="">เลือก Build</option>{builds.map(x=><option key={x.buildId} value={x.buildId}>{x.buildNumber} · {x.applicationVersion||"-"}</option>)}</select></label>
          <label>Environment<select value={environmentId} onChange={e=>setEnvironmentId(e.target.value)}><option value="">เลือก Environment</option>{environments.map(x=><option key={x.testEnvironmentId} value={x.testEnvironmentId}>{x.environmentName}</option>)}</select></label>
          <label>Priority<input type="number" min={1} max={10} value={priority} onChange={e=>setPriority(Number(e.target.value))} /></label>
        </div>}
      </>}
      <div className="modal-actions">
        <button className="btn" disabled={running} onClick={onClose}><span className="material-symbols-outlined" aria-hidden="true">close</span> ยกเลิก</button>
        <button className="btn primary" disabled={running||!preview?.eligibleCount||!buildId||!environmentId} onClick={run}>{running?<><span className="spinner inline" aria-hidden="true" /> กำลังสั่งรัน...</>:<><span className="material-symbols-outlined" aria-hidden="true">play_arrow</span> สั่งรัน {preview?.eligibleCount??0} รายการ</>}</button>
      </div>
    </ModalShell>;
}

export function RegressionPage({projectId,releaseId,buildId,search,canEdit,canRunAutomation,onOpenCycle}:{projectId?:string;releaseId?:string;buildId?:string;search:string;canEdit:boolean;canRunAutomation:boolean;onOpenCycle:(page:"test-cycles"|"execution",cycleId:string)=>void}){
  const [releases,setReleases]=useState<ReleaseItem[]>([]),[builds,setBuilds]=useState<BuildItem[]>([]),[modules,setModules]=useState<ModuleItem[]>([]),[environments,setEnvironments]=useState<RegressionEnvironment[]>([]),[cycles,setCycles]=useState<TestCycleItem[]>([]);
  const [selectedRelease,setSelectedRelease]=useState(releaseId??""),[selectedBuild,setSelectedBuild]=useState(buildId??""),[changedModules,setChangedModules]=useState<string[]>([]),[minimumPriority,setMinimumPriority]=useState("P1"),[shared,setShared]=useState(true),[databaseChange,setDatabaseChange]=useState(false),[apiChange,setApiChange]=useState(false),[calculationChange,setCalculationChange]=useState(false),[permissionChange,setPermissionChange]=useState(false),[installerChange,setInstallerChange]=useState(false),[defectFix,setDefectFix]=useState(false),[sharedComponents,setSharedComponents]=useState(""),[changeNotes,setChangeNotes]=useState("");
  const [impact,setImpact]=useState<RegressionImpact|null>(null),[selectedCases,setSelectedCases]=useState<string[]>([]),[loading,setLoading]=useState(false),[initialLoading,setInitialLoading]=useState(true),[error,setError]=useState(""),[success,setSuccess]=useState(""),[impactFilter,setImpactFilter]=useState(""),[moduleFilter,setModuleFilter]=useState(""),[priorityFilter,setPriorityFilter]=useState("");
  const [caseDetail,setCaseDetail]=useState<TestCaseItem|null>(null),[caseDetailLoading,setCaseDetailLoading]=useState(false);
  const [history,setHistory]=useState<RegressionHistory[]>([]),[baselineBuild,setBaselineBuild]=useState(""),[baseline,setBaseline]=useState<RegressionBaseline|null>(null),[resultFilter,setResultFilter]=useState(""),[defectOnly,setDefectOnly]=useState(false);
  const [activities,setActivities]=useState<RegressionActivity[]>([]),[pageSize,setPageSize]=useState(50),[profileName,setProfileName]=useState(""),[profileVisibility,setProfileVisibility]=useState("Private"),[selectedProfileId,setSelectedProfileId]=useState(""),[profiles,setProfiles]=useState<RegressionProfile[]>([]),[schedules,setSchedules]=useState<RegressionSchedule[]>([]),[notifications,setNotifications]=useState<RegressionNotification[]>([]),[scheduleName,setScheduleName]=useState("Regression เมื่อมี Build ใหม่"),[scheduleEnvironmentId,setScheduleEnvironmentId]=useState(""),[schedulePriority,setSchedulePriority]=useState(5),[directImpactWeight,setDirectImpactWeight]=useState(40),[historicalDefectWeight,setHistoricalDefectWeight]=useState(30),[criticalPriorityWeight,setCriticalPriorityWeight]=useState(20),[sharedDependencyWeight,setSharedDependencyWeight]=useState(10);
  const [suiteModal,setSuiteModal]=useState(false),[suiteName,setSuiteName]=useState(""),[suiteDescription,setSuiteDescription]=useState(""),[riskTier,setRiskTier]=useState("High"),[createCycle,setCreateCycle]=useState(true),[environmentId,setEnvironmentId]=useState(""),[cycleName,setCycleName]=useState(""),[startDate,setStartDate]=useState(""),[endDate,setEndDate]=useState(""),[existingCycle,setExistingCycle]=useState(""),[saving,setSaving]=useState(false);
  const [automationRunModal,setAutomationRunModal]=useState(false);
  const headers=useMemo(()=>({"Content-Type":"application/json",Authorization:`Bearer ${localStorage.getItem("qa.accessToken")}`}),[]);
  const read=useCallback(async(url:string)=>{const r=await fetch(url,{headers});if(!r.ok)throw new Error("โหลดข้อมูล Regression ไม่สำเร็จ");return r.json();},[headers]);
  useEffect(()=>{setSelectedRelease(releaseId??"")},[releaseId]);useEffect(()=>{setSelectedBuild(buildId??"")},[buildId]);
  useEffect(()=>{if(!projectId){setInitialLoading(false);return}setInitialLoading(true);Promise.all([read(`${apiUrl}/releases?projectId=${projectId}`),read(`${apiUrl}/projects/${projectId}/modules`),read(`${apiUrl}/test-environments?projectId=${projectId}`),read(`${apiUrl}/test-cycles?projectId=${projectId}&size=100`)]).then(([releaseRows,moduleRows,environmentRows,cycleRows])=>{setReleases(Array.isArray(releaseRows)?releaseRows:[]);setModules((Array.isArray(moduleRows)?moduleRows:[]).filter((x:ModuleItem)=>x.isActive));setEnvironments((Array.isArray(environmentRows)?environmentRows:[]).filter((x:RegressionEnvironment)=>x.isActive));setCycles(((cycleRows?.items?.rows??cycleRows?.items??[]) as TestCycleItem[]).filter(x=>x.cycleType==="Regression"));}).catch(e=>setError(e.message)).finally(()=>setInitialLoading(false));},[projectId,read]);
  useEffect(()=>{const active=releases.filter(x=>x.status!=="Cancelled");if(active.length===releases.length)return;setReleases(active);if(selectedRelease&&!active.some(x=>x.releaseId===selectedRelease)){setSelectedRelease(active[0]?.releaseId??"");setSelectedBuild("");setImpact(null)}},[releases,selectedRelease]);
  // UI รอบ 4: live flag กันผลของ Release ก่อนหน้ามาทับเมื่อสลับ Release เร็ว ๆ
  useEffect(()=>{if(!selectedRelease){setBuilds([]);return}let live=true;read(`${apiUrl}/releases/${selectedRelease}/builds`).then(rows=>{if(live)setBuilds((Array.isArray(rows)?rows:[]).filter((x:BuildItem)=>x.isActive))}).catch(e=>{if(live)setError(e.message)});return()=>{live=false};},[selectedRelease,read]);
  useEffect(()=>{if(!selectedRelease){setHistory([]);return}let live=true;read(`${apiUrl}/releases/${selectedRelease}/regression-history`).then(rows=>{if(live)setHistory(rows)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false};},[selectedRelease,read,impact]);
  useEffect(()=>{if(!selectedRelease){setActivities([]);return}let live=true;read(`${apiUrl}/releases/${selectedRelease}/regression-activities?size=20`).then(rows=>{if(live)setActivities(rows)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false};},[selectedRelease,read,impact,success]);
  useEffect(()=>{if(!projectId)return;Promise.all([read(`${apiUrl}/projects/${projectId}/regression-profiles`),read(`${apiUrl}/projects/${projectId}/regression-schedules`),read(`${apiUrl}/projects/${projectId}/regression-notifications`)]).then(([profileRows,scheduleRows,notificationRows])=>{setProfiles((profileRows as {regressionProfileId:string;name:string;visibility:string;isOwner:boolean;settingsJson:string}[]).map(x=>({id:x.regressionProfileId,name:x.name,visibility:x.visibility,isOwner:x.isOwner,...JSON.parse(x.settingsJson)})));setSchedules(scheduleRows);setNotifications(notificationRows)}).catch(e=>setError(e.message));},[projectId,read,success]);
  useEffect(()=>{if(!selectedRelease||!selectedBuild||!baselineBuild||baselineBuild===selectedBuild){setBaseline(null);return}read(`${apiUrl}/releases/${selectedRelease}/regression-baseline?baselineBuildId=${baselineBuild}&targetBuildId=${selectedBuild}`).then(setBaseline).catch(e=>setError(e.message));},[selectedRelease,selectedBuild,baselineBuild,read]);
  useEffect(()=>{if(builds.length&&!builds.some(x=>x.buildId===selectedBuild))setSelectedBuild(builds[0].buildId)},[builds,selectedBuild]);
  useEffect(()=>{if(selectedBuild&&!builds.some(x=>x.buildId===selectedBuild&&x.releaseId===selectedRelease)){setSelectedBuild("");setImpact(null)}},[builds,selectedBuild,selectedRelease]);
  const analyze=async(page=1,recordAnalysis=true)=>{if(!selectedRelease||!selectedBuild){setError("กรุณาเลือก Release และ Build");return}setLoading(true);setError("");setSuccess("");try{const r=await fetch(`${apiUrl}/releases/${selectedRelease}/regression-impact`,{method:"POST",headers,body:JSON.stringify({buildId:selectedBuild,changedModuleIds:changedModules,includeSharedDependencies:shared,minimumPriority,databaseChange,apiChange,calculationChange,permissionChange,installerChange,defectFix,sharedComponents,changeNotes,page,pageSize,directImpactWeight,historicalDefectWeight,criticalPriorityWeight,sharedDependencyWeight,recordAnalysis})});if(!r.ok){const p=await r.json().catch(()=>null);throw new Error(p?.detail??"วิเคราะห์ Regression Impact ไม่สำเร็จ")}const data=await r.json() as RegressionImpact;setImpact(data);setSelectedCases(current=>recordAnalysis?data.cases.filter(x=>x.isRequired).map(x=>x.testCaseId):[...new Set([...current,...data.cases.filter(x=>x.isRequired).map(x=>x.testCaseId)])]);}catch(e){setError(e instanceof Error?e.message:"วิเคราะห์ไม่สำเร็จ")}finally{setLoading(false)}};
  const currentSettings=()=>({minimumPriority,includeSharedDependencies:shared,databaseChange,apiChange,calculationChange,permissionChange,installerChange,defectFix,directImpactWeight,historicalDefectWeight,criticalPriorityWeight,sharedDependencyWeight});
  const saveProfile=async()=>{const name=profileName.trim();if(!name||!projectId)return;const settings=currentSettings();setSaving(true);try{const r=await fetch(`${apiUrl}/regression-profiles`,{method:"POST",headers,body:JSON.stringify({projectId,name,visibility:profileVisibility,settingsJson:JSON.stringify(settings)})});if(!r.ok)throw new Error("บันทึก Regression Profile ไม่สำเร็จ");const row=await r.json();setProfiles(current=>[{id:row.regressionProfileId,name,visibility:profileVisibility,isOwner:true,...settings},...current]);setSelectedProfileId(row.regressionProfileId);setProfileName("");setSuccess(`บันทึก Profile “${name}” ลงฐานข้อมูลแล้ว`)}catch(e){setError(e instanceof Error?e.message:"บันทึก Profile ไม่สำเร็จ")}finally{setSaving(false)}};
  const updateProfile=async()=>{const name=profileName.trim();const profile=profiles.find(x=>x.id===selectedProfileId);if(!profile?.isOwner||!name)return;setSaving(true);try{const settings=currentSettings();const r=await fetch(`${apiUrl}/regression-profiles/${profile.id}`,{method:"PUT",headers,body:JSON.stringify({name,visibility:profileVisibility,settingsJson:JSON.stringify(settings)})});if(!r.ok)throw new Error("อัปเดต Regression Profile ไม่สำเร็จ");setProfiles(current=>current.map(x=>x.id===profile.id?{...x,name,visibility:profileVisibility,...settings}:x));setSuccess(`อัปเดต Profile “${name}” แล้ว`)}catch(e){setError(e instanceof Error?e.message:"อัปเดต Profile ไม่สำเร็จ")}finally{setSaving(false)}};
  const applyProfile=(id:string)=>{const p=profiles.find(x=>x.id===id);if(!p)return;setMinimumPriority(p.minimumPriority);setShared(p.includeSharedDependencies);setDatabaseChange(p.databaseChange);setApiChange(p.apiChange);setCalculationChange(p.calculationChange);setPermissionChange(p.permissionChange);setInstallerChange(p.installerChange);setDefectFix(p.defectFix);setDirectImpactWeight(p.directImpactWeight);setHistoricalDefectWeight(p.historicalDefectWeight);setCriticalPriorityWeight(p.criticalPriorityWeight);setSharedDependencyWeight(p.sharedDependencyWeight);if(p.isOwner){setProfileName(p.name);setProfileVisibility(p.visibility??"Private")}setImpact(null);setSuccess(`ใช้ Profile “${p.name}” แล้ว`)};
  const deleteProfile=async()=>{if(!selectedProfileId||!await confirmDialog("ยืนยันลบ Regression Profile นี้?"))return;const r=await fetch(`${apiUrl}/regression-profiles/${selectedProfileId}`,{method:"DELETE",headers});if(!r.ok){setError("ลบ Profile ไม่สำเร็จหรือคุณไม่ใช่เจ้าของ");return}setProfiles(current=>current.filter(x=>x.id!==selectedProfileId));setSelectedProfileId("");setSuccess("ลบ Regression Profile แล้ว")};
  const acknowledgeNotification=async(item:RegressionNotification)=>{if(!canEdit)return;setSaving(true);try{const r=await fetch(`${apiUrl}/regression-schedules/${item.regressionScheduleId}/acknowledge/${item.buildId}`,{method:"POST",headers});if(!r.ok)throw new Error();setNotifications(current=>current.filter(x=>!(x.regressionScheduleId===item.regressionScheduleId&&x.buildId===item.buildId)));setSuccess("รับทราบการแจ้งเตือนแล้ว")}catch{setError("รับทราบการแจ้งเตือนไม่สำเร็จ")}finally{setSaving(false)}};
  const removeSchedule=async(id:string)=>{if(!await confirmDialog("ยืนยันปิด Scheduled Regression นี้?"))return;setSaving(true);try{const r=await fetch(`${apiUrl}/regression-schedules/${id}`,{method:"DELETE",headers});if(!r.ok)throw new Error();setSchedules(current=>current.filter(x=>x.regressionScheduleId!==id));setNotifications(current=>current.filter(x=>x.regressionScheduleId!==id));setSuccess("ปิด Scheduled Regression แล้ว")}catch{setError("ปิด Schedule ไม่สำเร็จหรือคุณไม่ใช่เจ้าของ")}finally{setSaving(false)}};
  const selectAllPages=async()=>{if(!selectedRelease||!selectedBuild)return;setLoading(true);try{const r=await fetch(`${apiUrl}/releases/${selectedRelease}/regression-impact`,{method:"POST",headers,body:JSON.stringify({buildId:selectedBuild,changedModuleIds:changedModules,includeSharedDependencies:shared,minimumPriority,databaseChange,apiChange,calculationChange,permissionChange,installerChange,defectFix,sharedComponents,changeNotes,page:1,pageSize,directImpactWeight,historicalDefectWeight,criticalPriorityWeight,sharedDependencyWeight,recordAnalysis:false,includeAllCaseIds:true})});if(!r.ok)throw new Error();const data=await r.json() as RegressionImpact;setSelectedCases(data.allCaseIds??[]);setSuccess(`เลือก Test Case ทั้งหมด ${data.totalItems} รายการจากทุกหน้าแล้ว`)}catch{setError("เลือก Test Case ทั้งหมดไม่สำเร็จ")}finally{setLoading(false)}};
  const exportAllPages=async()=>{if(!impact)return;setLoading(true);try{const all:RegressionCase[]=[];for(let page=1;page<=impact.totalPages;page++){const r=await fetch(`${apiUrl}/releases/${selectedRelease}/regression-impact`,{method:"POST",headers,body:JSON.stringify({buildId:selectedBuild,changedModuleIds:changedModules,includeSharedDependencies:shared,minimumPriority,databaseChange,apiChange,calculationChange,permissionChange,installerChange,defectFix,sharedComponents,changeNotes,page,pageSize:200,directImpactWeight,historicalDefectWeight,criticalPriorityWeight,sharedDependencyWeight,recordAnalysis:false})});if(!r.ok)throw new Error();const data=await r.json() as RegressionImpact;all.push(...data.cases);if(page===1&&data.totalPages!==impact.totalPages){page=0;(impact as RegressionImpact).totalPages=data.totalPages;all.length=0}}const headings=["Test Case Code","Title","Module","Priority","Impact Type","Risk Score","Last Result","Reason"];const escape=(v:string)=>`"${v.replaceAll('"','""')}"`;const body="\ufeff"+[headings,...all.map(x=>[x.testCaseCode,x.title,x.moduleName,x.priority,x.impactType,String(x.riskScore),x.lastResult||"Not Run",x.reason])].map(row=>row.map(escape).join(",")).join("\r\n");const url=URL.createObjectURL(new Blob([body],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="Regression_All_Pages.csv";a.click();URL.revokeObjectURL(url)}catch{setError("Export รายงานทุกหน้าไม่สำเร็จ")}finally{setLoading(false)}};
  const saveSchedule=async()=>{if(!selectedRelease||!projectId)return;setSaving(true);try{const r=await fetch(`${apiUrl}/regression-schedules`,{method:"POST",headers,body:JSON.stringify({releaseId:selectedRelease,regressionProfileId:selectedProfileId||null,name:scheduleName,environmentId:scheduleEnvironmentId||null,priority:schedulePriority})});if(!r.ok)throw new Error();const row=await r.json();setSchedules(current=>[...current,row]);setScheduleEnvironmentId("");setSuccess(scheduleEnvironmentId?"เปิด Scheduled Regression พร้อมรัน Automation อัตโนมัติแล้ว":"เปิด Scheduled Regression สำหรับ Build ใหม่แล้ว")}catch{setError("สร้าง Scheduled Regression ไม่สำเร็จ")}finally{setSaving(false)}};
  const visibleCases=useMemo(()=>{const term=search.trim().toLowerCase();return(impact?.cases??[]).filter(x=>(!impactFilter||x.impactType===impactFilter)&&(!moduleFilter||x.moduleId===moduleFilter)&&(!priorityFilter||x.priority===priorityFilter)&&(!resultFilter||(x.lastResult||"Not Run")===resultFilter)&&(!defectOnly||x.impactType==="Historical Defect")&&(!term||`${x.testCaseCode} ${x.title} ${x.moduleName}`.toLowerCase().includes(term)))},[impact,impactFilter,moduleFilter,priorityFilter,resultFilter,defectOnly,search]);
  const toggleCase=(id:string)=>setSelectedCases(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id]);
  const openCaseDetail=async(item:RegressionCase)=>{setCaseDetailLoading(true);setError("");try{setCaseDetail(await read(`${apiUrl}/test-cases/${item.testCaseId}`) as TestCaseItem);}catch(e){setError(e instanceof Error?e.message:"โหลดรายละเอียด Test Case ไม่สำเร็จ")}finally{setCaseDetailLoading(false)}};
  const downloadRegression=(format:"csv"|"xls")=>{if(!impact)return;const rows=visibleCases.map(x=>[x.testCaseCode,x.title,x.moduleName,x.priority,x.impactType,x.lastResult||"Not Run",x.reason]);const headings=["Test Case Code","Title","Module","Priority","Impact Type","Last Result","Reason"];const escape=(value:string)=>`"${value.replaceAll('"','""')}"`;let body:string,mime:string,file:string;if(format==="csv"){body="\ufeff"+[headings,...rows].map(row=>row.map(escape).join(",")).join("\r\n");mime="text/csv;charset=utf-8";file="Regression_Report.csv";}else{body=`<html><head><meta charset="utf-8"></head><body><table><thead><tr>${headings.map(x=>`<th>${x}</th>`).join("")}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${x.replaceAll("&","&amp;").replaceAll("<","&lt;")}</td>`).join("")}</tr>`).join("")}</tbody></table></body></html>`;mime="application/vnd.ms-excel";file="Regression_Report.xls";}const url=URL.createObjectURL(new Blob([body],{type:mime}));const a=document.createElement("a");a.href=url;a.download=file;a.click();URL.revokeObjectURL(url)};
  const toggleVisible=()=>setSelectedCases(current=>visibleCases.every(x=>current.includes(x.testCaseId))?current.filter(id=>!visibleCases.some(x=>x.testCaseId===id)):[...new Set([...current,...visibleCases.map(x=>x.testCaseId)])]);
  const openSuite=()=>{const rel=releases.find(x=>x.releaseId===selectedRelease);setSuiteName(`${rel?.releaseCode??"Release"} Regression`);setCycleName(`${rel?.releaseCode??"Release"} Regression Cycle`);setSuiteDescription(changeNotes);setEnvironmentId(environments[0]?.testEnvironmentId??"");setSuiteModal(true)};
  const generateSuite=async()=>{if(!selectedCases.length||!suiteName.trim())return;setSaving(true);setError("");try{const suiteResponse=await fetch(`${apiUrl}/regression-suites/generate`,{method:"POST",headers,body:JSON.stringify({releaseId:selectedRelease,suiteName,description:suiteDescription,riskTier,testCaseIds:selectedCases})});if(!suiteResponse.ok){const p=await suiteResponse.json().catch(()=>null);throw new Error(p?.detail??"สร้าง Regression Suite ไม่สำเร็จ")}const suite=await suiteResponse.json();let message=`สร้าง ${suite.suiteCode} พร้อม ${suite.caseCount} Test Cases แล้ว`;if(createCycle){if(!environmentId)throw new Error("กรุณาเลือก Environment ก่อนสร้าง Cycle");const cycleResponse=await fetch(`${apiUrl}/test-cycles`,{method:"POST",headers,body:JSON.stringify({projectId,releaseId:selectedRelease,buildId:selectedBuild,environmentId,testSuiteId:suite.testSuiteId,cycleCode:"",cycleName:cycleName||suiteName,cycleType:"Regression",startDate:startDate||null,endDate:endDate||null,ownerUserId:null,notes:suiteDescription,populateFromSuite:true,requiredOnly:false})});if(!cycleResponse.ok){const p=await cycleResponse.json().catch(()=>null);throw new Error(p?.detail??"สร้าง Regression Cycle ไม่สำเร็จ")}const cycle=await cycleResponse.json();message+=` และสร้าง ${cycle.cycleCode} แล้ว`;setCycles(current=>[cycle,...current]);}setSuccess(message);setSuiteModal(false);await analyze();}catch(e){setError(e instanceof Error?e.message:"บันทึกไม่สำเร็จ")}finally{setSaving(false)}};
  const addToCycle=async()=>{if(!existingCycle||!selectedCases.length)return;setSaving(true);setError("");try{const r=await fetch(`${apiUrl}/test-cycles/${existingCycle}/add-impact-cases`,{method:"POST",headers,body:JSON.stringify({testCaseIds:selectedCases})});if(!r.ok)throw new Error("เพิ่ม Impact Cases เข้า Cycle ไม่สำเร็จ");setSuccess(`เพิ่ม ${selectedCases.length} Test Cases เข้า Regression Cycle แล้ว`);setExistingCycle("");await analyze();}catch(e){setError(e instanceof Error?e.message:"บันทึกไม่สำเร็จ")}finally{setSaving(false)}};
  const metrics=impact?.metrics??{impactedModules:0,recommendedCases:0,regressionCycles:0,totalCycleCases:0,executedCases:0,passedCases:0,failedCases:0,progressPercent:0,passRate:0,openDefects:0,overallStatus:"Not Started"};
  const selectedReleaseInfo=releases.find(x=>x.releaseId===selectedRelease);
  const selectedBuildInfo=builds.find(x=>x.buildId===selectedBuild);
  const stepDone1=!!selectedRelease&&!!selectedBuild,stepDone2=!!impact,stepDone3=selectedCases.length>0;
  const activeStepIndex=[stepDone1,stepDone2,stepDone3].findIndex(v=>!v);
  if(initialLoading)return <article className="card regression-empty"><div className="spinner" /><p>กำลังโหลด Regression workspace...</p></article>;
  return <div className="regression-page">
    <section className="regression-hero" aria-labelledby="regression-workspace-title">
      <div className="regression-hero-copy"><span className="regression-eyebrow"><span className="material-symbols-outlined" aria-hidden="true">replay</span> Regression workspace</span><h2 id="regression-workspace-title">วิเคราะห์ผลกระทบ แล้วเลือกชุดทดสอบที่จำเป็น</h2><p>ลดเวลาการเลือก Test Case ด้วยข้อมูล Module, ประเภทการเปลี่ยนแปลง และประวัติ Defect ของ Release</p><div className="regression-context-chips"><span><span className="material-symbols-outlined" aria-hidden="true">inventory_2</span>{selectedReleaseInfo?`${selectedReleaseInfo.releaseCode} · ${selectedReleaseInfo.version}`:"ยังไม่ได้เลือก Release"}</span><span><span className="material-symbols-outlined" aria-hidden="true">deployed_code</span>{selectedBuildInfo?`Build ${selectedBuildInfo.buildNumber}`:"ยังไม่ได้เลือก Build"}</span></div></div>
      <div className="regression-hero-status"><div className={`regression-progress-ring ${metrics.overallStatus.toLowerCase().replaceAll(" ","-")}`} style={{"--regression-progress":`${metrics.progressPercent}%`} as React.CSSProperties}><span><b>{metrics.progressPercent}%</b><small>Progress</small></span></div><div><small>สถานะรอบปัจจุบัน</small><b>{metrics.overallStatus}</b><span>{metrics.executedCases.toLocaleString()} / {metrics.totalCycleCases.toLocaleString()} รายการทดสอบแล้ว</span></div></div>
      <button className="btn regression-hero-action" disabled={loading||!selectedBuild} onClick={()=>document.getElementById("regression-analysis")?.scrollIntoView({behavior:"smooth",block:"start"})}><span className="material-symbols-outlined" aria-hidden="true">tune</span>ตั้งค่าการวิเคราะห์</button>
    </section>
    <section className="regression-summary" aria-label="Regression summary"><article className="is-blue"><span className="regression-summary-icon blue material-symbols-outlined" aria-hidden="true">account_tree</span><div><small>Impacted Modules</small><b>{metrics.impactedModules.toLocaleString()}</b><span>Module ที่เปลี่ยนแปลง</span></div></article><article className="is-violet"><span className="regression-summary-icon violet material-symbols-outlined" aria-hidden="true">fact_check</span><div><small>Recommended Cases</small><b>{metrics.recommendedCases.toLocaleString()}</b><span>{selectedCases.length.toLocaleString()} รายการที่เลือก</span></div></article><article className="is-green"><span className="regression-summary-icon green material-symbols-outlined" aria-hidden="true">data_check</span><div><small>Regression Progress</small><b>{metrics.progressPercent}%</b><span>{metrics.executedCases.toLocaleString()}/{metrics.totalCycleCases.toLocaleString()} Executed</span></div></article><article className="is-amber"><span className="regression-summary-icon amber material-symbols-outlined" aria-hidden="true">task_alt</span><div><small>Pass Rate</small><b>{metrics.passRate}%</b><span>{metrics.failedCases.toLocaleString()} Failed/Blocked</span></div></article><article className="is-red"><span className="regression-summary-icon red material-symbols-outlined" aria-hidden="true">bug_report</span><div><small>Open Defects</small><b>{metrics.openDefects.toLocaleString()}</b><span className={`regression-health ${metrics.overallStatus.toLowerCase().replaceAll(" ","-")}`}>{metrics.overallStatus}</span></div></article></section>
    <nav className="regression-steps" aria-label="ขั้นตอนการทำ Regression">{([["เลือกบริบทและการเปลี่ยนแปลง","Release · Target Build · Changed Modules",stepDone1,"regression-analysis"],["วิเคราะห์และเลือก Test Case","กด “วิเคราะห์ Impact” แล้วติ๊กรายการที่จะทดสอบ",stepDone2,impact?"regression-results":"regression-analysis"],["สร้าง Suite / Cycle","เพิ่มเข้า Cycle เดิมหรือสร้างใหม่",stepDone3,"regression-results"]] as [string,string,boolean,string][]).map(([title,desc,done,target],index)=>(<button key={String(index)} type="button" aria-current={!done&&index===activeStepIndex?"step":undefined} className={done?"done":index===activeStepIndex?"active":""} onClick={()=>document.getElementById(target)?.scrollIntoView({behavior:"smooth",block:"start"})}><span className="regression-step-no" aria-hidden="true">{done?"✓":String(index+1)}</span><span className="regression-step-text"><b>{title}</b><small>{desc}</small></span></button>))}</nav>
    {error&&<div className="inline-alert error"><span>{error}</span><button type="button" aria-label="ปิดข้อความ" onClick={()=>setError("")}><span className="material-symbols-outlined" aria-hidden="true">close</span></button></div>}{success&&<div className="inline-alert success"><span>{success}</span><button onClick={()=>setSuccess("")}><span className="material-symbols-outlined" aria-hidden="true">close</span></button></div>}
    <section id="regression-analysis" className="card regression-analysis"><div className="regression-section-head"><div><span className="regression-title-icon">◎</span><div><h2><span className="regression-step-chip">ขั้นตอน 1</span>Impact Analysis</h2><p>ระบุส่วนที่เปลี่ยนแปลงเพื่อค้นหา Test Case ที่ควร Regression</p></div></div><span className="regression-analyze-action"><button className="btn primary" disabled={loading||!selectedBuild} onClick={()=>analyze()}>{loading?<><span className="spinner inline" aria-hidden="true" /> กำลังวิเคราะห์...</>:<><span aria-hidden="true">⚡</span> วิเคราะห์ Impact</>}</button>{!selectedBuild&&<small className="regression-analyze-hint">เลือก Release และ Target Build ก่อน</small>}</span></div>
      <div className="regression-profile-bar"><select aria-label="Regression Profile" value={selectedProfileId} onChange={e=>{setSelectedProfileId(e.target.value);applyProfile(e.target.value)}}><option value="">เลือก Profile / Template</option>{profiles.map(x=><option key={x.id} value={x.id}>{x.name}{x.isOwner?"":" (Shared)"}</option>)}</select><input aria-label="ชื่อ Regression Profile" value={profileName} onChange={e=>setProfileName(e.target.value)} placeholder="ชื่อ Profile"/><select aria-label="การมองเห็น Regression Profile" value={profileVisibility} onChange={e=>setProfileVisibility(e.target.value)}><option value="Private">Owner / Private</option><option value="Shared">Shared with Team</option></select><button className="btn" disabled={!profileName.trim()||saving} onClick={saveProfile}><span className="material-symbols-outlined" aria-hidden="true">check</span> บันทึกใหม่</button><button className="btn" disabled={!profiles.find(x=>x.id===selectedProfileId)?.isOwner||!profileName.trim()||saving} onClick={updateProfile}><span className="material-symbols-outlined" aria-hidden="true">edit</span> อัปเดต Profile</button><button className="btn danger" disabled={!selectedProfileId} onClick={deleteProfile}><span className="material-symbols-outlined" aria-hidden="true">close</span> ลบ Profile</button></div>
      <div className="regression-context-grid"><label>Release<select value={selectedRelease} onChange={e=>{setSelectedRelease(e.target.value);setImpact(null)}}><option value="">เลือก Release</option>{releases.filter(x=>!projectId||x.projectId===projectId).map(x=><option key={x.releaseId} value={x.releaseId}>{x.releaseCode} · {x.version}</option>)}</select></label><label>Target Build<select value={selectedBuild} onChange={e=>{setSelectedBuild(e.target.value);setImpact(null)}}><option value="">เลือก Build</option>{builds.map(x=><option key={x.buildId} value={x.buildId}>{x.buildNumber} · {x.applicationVersion||"-"}</option>)}</select></label><label>Minimum Priority<select value={minimumPriority} onChange={e=>setMinimumPriority(e.target.value)}><option>P0</option><option>P1</option><option>P2</option><option>P3</option></select></label></div>
      <div className="regression-analysis-grid"><div className="regression-module-picker"><div className="regression-field-title"><b>Changed Modules</b><small>เลือกได้มากกว่า 1 Module</small></div><div className="regression-module-options">{modules.map(x=><label key={x.moduleId} className={changedModules.includes(x.moduleId)?"selected":""}><input type="checkbox" checked={changedModules.includes(x.moduleId)} onChange={()=>setChangedModules(v=>v.includes(x.moduleId)?v.filter(id=>id!==x.moduleId):[...v,x.moduleId])}/><span><b>{x.moduleCode}</b><small>{x.moduleName}</small></span></label>)}</div></div><div className="regression-change-panel"><div className="regression-field-title"><b>Change Impact</b><small>เลือกประเภทการเปลี่ยนแปลงที่เกี่ยวข้อง</small></div><div className="regression-impact-options">{[["Database / Schema",databaseChange,setDatabaseChange],["API Contract",apiChange,setApiChange],["Calculation",calculationChange,setCalculationChange],["Permission",permissionChange,setPermissionChange],["Update / Installer",installerChange,setInstallerChange],["Defect Fix",defectFix,setDefectFix]] .map(([label,value,setter])=><label key={label as string}><input type="checkbox" checked={value as boolean} onChange={e=>(setter as (v:boolean)=>void)(e.target.checked)}/><span>{label as string}</span></label>)}</div><label>Shared Components<input value={sharedComponents} onChange={e=>setSharedComponents(e.target.value)} placeholder="เช่น Auth, Pricing, Shared Library"/></label><label className="regression-shared-check"><input type="checkbox" checked={shared} onChange={e=>setShared(e.target.checked)}/><span>รวม Shared Dependencies และ Critical P0/P1</span></label></div></div>
      <label className="regression-notes">Change Notes<textarea rows={3} value={changeNotes} onChange={e=>setChangeNotes(e.target.value)} placeholder="สรุปสิ่งที่เปลี่ยนแปลง เพื่อใช้เป็นบริบทของ Suite และ Cycle"/></label>
      <details className="regression-risk-config"><summary>ตั้งค่า Risk Score</summary><p>กำหนดน้ำหนักเพื่อจัดลำดับ Test Case ที่มีความเสี่ยงสูงก่อน (คะแนนสูงสุด 100)</p><div>{[["Direct Impact",directImpactWeight,setDirectImpactWeight],["Historical Defect",historicalDefectWeight,setHistoricalDefectWeight],["Critical P0/P1",criticalPriorityWeight,setCriticalPriorityWeight],["Shared Dependency",sharedDependencyWeight,setSharedDependencyWeight]].map(([label,value,setter])=><label key={label as string}><span>{label as string}<b>{value as number}</b></span><input type="range" min="0" max="60" step="5" value={value as number} onChange={e=>(setter as (v:number)=>void)(Number(e.target.value))}/></label>)}</div></details>
    </section>
    <section id="regression-results" className="card regression-results"><div className="regression-section-head"><div><span className="regression-title-icon">⇄</span><div><h2><span className="regression-step-chip">ขั้นตอน 2</span>Recommended Test Cases</h2><p>{impact?`${impact.cases.length} รายการจากผลวิเคราะห์ · แสดง ${visibleCases.length} · เลือกแล้ว ${selectedCases.length} รายการ`:"เริ่มจากเลือก Module หรือประเภทการเปลี่ยนแปลง แล้วกดวิเคราะห์ Impact"}</p></div></div>{impact&&<div className="regression-result-actions"><button className="btn" onClick={()=>downloadRegression("csv")}><span className="material-symbols-outlined" aria-hidden="true">download</span> Export CSV</button><button className="btn" onClick={()=>downloadRegression("xls")}><span className="material-symbols-outlined" aria-hidden="true">download</span> Export Excel</button><button className="btn" onClick={toggleVisible}>{visibleCases.length&&visibleCases.every(x=>selectedCases.includes(x.testCaseId))?<><span className="material-symbols-outlined" aria-hidden="true">close</span> ยกเลิกที่แสดง</>:<><span aria-hidden="true">☑</span> เลือกทั้งหมดที่แสดง</>}</button></div>}</div>
      {impact&&<div className="regression-server-actions"><button className="btn" disabled={loading} onClick={selectAllPages}><span aria-hidden="true">☑</span> เลือกทั้งหมดทุกหน้า ({impact.totalItems})</button><button className="btn" disabled={loading} onClick={exportAllPages}><span className="material-symbols-outlined" aria-hidden="true">download</span> Export ทุกหน้าพร้อม Risk</button></div>}
      {impact&&<div className="regression-filters"><select aria-label="กรอง Impact Type" value={impactFilter} onChange={e=>setImpactFilter(e.target.value)}><option value="">ทุก Impact Type</option>{[...new Set(impact.cases.map(x=>x.impactType))].map(x=><option key={x}>{x}</option>)}</select><select aria-label="กรอง Module" value={moduleFilter} onChange={e=>setModuleFilter(e.target.value)}><option value="">ทุก Module</option>{[...new Map(impact.cases.map(x=>[x.moduleId,x.moduleName])).entries()].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select><select aria-label="กรอง Priority" value={priorityFilter} onChange={e=>setPriorityFilter(e.target.value)}><option value="">ทุก Priority</option><option>P0</option><option>P1</option><option>P2</option><option>P3</option></select><select aria-label="กรอง Last Result" value={resultFilter} onChange={e=>setResultFilter(e.target.value)}><option value="">ทุก Last Result</option><option>Fail</option><option>Blocked</option><option>Not Run</option><option>Pass</option></select><label className="regression-defect-filter"><input type="checkbox" checked={defectOnly} onChange={e=>setDefectOnly(e.target.checked)}/><span>เคยพบ Defect</span></label></div>}
      {!impact?<div className="regression-empty"><span>◎</span><b>ยังไม่มีผลการวิเคราะห์</b><p>ระบบจะแนะนำ Direct Impact, Shared Dependency, Critical P0/P1 และ Historical Defect Cases</p></div>:visibleCases.length===0?<div className="regression-empty"><span>⌕</span><b>ไม่พบ Test Case ตามตัวกรอง</b><p>ลองเปลี่ยน Impact Type, Module หรือ Priority</p></div>:<div className="regression-case-list">{visibleCases.map(x=><div key={x.testCaseId} className={`regression-case ${selectedCases.includes(x.testCaseId)?"selected":""}`}><input aria-label={`เลือก ${x.testCaseCode} ${x.title}`} type="checkbox" checked={selectedCases.includes(x.testCaseId)} onChange={()=>toggleCase(x.testCaseId)}/><span className="regression-case-main"><span className="regression-case-code"><button className="regression-case-link" disabled={caseDetailLoading} onClick={()=>openCaseDetail(x)} aria-label={`ดูรายละเอียด ${x.testCaseCode}`}>{x.testCaseCode}</button><Badge tone={x.priority==="P0"||x.priority==="P1"?"red":"blue"}>{x.priority}</Badge>{x.isRequired&&<Badge tone="yellow">Required</Badge>}<Badge tone={x.riskScore>=60?"red":x.riskScore>=30?"yellow":"blue"}>Risk {x.riskScore}</Badge></span><strong>{x.title}</strong><small>{x.moduleName} · {x.testType||"ไม่ระบุประเภท"} · Rev. {x.revisionNo}</small></span><span className="regression-case-impact"><Badge tone={x.impactType==="Direct Impact"?"blue":x.impactType==="Historical Defect"?"red":"yellow"}>{x.impactType}</Badge><small>{x.reason}</small></span><span className="regression-last-result"><small>Last Result</small><b className={(x.lastResult||"not-run").toLowerCase()}>{x.lastResult||"Not Run"}</b></span></div>)}</div>}
      {impact&&impact.totalPages>1&&<nav className="regression-pagination" aria-label="หน้ารายการ Recommended Test Cases"><span>หน้า {impact.page} / {impact.totalPages} · ทั้งหมด {impact.totalItems} รายการ</span><label>ต่อหน้า<select value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setTimeout(()=>analyze(1,false),0)}}><option value="25">25</option><option value="50">50</option><option value="100">100</option><option value="200">200</option></select></label><button className="btn" disabled={loading||impact.page<=1} onClick={()=>analyze(impact.page-1,false)}><span aria-hidden="true">‹</span> ก่อนหน้า</button><button className="btn" disabled={loading||impact.page>=impact.totalPages} onClick={()=>analyze(impact.page+1,false)}>ถัดไป <span aria-hidden="true">›</span></button></nav>}
    </section>
    <section className="card regression-schedule"><div className="regression-section-head"><div><span className="regression-title-icon">◷</span><div><h2>Scheduled Regression</h2><p>เตรียม Regression อัตโนมัติและแจ้งเตือนเมื่อมี Active Build ใหม่ — ถ้าเลือก Environment ไว้ ระบบจะวิเคราะห์ Impact และสั่งรัน Automation ให้อัตโนมัติทันทีที่ Build ถูก Mark เป็น Release Candidate</p></div></div><Badge tone={notifications.length?"yellow":"green"}>{notifications.length} Notifications</Badge></div>{notifications.length>0&&<div className="regression-notifications">{notifications.map(x=><div key={`${x.regressionScheduleId}-${x.buildId}`}><span>!</span><p><b>{x.message}</b><small>{x.scheduleName} · {formatThaiDateTime(x.createdAt)}</small></p><button className="btn" disabled={!canEdit||saving} onClick={()=>acknowledgeNotification(x)}><span className="material-symbols-outlined" aria-hidden="true">check</span> รับทราบ</button></div>)}</div>}<div className="regression-schedule-form"><input aria-label="ชื่อ Scheduled Regression" value={scheduleName} onChange={e=>setScheduleName(e.target.value)}/><select aria-label="Profile สำหรับ Scheduled Regression" value={selectedProfileId} onChange={e=>{setSelectedProfileId(e.target.value);applyProfile(e.target.value)}}><option value="">ไม่ใช้ Profile</option>{profiles.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select aria-label="Environment สำหรับรัน Automation อัตโนมัติ (ไม่บังคับ)" value={scheduleEnvironmentId} onChange={e=>setScheduleEnvironmentId(e.target.value)}><option value="">ไม่ตั้งค่า Automation อัตโนมัติ</option>{environments.map(x=><option key={x.testEnvironmentId} value={x.testEnvironmentId}>รัน Automation ที่ {x.environmentName}</option>)}</select>{scheduleEnvironmentId&&<input aria-label="Priority ของ Automation Run อัตโนมัติ" type="number" min={1} max={10} value={schedulePriority} onChange={e=>setSchedulePriority(Number(e.target.value))} />}<button className="btn primary" disabled={!selectedRelease||!scheduleName.trim()||saving} onClick={saveSchedule}><span className="material-symbols-outlined" aria-hidden="true">play_arrow</span> เปิด Schedule</button></div>{schedules.length>0&&<ul className="regression-schedule-list">{schedules.map(x=><li key={x.regressionScheduleId}><span><b>{x.name}</b><small>{releases.find(r=>r.releaseId===x.releaseId)?.releaseCode??"-"} · {x.environmentName?`Automation อัตโนมัติที่ ${x.environmentName}`:"ไม่ได้ตั้งค่า Automation อัตโนมัติ"}</small></span><button className="btn danger" disabled={!canEdit||saving} onClick={()=>removeSchedule(x.regressionScheduleId)}><span aria-hidden="true">⏹</span> ปิด Schedule</button></li>)}</ul>}</section>
    <section className="regression-dashboard-grid"><article className="card regression-trend"><div className="regression-section-head"><div><span className="regression-title-icon">↗</span><div><h2>Regression Trend</h2><p>จำนวน Test Case ที่ระบบแนะนำจากการวิเคราะห์ 6 ครั้งล่าสุด</p></div></div></div><div className="regression-trend-bars">{history.slice(0,6).reverse().map(x=>{const max=Math.max(1,...history.slice(0,6).map(h=>h.recommendedCases));return <div key={x.regressionAnalysisId}><span style={{height:`${Math.max(8,x.recommendedCases*100/max)}%`}} title={`${x.recommendedCases} cases`}></span><small>{x.buildNumber}</small><b>{x.recommendedCases}</b></div>})}{history.length===0&&<p className="regression-helper">ยังไม่มีข้อมูลแนวโน้ม</p>}</div></article><article className="card regression-activity"><div className="regression-section-head"><div><span className="regression-title-icon">⌁</span><div><h2>Recent Activity</h2><p>กิจกรรม Regression ล่าสุดของ Release</p></div></div><Badge tone="blue">{activities.length}</Badge></div><div className="regression-activity-list">{activities.slice(0,6).map(x=><div key={x.regressionActivityId}><span></span><p><b>{x.action}</b><small>{x.details||"-"} · {x.actorName||"System"}</small></p><time>{formatThaiDateTime(x.createdAt,{dateStyle:"short",timeStyle:"short"})}</time></div>)}{activities.length===0&&<p className="regression-helper">ยังไม่มีกิจกรรม</p>}</div></article></section>
    <section className="regression-phase-grid"><article className="card regression-baseline"><div className="regression-section-head"><div><span className="regression-title-icon">Δ</span><div><h2>Baseline Comparison</h2><p>เปรียบเทียบผล Regression ของ Target Build กับ Build ก่อนหน้า</p></div></div></div><label>Baseline Build<select value={baselineBuild} onChange={e=>setBaselineBuild(e.target.value)}><option value="">เลือก Build สำหรับเปรียบเทียบ</option>{builds.filter(x=>x.buildId!==selectedBuild).map(x=><option key={x.buildId} value={x.buildId}>{x.buildNumber} · {x.applicationVersion||"-"}</option>)}</select></label>{baseline?<div className="regression-compare"><div><small>Executed</small><b>{baseline.target.executedCases}</b><span className={baseline.executedDelta>=0?"positive":"negative"}>{baseline.executedDelta>=0?"+":""}{baseline.executedDelta}</span></div><div><small>Passed</small><b>{baseline.target.passedCases}</b><span className={baseline.passedDelta>=0?"positive":"negative"}>{baseline.passedDelta>=0?"+":""}{baseline.passedDelta}</span></div><div><small>Failed</small><b>{baseline.target.failedCases+baseline.target.blockedCases}</b><span className={baseline.failedDelta<=0?"positive":"negative"}>{baseline.failedDelta>=0?"+":""}{baseline.failedDelta}</span></div><div><small>Pass Rate</small><b>{baseline.target.passRate}%</b><span className={baseline.passRateDelta>=0?"positive":"negative"}>{baseline.passRateDelta>=0?"+":""}{baseline.passRateDelta}%</span></div></div>:<p className="regression-helper">{builds.length<2?"Release นี้ยังไม่มี Build อื่นสำหรับเปรียบเทียบ":"เลือก Baseline Build เพื่อดูแนวโน้ม"}</p>}</article><article className="card regression-history"><div className="regression-section-head"><div><span className="regression-title-icon">↺</span><div><h2>Regression History</h2><p>ประวัติการวิเคราะห์ Impact ล่าสุด</p></div></div><Badge tone="blue">{history.length}</Badge></div>{history.length?<div className="regression-history-list">{history.slice(0,6).map(x=><div key={x.regressionAnalysisId}><span><b>Build {x.buildNumber}</b><small>{formatThaiDateTime(x.analyzedAt)} · {x.analyzedByName||"System"}</small></span><span><b>{x.recommendedCases}</b><small>Cases · {x.impactedModules} Modules · {x.minimumPriority}</small></span>{x.changeNotes&&<p>{x.changeNotes}</p>}</div>)}</div>:<p className="regression-helper">ยังไม่มีประวัติการวิเคราะห์สำหรับ Release นี้</p>}</article></section>
    {impact&&selectedCases.length>0&&<div className="regression-selection-bar"><div><b>{selectedCases.length}</b><span>Test Cases ที่เลือก</span></div><div className="regression-existing-cycle"><select aria-label="Regression Cycle ที่มีอยู่" value={existingCycle} onChange={e=>setExistingCycle(e.target.value)}><option value="">เพิ่มเข้า Regression Cycle ที่มีอยู่</option>{cycles.filter(x=>x.releaseId===selectedRelease&&x.buildId===selectedBuild).map(x=><option key={x.testCycleId} value={x.testCycleId}>{x.cycleCode} · {x.cycleName}</option>)}</select><button className="btn" disabled={!existingCycle||saving||!canEdit} onClick={addToCycle}><span className="material-symbols-outlined" aria-hidden="true">add</span> เพิ่มเข้า Cycle</button>{existingCycle&&<><button className="btn" onClick={()=>onOpenCycle("test-cycles",existingCycle)}><span className="material-symbols-outlined" aria-hidden="true">play_arrow</span> เปิด Cycle</button><button className="btn" onClick={()=>onOpenCycle("execution",existingCycle)}><span className="material-symbols-outlined" aria-hidden="true">play_arrow</span> เปิด Execution</button></>}</div><button className="btn" disabled={!canRunAutomation} onClick={()=>setAutomationRunModal(true)}><span className="material-symbols-outlined" aria-hidden="true">smart_toy</span> ส่ง Automation Run</button><button className="btn primary" disabled={!canEdit} onClick={openSuite}><span className="material-symbols-outlined" aria-hidden="true">add</span> สร้าง Regression Suite / Cycle</button></div>}
    {automationRunModal&&<RegressionAutomationRunModal testCaseIds={selectedCases} projectId={projectId} builds={builds} environments={environments} headers={headers} onClose={()=>setAutomationRunModal(false)} onDone={(message)=>{setAutomationRunModal(false);setSuccess(message);setSelectedCases([]);}} />}
    {suiteModal&&<ModalShell labelledBy="regression-suite-title" className="regression-suite-modal" onDismiss={() => { if (!saving) setSuiteModal(false); }}><div className="modal-head"><div><h2 id="regression-suite-title">สร้าง Regression Suite</h2><small>{selectedCases.length} Test Cases ที่เลือก</small></div><button disabled={saving} onClick={()=>setSuiteModal(false)}><span className="material-symbols-outlined" aria-hidden="true">close</span></button></div><div className="form-grid"><label className="full">Suite Name<input value={suiteName} onChange={e=>setSuiteName(e.target.value)}/></label><label>Risk Tier<select value={riskTier} onChange={e=>setRiskTier(e.target.value)}><option>Critical</option><option>High</option><option>Medium</option><option>Low</option></select></label><label className="full">Description<textarea rows={3} value={suiteDescription} onChange={e=>setSuiteDescription(e.target.value)}/></label></div><label className="regression-create-cycle"><input type="checkbox" checked={createCycle} onChange={e=>setCreateCycle(e.target.checked)}/><span><b>สร้าง Regression Cycle ต่อทันที</b><small>ระบบจะนำ Test Case ทั้งหมดใน Suite เข้า Cycle</small></span></label>{createCycle&&<div className="form-grid regression-cycle-fields"><label className="full">Cycle Name<input value={cycleName} onChange={e=>setCycleName(e.target.value)}/></label><label>Environment<select value={environmentId} onChange={e=>setEnvironmentId(e.target.value)}><option value="">เลือก Environment</option>{environments.map(x=><option key={x.testEnvironmentId} value={x.testEnvironmentId}>{x.environmentName}</option>)}</select></label><label>Start Date<input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></label><label>End Date<input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)}/></label></div>}<div className="modal-actions"><button className="btn" disabled={saving} onClick={()=>setSuiteModal(false)}><span className="material-symbols-outlined" aria-hidden="true">close</span> ยกเลิก</button><button className="btn primary" disabled={saving||!suiteName.trim()||(createCycle&&!environmentId)} onClick={generateSuite}>{saving?<><span className="spinner inline" aria-hidden="true" /> กำลังสร้าง...</>:createCycle?<><span className="material-symbols-outlined" aria-hidden="true">add</span> สร้าง Suite และ Cycle</>:<><span className="material-symbols-outlined" aria-hidden="true">add</span> สร้าง Suite</>}</button></div></ModalShell>}
    {caseDetail&&<ModalShell labelledBy="regression-case-detail-title" className="testcase-detail" onDismiss={() => setCaseDetail(null)}><div className="modal-head"><div><h2 id="regression-case-detail-title">{caseDetail.testCaseCode}</h2><small>{modules.find(x=>x.moduleId===caseDetail.moduleId)?.moduleName||"-"}</small></div><button aria-label="ปิดรายละเอียด Test Case" onClick={()=>setCaseDetail(null)}><span className="material-symbols-outlined" aria-hidden="true">close</span></button></div><div className="tc-detail-hero"><h3>{caseDetail.title}</h3><div className="tc-detail-badges"><Badge tone={caseDetail.priority==="P0"||caseDetail.priority==="P1"?"red":"blue"}>{caseDetail.priority}</Badge><Badge tone={caseDetail.status==="Ready"?"green":caseDetail.status==="Deprecated"?"yellow":"blue"}>{caseDetail.status}</Badge>{caseDetail.testType&&<Badge tone="yellow">{caseDetail.testType}</Badge>}</div></div><div className="tc-detail-meta"><div className="tc-detail-meta-item"><span>Revision</span><b>Rev. {caseDetail.revisionNo}</b></div><div className="tc-detail-meta-item"><span>Module</span><b>{modules.find(x=>x.moduleId===caseDetail.moduleId)?.moduleCode||"-"}</b></div><div className="tc-detail-meta-item"><span>Execution Type</span><b>{caseDetail.automationCandidate?"Automation Candidate":"Manual"}</b></div></div><section className="tc-detail-section"><h3>Objective</h3><p className="tc-detail-body">{caseDetail.objective||"ไม่ระบุวัตถุประสงค์"}</p></section>{caseDetail.preconditions&&<section className="tc-detail-section"><h3>Preconditions</h3><p className="tc-detail-body">{caseDetail.preconditions}</p></section>}<section className="tc-detail-section"><h3>Test Steps ({caseDetail.steps?.length??0})</h3><div className="tc-detail-steps">{(caseDetail.steps??[]).map(x=><div key={x.stepNo} className="tc-detail-step"><div className="tc-detail-step-no">{x.stepNo}</div><div className="tc-detail-step-body"><div className="tc-detail-step-action"><strong>Action</strong><p>{x.action}</p></div>{x.testData&&<div className="tc-detail-step-data"><strong>Test Data</strong><p>{x.testData}</p></div>}<div className="tc-detail-step-expect"><strong>Expected Result</strong><p>{x.expectedResult}</p></div></div></div>)}</div></section><div className="modal-actions"><button className="btn primary" onClick={()=>setCaseDetail(null)}><span className="material-symbols-outlined" aria-hidden="true">close</span> ปิด</button></div></ModalShell>}
  </div>
}
